In [1]:
import sqlite3

In [2]:
conn = sqlite3.connect('demo_tb.db')

cursor = conn.cursor()

In [3]:
sql = open('./sql/create.sql', 'r').read()
cursor.executescript(sql)

In [4]:
# 트랜잭션 커밋
conn.commit()

In [5]:
query = 'SELECT * FROM customers'
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

### SQL SELECT

In [6]:
query = 'SELECT CustomerName, City FROM customers'
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Alfreds Futterkiste', 'Berlin')
('Ana Trujillo Emparedados y helados', 'México D.F.')
('Antonio Moreno Taquería', 'México D.F.')
('Around the Horn', 'London')
('Berglunds snabbköp', 'Luleå')
('Blauer See Delikatessen', 'Mannheim')
('Blondel père et fils', 'Strasbourg')
('Bólido Comidas preparadas', 'Madrid')
("Bon app''", 'Marseille')
('Bottom-Dollar Marketse', 'Tsawassen')
("B''s Beverages", 'London')
('Cactus Comidas para llevar', 'Buenos Aires')
('Centro comercial Moctezuma', 'México D.F.')
('Chop-suey Chinese', 'Bern')
('Comércio Mineiro', 'São Paulo')
('Consolidated Holdings', 'London')
('Drachenblut Delikatessend', 'Aachen')
('Du monde entier', 'Nantes')
('Eastern Connection', 'London')
('Ernst Handel', 'Graz')
('Familia Arquibaldo', 'São Paulo')
('FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Folies gourmandes', 'Lille')
('Folk och fä HB', 'Bräcke')
('Frankenversand', 'München')
('France restauration', 'Nantes')
('Franchi S.p.A.', 'Torino')
('Furia Bacalhau e Frutos do Mar', 'Lisboa')
('Galería del gastrónomo', 'Barcelona')
('Godos Cocina Típica', 'Sevilla')
('Gourmet Lanchonetes', 'Campinas')
('Great Lakes Food Market', 'Eugene')
('GROSELLA-Restaurante', 'Caracas')
('Hanari Carnes', 'Rio de Janeiro')
('HILARIÓN-Abastos', 'San Cristóbal')
('Hungry Coyote Import Store', 'Elgin')
('Hungry Owl All-Night Grocers', 'Cork')
('Island Trading', 'Cowes')
('Königlich Essen', 'Brandenburg')
("La corne d''abondance", 'Versailles')
("La maison d''Asie", 'Toulouse')
('Laughing Bacchus Wine Cellars', 'Vancouver')
('Lazy K Kountry Store', 'Walla Walla')
('Lehmanns Marktstand', 'Frankfurt a.M.')
("Let''s Stop N Shop", 'San Francisco')
('LILA-Supermercado', 'Barquisimeto')
('LINO-Delicateses', 'I. de Margarita')
('Lonesome Pine Restaurant', 'Portland')
('Magazzini Alimentari Riuniti', 'Bergamo')
('Maison Dewey', 'Bruxelles')
('Mère Paillarde', 'Montréal')
('Morgenstern Gesundkost', 'Leipzig')
('North/South', 'London')
('Océano Atlántico Ltda.', 'Buenos Aires')
('Old World Delicatessen', 'Anchorage')
('Ottilies Käseladen', 'Köln')
('Paris spécialités', 'Paris')
('Pericles Comidas clásicas', 'México D.F.')
('Piccolo und mehr', 'Salzburg')
('Princesa Isabel Vinhoss', 'Lisboa')
('Que Delícia', 'Rio de Janeiro')
('Queen Cozinha', 'São Paulo')
('QUICK-Stop', 'Cunewalde')
('Rancho grande', 'Buenos Aires')
('Rattlesnake Canyon Grocery', 'Albuquerque')
('Reggiani Caseifici', 'Reggio Emilia')
('Ricardo Adocicados', 'Rio de Janeiro')
('Richter Supermarkt', 'Genève')
('Romero y tomillo', 'Madrid')
('Santé Gourmet', 'Stavern')
('Save-a-lot Markets', 'Boise')
('Seven Seas Imports', 'London')
('Simons bistro', 'København')
('Spécialités du monde', 'Paris')
('Split Rail Beer & Ale', 'Lander')
('Suprêmes délices', 'Charleroi')
('The Big Cheese', 'Portland')
('The Cracker Box', 'Butte')
('Toms Spezialitäten', 'Münster')
('Tortuga Restaurante', 'México D.F.')
('Tradição Hipermercados', 'São Paulo')
("Trail''s Head Gourmet Provisioners", 'Kirkland')
('Vaffeljernet', 'Århus')
('Victuailles en stock', 'Lyon')
('Vins et alcools Chevalier', 'Reims')
('Die Wandernde Kuh', 'Stuttgart')
('Wartian Herkku', 'Oulu')
('Wellington Importadora', 'Resende')
('White Clover Markets', 'Seattle')
('Wilman Kala', 'Helsinki')
('Wolski', 'Walla')

### SQL SELECT DISTINCT

In [7]:
query = 'SELECT DISTINCT Country FROM customers'
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Germany',)
('Mexico',)
('UK',)
('Sweden',)
('France',)
('Spain',)
('Canada',)
('Argentina',)
('Switzerland',)
('Brazil',)
('Austria',)
('Italy',)
('Portugal',)
('USA',)
('Venezuela',)
('Ireland',)
('Belgium',)
('Norway',)
('Denmark',)
('Finland',)
('Poland',)

In [8]:
query = 'SELECT Country FROM Customers'
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Germany',)
('Mexico',)
('Mexico',)
('UK',)
('Sweden',)
('Germany',)
('France',)
('Spain',)
('France',)
('Canada',)
('UK',)
('Argentina',)
('Mexico',)
('Switzerland',)
('Brazil',)
('UK',)
('Germany',)
('France',)
('UK',)
('Austria',)
('Brazil',)
('Spain',)
('France',)
('Sweden',)
('Germany',)
('France',)
('Italy',)
('Portugal',)
('Spain',)
('Spain',)
('Brazil',)
('USA',)
('Venezuela',)
('Brazil',)
('Venezuela',)
('USA',)
('Ireland',)
('UK',)
('Germany',)
('France',)
('France',)
('Canada',)
('USA',)
('Germany',)
('USA',)
('Venezuela',)
('Venezuela',)
('USA',)
('Italy',)
('Belgium',)
('Canada',)
('Germany',)
('UK',)
('Argentina',)
('USA',)
('Germany',)
('France',)
('Mexico',)
('Austria',)
('Portugal',)
('Brazil',)
('Brazil',)
('Germany',)
('Argentina',)
('USA',)
('Italy',)
('Brazil',)
('Switzerland',)
('Spain',)
('Norway',)
('USA',)
('UK',)
('Denmark',)
('France',)
('USA',)
('Belgium',)
('USA',)
('USA',)
('Germany',)
('Mexico',)
('Brazil',)
('USA',)
('Denmark',)
('France',)
('France',)
('Germany',)
('Finland',)
('Brazil',)
('USA',)
('Finland',)
('Poland',)

### SQL WHERE Clause

In [9]:
query = '''
        SELECT * FROM Customers
        WHERE Country = "Mexico"
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')

### The SQL ORDER BY

In [10]:
query = '''
        SELECT * FROM Customers
        ORDER BY Country
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')

### SQL And

In [11]:
query = '''
        SELECT *
        FROM Customers
        WHERE Country = 'Spain' AND CustomerName LIKE 'B%'
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')

In [16]:
query = '''
        SELECT *
        FROM Customers
        WHERE Country = 'Germany'
        AND City = 'Berlin'
        AND PostalCode LIKE '1%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')

In [17]:
query = '''
        SELECT *
        FROM Customers
        WHERE Country = 'Spain'
        AND (CustomerName LIKE 'G%' OR CustomerName LIKE 'R%');
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')

In [18]:
query = '''
        SELECT *
        FROM Customers
        WHERE Country = 'Spain'
        AND CustomerName LIKE 'G%' OR CustomerName LIKE 'R%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')

### SQL OR Operator

In [19]:
query = '''
        SELECT *
        FROM Customers
        WHERE Country = 'Germany'
        OR Country = 'Spain';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')

In [20]:
query = '''
        SELECT *
        FROM Customers
        WHERE City = 'Berlin' OR CustomerName LIKE 'G%'
        OR Country = 'Norway';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')

In [21]:
query = '''
        SELECT *
        FROM Customers
        WHERE Country = 'Spain'
        AND (CustomerName LIKE 'G%' OR CustomerName LIKE 'R%');
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')

In [22]:
query = '''
        SELECT *
        FROM Customers
        WHERE Country = 'Spain'
        AND CustomerName LIKE 'G%' OR CustomerName LIKE 'R%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')

### SQL NOT Operator

In [23]:
query = '''
        SELECT *
        FROM Customers
        WHERE NOT Country = 'Spain';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

In [24]:
query = '''
        SELECT *
        FROM Customers
        WHERE CustomerName NOT LIKE 'A%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

In [25]:
query = '''
        SELECT *
        FROM Customers
        WHERE CustomerID NOT BETWEEN 10 AND 60;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

In [26]:
query = '''
        SELECT *
        FROM Customers
        WHERE City NOT IN ('Paris', 'London');
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

In [27]:
query = '''
        SELECT *
        FROM Customers
        WHERE NOT CustomerID > 50;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')

In [28]:
query = '''
        SELECT *
        FROM Customers
        WHERE NOT CustomerID < 50;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

### SQL NULL Values

In [29]:
query = '''
        SELECT CustomerName, ContactName, Address
        FROM Customers
        WHERE Address IS NULL;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

In [30]:
query = '''
        SELECT CustomerName, ContactName, Address
        FROM Customers
        WHERE Address IS NOT NULL;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57')
('Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222')
('Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312')
('Around the Horn', 'Thomas Hardy', '120 Hanover Sq.')
('Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8')
('Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57')
('Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber')
('Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67')
("Bon app''", 'Laurence Lebihans', '12, rue des Bouchers')
('Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.')
("B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus')
('Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333')
('Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993')
('Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29')
('Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23')
('Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery')
('Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21')
('Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages')
('Eastern Connection', 'Ann Devon', '35 King George')
('Ernst Handel', 'Roland Mendel', 'Kirchgasse 6')
('Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92')
('FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86')
('Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai')
('Folk och fä HB', 'Maria Larsson', 'Åkergatan 24')
('Frankenversand', 'Peter Franken', 'Berliner Platz 43')
('France restauration', 'Carine Schmitt', '54, rue Royale')
('Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34')
('Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32')
('Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23')
('Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33')
('Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442')
('Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.')
('GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes')
('Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67')
('HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35')
('Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.')
('Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road')
('Island Trading', 'Helen Bennett', 'Garden House Crowther Way')
('Königlich Essen', 'Philip Cramer', 'Maubelstr. 90')
("La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe")
("La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine')
('Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.')
('Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace')
('Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7')
("Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5')
('LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo')
('LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar')
('Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.')
('Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22')
('Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532')
('Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent')
('Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22')
('North/South', 'Simon Crowther', 'South House 300 Queensbridge')
('Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A')
('Old World Delicatessen', 'Rene Phillips', '2743 Bering St.')
('Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369')
('Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne')
('Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321')
('Piccolo und mehr', 'Georg Pipps', 'Geislweg 14')
('Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58')
('Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12')
('Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891')
('QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10')
('Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900')
('Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.')
('Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124')
('Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267')
('Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237')
('Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1')
('Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78')
('Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.')
('Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.')
('Simons bistro', 'Jytte Petersen', 'Vinbæltet 34')
('Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston')
('Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555')
('Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255')
('The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2')
('The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.')
('Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48')
('Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123')
('Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414')
("Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.')
('Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45')
('Victuailles en stock', 'Mary Saveley', '2, rue du Commerce')
('Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye")
('Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900')
('Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38')
('Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12')
('White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B')
('Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45')
('Wolski', 'Zbyszek', 'ul. Filtrowa 68')

### UPDATE Table

In [32]:
query = '''
        UPDATE Customers
        SET ContactName = 'Alfred Schmidt', City = 'Frankfurt'
        WHERE CustomerID = 1;
        '''
cursor.execute(query)
conn.commit()
# 출력
query = 'SELECT * FROM customers'
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Alfred Schmidt', 'Obere Str. 57', 'Frankfurt', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

In [33]:
query = '''
        UPDATE Customers
        SET ContactName = 'Juan'
        WHERE Country = 'Mexico';
        '''
cursor.execute(query)
conn.commit()
# 출력
query = 'SELECT * FROM customers'
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Alfreds Futterkiste', 'Alfred Schmidt', 'Obere Str. 57', 'Frankfurt', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Juan', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Juan', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Juan', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Juan', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

### SQL DELETE Statement

In [35]:
query = '''
        DELETE FROM Customers
        WHERE CustomerName = 'Alfreds Futterkiste';
        '''
cursor.execute(query)
conn.commit()
# 출력
query = 'SELECT * FROM customers'
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2, 'Ana Trujillo Emparedados y helados', 'Juan', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Juan', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Juan', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Juan', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

### SQL TOP, LIMIT, FETCH FIRST or ROWNUM Clause

In [38]:
query = '''
        SELECT * FROM Customers
        LIMIT 3;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2, 'Ana Trujillo Emparedados y helados', 'Juan', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')

In [40]:
query = '''
        SELECT * FROM Customers
        WHERE Country = 'Germany'
        LIMIT 3;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')

In [41]:
query = '''
        SELECT * FROM Customers
        ORDER BY CustomerName DESC
        LIMIT 3;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')

### SQL MIN() and MAX() Functions

In [42]:
query = '''
        SELECT MIN(Price)
        FROM Products;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2.5,)

In [43]:
query = '''
        SELECT MAX(Price)
        FROM Products;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(263.5,)

In [47]:
query = '''
        SELECT MIN(Price) AS SmallestPrice
        FROM Products;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2.5,)

In [49]:
query = '''
        SELECT MIN(Price) AS SmallestPrice, CategoryID
        FROM Products
        GROUP BY CategoryID;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(4.5, 1)
(10, 2)
(9.2, 3)
(2.5, 4)
(7, 5)
(7.45, 6)
(10, 7)
(6, 8)

### SQL COUNT() Function

In [50]:
query = '''
        SELECT COUNT(*)
        FROM Products;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(77,)

In [51]:
query = '''
        SELECT COUNT(ProductID)
        FROM Products
        WHERE Price > 20;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(37,)

In [52]:
query = '''
        SELECT COUNT(DISTINCT Price)
        FROM Products;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(62,)

In [53]:
query = '''
        SELECT COUNT(*) AS [Number of records]
        FROM Products;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(77,)

In [54]:
query = '''
        SELECT COUNT(*) AS [Number of records], CategoryID
        FROM Products
        GROUP BY CategoryID;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(12, 1)
(12, 2)
(13, 3)
(10, 4)
(7, 5)
(6, 6)
(5, 7)
(12, 8)

### SQL SUM() Function

In [55]:
query = '''
        SELECT SUM(Quantity)
        FROM OrderDetails;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(12743,)

In [56]:
query = '''
        SELECT SUM(Quantity)
        FROM OrderDetails
        WHERE ProductId = 11;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(182,)

In [57]:
query = '''
        SELECT SUM(Quantity) AS total
        FROM OrderDetails;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(12743,)

In [58]:
query = '''
        SELECT OrderID, SUM(Quantity) AS [Total Quantity]
        FROM OrderDetails
        GROUP BY OrderID;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(10248, 27)
(10249, 49)
(10250, 60)
(10251, 41)
(10252, 105)
(10253, 102)
(10254, 57)
(10255, 110)
(10256, 27)
(10257, 46)
(10258, 121)
(10259, 11)
(10260, 102)
(10261, 40)
(10262, 29)
(10263, 184)
(10264, 60)
(10265, 50)
(10266, 12)
(10267, 135)
(10268, 14)
(10269, 80)
(10270, 55)
(10271, 24)
(10272, 70)
(10273, 152)
(10274, 27)
(10275, 18)
(10276, 25)
(10277, 32)
(10278, 64)
(10279, 15)
(10280, 62)
(10281, 11)
(10282, 8)
(10283, 76)
(10284, 61)
(10285, 121)
(10286, 140)
(10287, 75)
(10288, 13)
(10289, 39)
(10290, 60)
(10291, 46)
(10292, 20)
(10293, 33)
(10294, 75)
(10295, 4)
(10296, 57)
(10297, 80)
(10298, 125)
(10299, 35)
(10300, 50)
(10301, 30)
(10302, 80)
(10303, 85)
(10304, 42)
(10305, 80)
(10306, 25)
(10307, 13)
(10308, 6)
(10309, 75)
(10310, 15)
(10311, 13)
(10312, 58)
(10313, 12)
(10314, 95)
(10315, 44)
(10316, 80)
(10317, 20)
(10318, 26)
(10319, 52)
(10320, 30)
(10321, 10)
(10322, 20)
(10323, 13)
(10324, 241)
(10325, 71)
(10326, 90)
(10327, 140)
(10328, 59)
(10329, 50)
(10330, 75)
(10331, 15)
(10332, 66)
(10333, 60)
(10334, 18)
(10335, 86)
(10336, 18)
(10337, 137)
(10338, 35)
(10339, 108)
(10340, 72)
(10341, 17)
(10342, 160)
(10343, 69)
(10344, 105)
(10345, 159)
(10346, 56)
(10347, 70)
(10348, 40)
(10349, 24)
(10350, 33)
(10351, 120)
(10352, 30)
(10353, 62)
(10354, 16)
(10355, 50)
(10356, 62)
(10357, 54)
(10358, 40)
(10359, 206)
(10360, 138)
(10361, 109)
(10362, 94)
(10363, 44)
(10364, 35)
(10365, 24)
(10366, 10)
(10367, 76)
(10368, 78)
(10369, 38)
(10370, 65)
(10371, 6)
(10372, 164)
(10373, 130)
(10374, 45)
(10375, 25)
(10376, 42)
(10377, 40)
(10378, 6)
(10379, 44)
(10380, 74)
(10381, 14)
(10382, 165)
(10383, 55)
(10384, 43)
(10385, 38)
(10386, 25)
(10387, 48)
(10388, 75)
(10389, 81)
(10390, 169)
(10391, 18)
(10392, 50)
(10393, 176)
(10394, 20)
(10395, 106)
(10396, 121)
(10397, 28)
(10398, 150)
(10399, 139)
(10400, 86)
(10401, 168)
(10402, 125)
(10403, 91)
(10404, 100)
(10405, 50)
(10406, 89)
(10407, 60)
(10408, 51)
(10409, 24)
(10410, 65)
(10411, 74)
(10412, 20)
(10413, 78)
(10414, 68)
(10415, 22)
(10416, 50)
(10417, 123)
(10418, 146)
(10419, 80)
(10420, 50)
(10421, 59)
(10422, 2)
(10423, 34)
(10424, 139)
(10425, 30)
(10426, 12)
(10427, 35)
(10428, 20)
(10429, 75)
(10430, 195)
(10431, 130)
(10432, 50)
(10433, 28)
(10434, 24)
(10435, 32)
(10436, 99)
(10437, 15)
(10438, 50)
(10439, 67)
(10440, 208)
(10441, 50)
(10442, 170)
(10443, 18)

In [59]:
query = '''
        SELECT SUM(Quantity * 10)
        FROM OrderDetails;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(127430,)

In [60]:
query = '''
        SELECT SUM(Price * Quantity)
        FROM OrderDetails
        LEFT JOIN Products ON OrderDetails.ProductID = Products.ProductID;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(386424.23,)

### SQL AVG() Function

In [61]:
query = '''
        SELECT AVG(Price)
        FROM Products;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(28.866363636363637,)

In [62]:
query = '''
        SELECT AVG(Price)
        FROM Products
        WHERE CategoryID = 1;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(37.979166666666664,)

In [63]:
query = '''
        SELECT AVG(Price) AS [Average Price]
        FROM Products;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(28.866363636363637,)

In [64]:
query = '''
        SELECT * FROM Products
        WHERE price > (SELECT AVG(price) FROM Products);
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)

In [65]:
query = '''
        SELECT AVG(Price) AS AveragePrice, CategoryID
        FROM Products
        GROUP BY CategoryID;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(37.979166666666664, 1)
(23.0625, 2)
(25.16, 3)
(28.73, 4)
(20.25, 5)
(54.00666666666667, 6)
(32.37, 7)
(20.6825, 8)

### SQL LIKE Operator

In [66]:
query = '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE 'a%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2, 'Ana Trujillo Emparedados y helados', 'Juan', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')

In [67]:
query = '''
        SELECT * FROM Customers
        WHERE city LIKE 'L_nd__';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')

In [68]:
query = '''
        SELECT * FROM Customers
        WHERE city LIKE '%L%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

In [69]:
query = '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE 'La%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')

In [70]:
query = '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE 'a%' OR CustomerName LIKE 'b%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2, 'Ana Trujillo Emparedados y helados', 'Juan', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')

In [71]:
query = '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '%a';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(13, 'Centro comercial Moctezuma', 'Juan', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')

In [72]:
query = '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '%or%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(80, 'Tortuga Restaurante', 'Juan', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')

### SQL Wildcards

In [73]:
query = '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE 'a%';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2, 'Ana Trujillo Emparedados y helados', 'Juan', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')

### SQL IN

In [78]:
query = '''
        SELECT * FROM Customers
        WHERE Country IN ('Germany', 'France', 'UK');
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')

In [79]:
query = '''
        SELECT * FROM Customers
        WHERE Country NOT IN ('Germany', 'France', 'UK');
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2, 'Ana Trujillo Emparedados y helados', 'Juan', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Juan', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(58, 'Pericles Comidas clásicas', 'Juan', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(80, 'Tortuga Restaurante', 'Juan', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

In [80]:
query = '''
        SELECT * FROM Customers
        WHERE CustomerID IN (SELECT CustomerID FROM Orders);
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(2, 'Ana Trujillo Emparedados y helados', 'Juan', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Juan', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(13, 'Centro comercial Moctezuma', 'Juan', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(58, 'Pericles Comidas clásicas', 'Juan', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Juan', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

In [81]:
query = '''
        SELECT * FROM Customers
        WHERE CustomerID NOT IN (SELECT CustomerID FROM Orders);
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')

### SQL BETWEEN

In [82]:
query = '''
        SELECT * FROM Products
        WHERE Price BETWEEN 10 AND 20;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14)
(31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18)
(36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18)
(40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4)
(42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5)
(58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15)
(73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15)
(74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10)
(76, 'Lakkalikööri', 23, 1, '500 ml', 18)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13)

In [83]:
query = '''
        SELECT * FROM Products
        WHERE Price NOT BETWEEN 10 AND 20;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22)
(5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)
(6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25)
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(13, 'Konbu', 6, 8, '2 kg box', 6)
(14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25)
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21)
(23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9)
(24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(33, 'Geitost', 15, 4, '500 g', 2.5)
(37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
(41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(45, 'Røgede sild', 21, 8, '1k pkg.', 9.5)
(47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)
(52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(54, 'Tourtière', 25, 6, '16 pies', 7.45)
(55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34)
(61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 28.5)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36)
(71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21.5)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)
(75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75)

In [84]:
query = '''
        SELECT * FROM Products
        WHERE Price BETWEEN 10 AND 20
        AND CategoryID IN (1,2,3);
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15)
(76, 'Lakkalikööri', 23, 1, '500 ml', 18)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13)

In [85]:
query = '''
        SELECT * FROM Products
        WHERE ProductName BETWEEN 'Carnarvon Tigers' AND 'Mozzarella di Giovanni'
        ORDER BY ProductName;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18)
(4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22)
(5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
(58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25)
(52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7)
(71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21.5)
(33, 'Geitost', 15, 4, '500 g', 2.5)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38)
(31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5)
(6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25)
(37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26)
(24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65)
(13, 'Konbu', 6, 8, '2 kg box', 6)
(76, 'Lakkalikööri', 23, 1, '500 ml', 18)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14)
(74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10)
(65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)

In [86]:
query = '''
        SELECT * FROM Products
        WHERE ProductName NOT BETWEEN 'Carnarvon Tigers' AND 'Mozzarella di Giovanni'
        ORDER BY ProductName;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10)
(40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34)
(30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24)
(11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55)
(57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5)
(75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75)
(73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(45, 'Røgede sild', 21, 8, '1k pkg.', 9.5)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10)
(61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 28.5)
(46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25)
(54, 'Tourtière', 25, 6, '16 pies', 7.45)
(23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9)
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5)

In [87]:
query = '''
        SELECT * FROM Orders
        WHERE OrderDate BETWEEN '1996-07-01' AND '1996-07-31';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(10248, 90, 5, '1996-07-04', 3)
(10249, 81, 6, '1996-07-05', 1)
(10250, 34, 4, '1996-07-08', 2)
(10251, 84, 3, '1996-07-08', 1)
(10252, 76, 4, '1996-07-09', 2)
(10253, 34, 3, '1996-07-10', 2)
(10254, 14, 5, '1996-07-11', 2)
(10255, 68, 9, '1996-07-12', 3)
(10256, 88, 3, '1996-07-15', 2)
(10257, 35, 4, '1996-07-16', 3)
(10258, 20, 1, '1996-07-17', 1)
(10259, 13, 4, '1996-07-18', 3)
(10260, 55, 4, '1996-07-19', 1)
(10261, 61, 4, '1996-07-19', 2)
(10262, 65, 8, '1996-07-22', 3)
(10263, 20, 9, '1996-07-23', 3)
(10264, 24, 6, '1996-07-24', 3)
(10265, 7, 2, '1996-07-25', 1)
(10266, 87, 3, '1996-07-26', 3)
(10267, 25, 4, '1996-07-29', 1)
(10268, 33, 8, '1996-07-30', 3)
(10269, 89, 5, '1996-07-31', 1)

### SQL INNER JOIN

In [88]:
query = '''
        SELECT ProductID, ProductName, CategoryName
        FROM Products
        INNER JOIN Categories ON Products.CategoryID = Categories.CategoryID;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(1, 'Chais', 'Beverages')
(2, 'Chang', 'Beverages')
(3, 'Aniseed Syrup', 'Condiments')
(4, "Chef Anton's Cajun Seasoning", 'Condiments')
(5, "Chef Anton's Gumbo Mix", 'Condiments')
(6, "Grandma's Boysenberry Spread", 'Condiments')
(7, "Uncle Bob's Organic Dried Pears", 'Produce')
(8, 'Northwoods Cranberry Sauce', 'Condiments')
(9, 'Mishi Kobe Niku', 'Meat/Poultry')
(10, 'Ikura', 'Seafood')
(11, 'Queso Cabrales', 'Dairy Products')
(12, 'Queso Manchego La Pastora', 'Dairy Products')
(13, 'Konbu', 'Seafood')
(14, 'Tofu', 'Produce')
(15, 'Genen Shouyu', 'Condiments')
(16, 'Pavlova', 'Confections')
(17, 'Alice Mutton', 'Meat/Poultry')
(18, 'Carnarvon Tigers', 'Seafood')
(19, 'Teatime Chocolate Biscuits', 'Confections')
(20, "Sir Rodney's Marmalade", 'Confections')
(21, "Sir Rodney's Scones", 'Confections')
(22, "Gustaf's Knäckebröd", 'Grains/Cereals')
(23, 'Tunnbröd', 'Grains/Cereals')
(24, 'Guaraná Fantástica', 'Beverages')
(25, 'NuNuCa Nuß-Nougat-Creme', 'Confections')
(26, 'Gumbär Gummibärchen', 'Confections')
(27, 'Schoggi Schokolade', 'Confections')
(28, 'Rössle Sauerkraut', 'Produce')
(29, 'Thüringer Rostbratwurst', 'Meat/Poultry')
(30, 'Nord-Ost Matjeshering', 'Seafood')
(31, 'Gorgonzola Telino', 'Dairy Products')
(32, 'Mascarpone Fabioli', 'Dairy Products')
(33, 'Geitost', 'Dairy Products')
(34, 'Sasquatch Ale', 'Beverages')
(35, 'Steeleye Stout', 'Beverages')
(36, 'Inlagd Sill', 'Seafood')
(37, 'Gravad lax', 'Seafood')
(38, 'Côte de Blaye', 'Beverages')
(39, 'Chartreuse verte', 'Beverages')
(40, 'Boston Crab Meat', 'Seafood')
(41, "Jack's New England Clam Chowder", 'Seafood')
(42, 'Singaporean Hokkien Fried Mee', 'Grains/Cereals')
(43, 'Ipoh Coffee', 'Beverages')
(44, 'Gula Malacca', 'Condiments')
(45, 'Røgede sild', 'Seafood')
(46, 'Spegesild', 'Seafood')
(47, 'Zaanse koeken', 'Confections')
(48, 'Chocolade', 'Confections')
(49, 'Maxilaku', 'Confections')
(50, 'Valkoinen suklaa', 'Confections')
(51, 'Manjimup Dried Apples', 'Produce')
(52, 'Filo Mix', 'Grains/Cereals')
(53, 'Perth Pasties', 'Meat/Poultry')
(54, 'Tourtière', 'Meat/Poultry')
(55, 'Pâté chinois', 'Meat/Poultry')
(56, 'Gnocchi di nonna Alice', 'Grains/Cereals')
(57, 'Ravioli Angelo', 'Grains/Cereals')
(58, 'Escargots de Bourgogne', 'Seafood')
(59, 'Raclette Courdavault', 'Dairy Products')
(60, 'Camembert Pierrot', 'Dairy Products')
(61, "Sirop d'érable", 'Condiments')
(62, 'Tarte au sucre', 'Confections')
(63, 'Vegie-spread', 'Condiments')
(64, 'Wimmers gute Semmelknödel', 'Grains/Cereals')
(65, 'Louisiana Fiery Hot Pepper Sauce', 'Condiments')
(66, 'Louisiana Hot Spiced Okra', 'Condiments')
(67, 'Laughing Lumberjack Lager', 'Beverages')
(68, 'Scottish Longbreads', 'Confections')
(69, 'Gudbrandsdalsost', 'Dairy Products')
(70, 'Outback Lager', 'Beverages')
(71, 'Fløtemysost', 'Dairy Products')
(72, 'Mozzarella di Giovanni', 'Dairy Products')
(73, 'Röd Kaviar', 'Seafood')
(74, 'Longlife Tofu', 'Produce')
(75, 'Rhönbräu Klosterbier', 'Beverages')
(76, 'Lakkalikööri', 'Beverages')
(77, 'Original Frankfurter grüne Soße', 'Condiments')

In [89]:
query = '''
        SELECT Orders.OrderID, Customers.CustomerName, Shippers.ShipperName
        FROM ((Orders
        INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID)
        INNER JOIN Shippers ON Orders.ShipperID = Shippers.ShipperID);
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(10248, 'Wilman Kala', 'Federal Shipping')
(10249, 'Tradição Hipermercados', 'Speedy Express')
(10250, 'Hanari Carnes', 'United Package')
(10251, 'Victuailles en stock', 'Speedy Express')
(10252, 'Suprêmes délices', 'United Package')
(10253, 'Hanari Carnes', 'United Package')
(10254, 'Chop-suey Chinese', 'United Package')
(10255, 'Richter Supermarkt', 'Federal Shipping')
(10256, 'Wellington Importadora', 'United Package')
(10257, 'HILARIÓN-Abastos', 'Federal Shipping')
(10258, 'Ernst Handel', 'Speedy Express')
(10259, 'Centro comercial Moctezuma', 'Federal Shipping')
(10260, 'Old World Delicatessen', 'Speedy Express')
(10261, 'Que Delícia', 'United Package')
(10262, 'Rattlesnake Canyon Grocery', 'Federal Shipping')
(10263, 'Ernst Handel', 'Federal Shipping')
(10264, 'Folk och fä HB', 'Federal Shipping')
(10265, 'Blondel père et fils', 'Speedy Express')
(10266, 'Wartian Herkku', 'Federal Shipping')
(10267, 'Frankenversand', 'Speedy Express')
(10268, 'GROSELLA-Restaurante', 'Federal Shipping')
(10269, 'White Clover Markets', 'Speedy Express')
(10270, 'Wartian Herkku', 'Speedy Express')
(10271, 'Split Rail Beer & Ale', 'United Package')
(10272, 'Rattlesnake Canyon Grocery', 'United Package')
(10273, 'QUICK-Stop', 'Federal Shipping')
(10274, 'Vins et alcools Chevalier', 'Speedy Express')
(10275, 'Magazzini Alimentari Riuniti', 'Speedy Express')
(10276, 'Tortuga Restaurante', 'Federal Shipping')
(10277, 'Morgenstern Gesundkost', 'Federal Shipping')
(10278, 'Berglunds snabbköp', 'United Package')
(10279, 'Lehmanns Marktstand', 'United Package')
(10280, 'Berglunds snabbköp', 'Speedy Express')
(10281, 'Romero y tomillo', 'Speedy Express')
(10282, 'Romero y tomillo', 'Speedy Express')
(10283, 'LILA-Supermercado', 'Federal Shipping')
(10284, 'Lehmanns Marktstand', 'Speedy Express')
(10285, 'QUICK-Stop', 'United Package')
(10286, 'QUICK-Stop', 'Federal Shipping')
(10287, 'Ricardo Adocicados', 'Federal Shipping')
(10288, 'Reggiani Caseifici', 'Speedy Express')
(10289, "B''s Beverages", 'Federal Shipping')
(10290, 'Comércio Mineiro', 'Speedy Express')
(10291, 'Que Delícia', 'United Package')
(10292, 'Tradição Hipermercados', 'United Package')
(10293, 'Tortuga Restaurante', 'Federal Shipping')
(10294, 'Rattlesnake Canyon Grocery', 'United Package')
(10295, 'Vins et alcools Chevalier', 'United Package')
(10296, 'LILA-Supermercado', 'Speedy Express')
(10297, 'Blondel père et fils', 'United Package')
(10298, 'Hungry Owl All-Night Grocers', 'United Package')
(10299, 'Ricardo Adocicados', 'United Package')
(10300, 'Magazzini Alimentari Riuniti', 'United Package')
(10301, 'Die Wandernde Kuh', 'United Package')
(10302, 'Suprêmes délices', 'United Package')
(10303, 'Godos Cocina Típica', 'United Package')
(10304, 'Tortuga Restaurante', 'United Package')
(10305, 'Old World Delicatessen', 'Federal Shipping')
(10306, 'Romero y tomillo', 'Federal Shipping')
(10307, 'Lonesome Pine Restaurant', 'United Package')
(10308, 'Ana Trujillo Emparedados y helados', 'Federal Shipping')
(10309, 'Hungry Owl All-Night Grocers', 'Speedy Express')
(10310, 'The Big Cheese', 'United Package')
(10311, 'Du monde entier', 'Federal Shipping')
(10312, 'Die Wandernde Kuh', 'United Package')
(10313, 'QUICK-Stop', 'United Package')
(10314, 'Rattlesnake Canyon Grocery', 'United Package')
(10315, 'Island Trading', 'United Package')
(10316, 'Rattlesnake Canyon Grocery', 'Federal Shipping')
(10317, 'Lonesome Pine Restaurant', 'Speedy Express')
(10318, 'Island Trading', 'United Package')
(10319, 'Tortuga Restaurante', 'Federal Shipping')
(10320, 'Wartian Herkku', 'Federal Shipping')
(10321, 'Island Trading', 'United Package')
(10322, 'Pericles Comidas clásicas', 'Federal Shipping')
(10323, 'Königlich Essen', 'Speedy Express')
(10324, 'Save-a-lot Markets', 'Speedy Express')
(10325, 'Königlich Essen', 'Federal Shipping')
(10326, 'Bólido Comidas preparadas', 'United Package')
(10327, 'Folk och fä HB', 'Speedy Express')
(10328, 'Furia Bacalhau e Frutos do Mar', 'Federal Shipping')
(10329, 'Split Rail Beer & Ale', 'United Package')
(10330, 'LILA-Supermercado', 'Speedy Express')
(10331, "Bon app''", 'Speedy Express')
(10332, 'Mère Paillarde', 'United Package')
(10333, 'Wartian Herkku', 'Federal Shipping')
(10334, 'Victuailles en stock', 'United Package')
(10335, 'Hungry Owl All-Night Grocers', 'United Package')
(10336, 'Princesa Isabel Vinhoss', 'United Package')
(10337, 'Frankenversand', 'Federal Shipping')
(10338, 'Old World Delicatessen', 'Federal Shipping')
(10339, 'Mère Paillarde', 'United Package')
(10340, "Bon app''", 'Federal Shipping')
(10341, 'Simons bistro', 'Federal Shipping')
(10342, 'Frankenversand', 'United Package')
(10343, 'Lehmanns Marktstand', 'Speedy Express')
(10344, 'White Clover Markets', 'United Package')
(10345, 'QUICK-Stop', 'United Package')
(10346, 'Rattlesnake Canyon Grocery', 'Federal Shipping')
(10347, 'Familia Arquibaldo', 'Federal Shipping')
(10348, 'Die Wandernde Kuh', 'United Package')
(10349, 'Split Rail Beer & Ale', 'Speedy Express')
(10350, "La maison d''Asie", 'United Package')
(10351, 'Ernst Handel', 'Speedy Express')
(10352, 'Furia Bacalhau e Frutos do Mar', 'Federal Shipping')
(10353, 'Piccolo und mehr', 'Federal Shipping')
(10354, 'Pericles Comidas clásicas', 'Federal Shipping')
(10355, 'Around the Horn', 'Speedy Express')
(10356, 'Die Wandernde Kuh', 'United Package')
(10357, 'LILA-Supermercado', 'Federal Shipping')
(10358, "La maison d''Asie", 'Speedy Express')
(10359, 'Seven Seas Imports', 'Federal Shipping')
(10360, 'Blondel père et fils', 'Federal Shipping')
(10361, 'QUICK-Stop', 'United Package')
(10362, "Bon app''", 'Speedy Express')
(10363, 'Drachenblut Delikatessend', 'Federal Shipping')
(10364, 'Eastern Connection', 'Speedy Express')
(10365, 'Antonio Moreno Taquería', 'United Package')
(10366, 'Galería del gastrónomo', 'United Package')
(10367, 'Vaffeljernet', 'Federal Shipping')
(10368, 'Ernst Handel', 'United Package')
(10369, 'Split Rail Beer & Ale', 'United Package')
(10370, 'Chop-suey Chinese', 'United Package')
(10371, "La maison d''Asie", 'Speedy Express')
(10372, 'Queen Cozinha', 'United Package')
(10373, 'Hungry Owl All-Night Grocers', 'Federal Shipping')
(10374, 'Wolski', 'Federal Shipping')
(10375, 'Hungry Coyote Import Store', 'United Package')
(10376, 'Mère Paillarde', 'United Package')
(10377, 'Seven Seas Imports', 'Federal Shipping')
(10378, 'Folk och fä HB', 'Federal Shipping')
(10379, 'Que Delícia', 'Speedy Express')
(10380, 'Hungry Owl All-Night Grocers', 'Federal Shipping')
(10381, 'LILA-Supermercado', 'Federal Shipping')
(10382, 'Ernst Handel', 'Speedy Express')
(10383, 'Around the Horn', 'Federal Shipping')
(10384, 'Berglunds snabbköp', 'Federal Shipping')
(10385, 'Split Rail Beer & Ale', 'United Package')
(10386, 'Familia Arquibaldo', 'Federal Shipping')
(10387, 'Santé Gourmet', 'United Package')
(10388, 'Seven Seas Imports', 'Speedy Express')
(10389, 'Bottom-Dollar Marketse', 'United Package')
(10390, 'Ernst Handel', 'Speedy Express')
(10391, 'Drachenblut Delikatessend', 'Federal Shipping')
(10392, 'Piccolo und mehr', 'Federal Shipping')
(10393, 'Save-a-lot Markets', 'Federal Shipping')
(10394, 'Hungry Coyote Import Store', 'Federal Shipping')
(10395, 'HILARIÓN-Abastos', 'Speedy Express')
(10396, 'Frankenversand', 'Federal Shipping')
(10397, 'Princesa Isabel Vinhoss', 'Speedy Express')
(10398, 'Save-a-lot Markets', 'Federal Shipping')
(10399, 'Vaffeljernet', 'Federal Shipping')
(10400, 'Eastern Connection', 'Federal Shipping')
(10401, 'Rattlesnake Canyon Grocery', 'Speedy Express')
(10402, 'Ernst Handel', 'United Package')
(10403, 'Ernst Handel', 'Federal Shipping')
(10404, 'Magazzini Alimentari Riuniti', 'Speedy Express')
(10405, 'LINO-Delicateses', 'Speedy Express')
(10406, 'Queen Cozinha', 'Speedy Express')
(10407, 'Ottilies Käseladen', 'United Package')
(10408, 'Folies gourmandes', 'Speedy Express')
(10409, 'Océano Atlántico Ltda.', 'Speedy Express')
(10410, 'Bottom-Dollar Marketse', 'Federal Shipping')
(10411, 'Bottom-Dollar Marketse', 'Federal Shipping')
(10412, 'Wartian Herkku', 'United Package')
(10413, "La maison d''Asie", 'United Package')
(10414, 'Familia Arquibaldo', 'Federal Shipping')
(10415, 'Hungry Coyote Import Store', 'Speedy Express')
(10416, 'Wartian Herkku', 'Federal Shipping')
(10417, 'Simons bistro', 'Federal Shipping')
(10418, 'QUICK-Stop', 'Speedy Express')
(10419, 'Richter Supermarkt', 'United Package')
(10420, 'Wellington Importadora', 'Speedy Express')
(10421, 'Que Delícia', 'Speedy Express')
(10422, 'Franchi S.p.A.', 'Speedy Express')
(10423, 'Gourmet Lanchonetes', 'Federal Shipping')
(10424, 'Mère Paillarde', 'United Package')
(10425, "La maison d''Asie", 'United Package')
(10426, 'Galería del gastrónomo', 'Speedy Express')
(10427, 'Piccolo und mehr', 'United Package')
(10428, 'Reggiani Caseifici', 'Speedy Express')
(10429, 'Hungry Owl All-Night Grocers', 'United Package')
(10430, 'Ernst Handel', 'Speedy Express')
(10431, 'Bottom-Dollar Marketse', 'United Package')
(10432, 'Split Rail Beer & Ale', 'United Package')
(10433, 'Princesa Isabel Vinhoss', 'Federal Shipping')
(10434, 'Folk och fä HB', 'United Package')
(10435, 'Consolidated Holdings', 'United Package')
(10436, 'Blondel père et fils', 'United Package')
(10437, 'Wartian Herkku', 'Speedy Express')
(10438, 'Toms Spezialitäten', 'United Package')
(10439, 'Mère Paillarde', 'Federal Shipping')
(10440, 'Save-a-lot Markets', 'United Package')
(10441, 'Old World Delicatessen', 'United Package')
(10442, 'Ernst Handel', 'United Package')
(10443, 'Reggiani Caseifici', 'Speedy Express')

### SQL LEFT JOIN

In [90]:
query = '''
        SELECT Customers.CustomerName, Orders.OrderID
        FROM Customers
        LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID
        ORDER BY Customers.CustomerName;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Ana Trujillo Emparedados y helados', 10308)
('Antonio Moreno Taquería', 10365)
('Around the Horn', 10355)
('Around the Horn', 10383)
("B''s Beverages", 10289)
('Berglunds snabbköp', 10278)
('Berglunds snabbköp', 10280)
('Berglunds snabbköp', 10384)
('Blauer See Delikatessen', None)
('Blondel père et fils', 10265)
('Blondel père et fils', 10297)
('Blondel père et fils', 10360)
('Blondel père et fils', 10436)
("Bon app''", 10331)
("Bon app''", 10340)
("Bon app''", 10362)
('Bottom-Dollar Marketse', 10389)
('Bottom-Dollar Marketse', 10410)
('Bottom-Dollar Marketse', 10411)
('Bottom-Dollar Marketse', 10431)
('Bólido Comidas preparadas', 10326)
('Cactus Comidas para llevar', None)
('Centro comercial Moctezuma', 10259)
('Chop-suey Chinese', 10254)
('Chop-suey Chinese', 10370)
('Comércio Mineiro', 10290)
('Consolidated Holdings', 10435)
('Die Wandernde Kuh', 10301)
('Die Wandernde Kuh', 10312)
('Die Wandernde Kuh', 10348)
('Die Wandernde Kuh', 10356)
('Drachenblut Delikatessend', 10363)
('Drachenblut Delikatessend', 10391)
('Du monde entier', 10311)
('Eastern Connection', 10364)
('Eastern Connection', 10400)
('Ernst Handel', 10258)
('Ernst Handel', 10263)
('Ernst Handel', 10351)
('Ernst Handel', 10368)
('Ernst Handel', 10382)
('Ernst Handel', 10390)
('Ernst Handel', 10402)
('Ernst Handel', 10403)
('Ernst Handel', 10430)
('Ernst Handel', 10442)
('FISSA Fabrica Inter. Salchichas S.A.', None)
('Familia Arquibaldo', 10347)
('Familia Arquibaldo', 10386)
('Familia Arquibaldo', 10414)
('Folies gourmandes', 10408)
('Folk och fä HB', 10264)
('Folk och fä HB', 10327)
('Folk och fä HB', 10378)
('Folk och fä HB', 10434)
('France restauration', None)
('Franchi S.p.A.', 10422)
('Frankenversand', 10267)
('Frankenversand', 10337)
('Frankenversand', 10342)
('Frankenversand', 10396)
('Furia Bacalhau e Frutos do Mar', 10328)
('Furia Bacalhau e Frutos do Mar', 10352)
('GROSELLA-Restaurante', 10268)
('Galería del gastrónomo', 10366)
('Galería del gastrónomo', 10426)
('Godos Cocina Típica', 10303)
('Gourmet Lanchonetes', 10423)
('Great Lakes Food Market', None)
('HILARIÓN-Abastos', 10257)
('HILARIÓN-Abastos', 10395)
('Hanari Carnes', 10250)
('Hanari Carnes', 10253)
('Hungry Coyote Import Store', 10375)
('Hungry Coyote Import Store', 10394)
('Hungry Coyote Import Store', 10415)
('Hungry Owl All-Night Grocers', 10298)
('Hungry Owl All-Night Grocers', 10309)
('Hungry Owl All-Night Grocers', 10335)
('Hungry Owl All-Night Grocers', 10373)
('Hungry Owl All-Night Grocers', 10380)
('Hungry Owl All-Night Grocers', 10429)
('Island Trading', 10315)
('Island Trading', 10318)
('Island Trading', 10321)
('Königlich Essen', 10323)
('Königlich Essen', 10325)
('LILA-Supermercado', 10283)
('LILA-Supermercado', 10296)
('LILA-Supermercado', 10330)
('LILA-Supermercado', 10357)
('LILA-Supermercado', 10381)
('LINO-Delicateses', 10405)
("La corne d''abondance", None)
("La maison d''Asie", 10350)
("La maison d''Asie", 10358)
("La maison d''Asie", 10371)
("La maison d''Asie", 10413)
("La maison d''Asie", 10425)
('Laughing Bacchus Wine Cellars', None)
('Lazy K Kountry Store', None)
('Lehmanns Marktstand', 10279)
('Lehmanns Marktstand', 10284)
('Lehmanns Marktstand', 10343)
("Let''s Stop N Shop", None)
('Lonesome Pine Restaurant', 10307)
('Lonesome Pine Restaurant', 10317)
('Magazzini Alimentari Riuniti', 10275)
('Magazzini Alimentari Riuniti', 10300)
('Magazzini Alimentari Riuniti', 10404)
('Maison Dewey', None)
('Morgenstern Gesundkost', 10277)
('Mère Paillarde', 10332)
('Mère Paillarde', 10339)
('Mère Paillarde', 10376)
('Mère Paillarde', 10424)
('Mère Paillarde', 10439)
('North/South', None)
('Océano Atlántico Ltda.', 10409)
('Old World Delicatessen', 10260)
('Old World Delicatessen', 10305)
('Old World Delicatessen', 10338)
('Old World Delicatessen', 10441)
('Ottilies Käseladen', 10407)
('Paris spécialités', None)
('Pericles Comidas clásicas', 10322)
('Pericles Comidas clásicas', 10354)
('Piccolo und mehr', 10353)
('Piccolo und mehr', 10392)
('Piccolo und mehr', 10427)
('Princesa Isabel Vinhoss', 10336)
('Princesa Isabel Vinhoss', 10397)
('Princesa Isabel Vinhoss', 10433)
('QUICK-Stop', 10273)
('QUICK-Stop', 10285)
('QUICK-Stop', 10286)
('QUICK-Stop', 10313)
('QUICK-Stop', 10345)
('QUICK-Stop', 10361)
('QUICK-Stop', 10418)
('Que Delícia', 10261)
('Que Delícia', 10291)
('Que Delícia', 10379)
('Que Delícia', 10421)
('Queen Cozinha', 10372)
('Queen Cozinha', 10406)
('Rancho grande', None)
('Rattlesnake Canyon Grocery', 10262)
('Rattlesnake Canyon Grocery', 10272)
('Rattlesnake Canyon Grocery', 10294)
('Rattlesnake Canyon Grocery', 10314)
('Rattlesnake Canyon Grocery', 10316)
('Rattlesnake Canyon Grocery', 10346)
('Rattlesnake Canyon Grocery', 10401)
('Reggiani Caseifici', 10288)
('Reggiani Caseifici', 10428)
('Reggiani Caseifici', 10443)
('Ricardo Adocicados', 10287)
('Ricardo Adocicados', 10299)
('Richter Supermarkt', 10255)
('Richter Supermarkt', 10419)
('Romero y tomillo', 10281)
('Romero y tomillo', 10282)
('Romero y tomillo', 10306)
('Santé Gourmet', 10387)
('Save-a-lot Markets', 10324)
('Save-a-lot Markets', 10393)
('Save-a-lot Markets', 10398)
('Save-a-lot Markets', 10440)
('Seven Seas Imports', 10359)
('Seven Seas Imports', 10377)
('Seven Seas Imports', 10388)
('Simons bistro', 10341)
('Simons bistro', 10417)
('Split Rail Beer & Ale', 10271)
('Split Rail Beer & Ale', 10329)
('Split Rail Beer & Ale', 10349)
('Split Rail Beer & Ale', 10369)
('Split Rail Beer & Ale', 10385)
('Split Rail Beer & Ale', 10432)
('Spécialités du monde', None)
('Suprêmes délices', 10252)
('Suprêmes délices', 10302)
('The Big Cheese', 10310)
('The Cracker Box', None)
('Toms Spezialitäten', 10438)
('Tortuga Restaurante', 10276)
('Tortuga Restaurante', 10293)
('Tortuga Restaurante', 10304)
('Tortuga Restaurante', 10319)
('Tradição Hipermercados', 10249)
('Tradição Hipermercados', 10292)
("Trail''s Head Gourmet Provisioners", None)
('Vaffeljernet', 10367)
('Vaffeljernet', 10399)
('Victuailles en stock', 10251)
('Victuailles en stock', 10334)
('Vins et alcools Chevalier', 10274)
('Vins et alcools Chevalier', 10295)
('Wartian Herkku', 10266)
('Wartian Herkku', 10270)
('Wartian Herkku', 10320)
('Wartian Herkku', 10333)
('Wartian Herkku', 10412)
('Wartian Herkku', 10416)
('Wartian Herkku', 10437)
('Wellington Importadora', 10256)
('Wellington Importadora', 10420)
('White Clover Markets', 10269)
('White Clover Markets', 10344)
('Wilman Kala', 10248)
('Wolski', 10374)

In [91]:
query = '''
        SELECT Orders.OrderID, Employees.LastName, Employees.FirstName
        FROM Orders
        RIGHT JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID
        ORDER BY Orders.OrderID;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(None, 'West', 'Adam')
(10248, 'Buchanan', 'Steven')
(10249, 'Suyama', 'Michael')
(10250, 'Peacock', 'Margaret')
(10251, 'Leverling', 'Janet')
(10252, 'Peacock', 'Margaret')
(10253, 'Leverling', 'Janet')
(10254, 'Buchanan', 'Steven')
(10255, 'Dodsworth', 'Anne')
(10256, 'Leverling', 'Janet')
(10257, 'Peacock', 'Margaret')
(10258, 'Davolio', 'Nancy')
(10259, 'Peacock', 'Margaret')
(10260, 'Peacock', 'Margaret')
(10261, 'Peacock', 'Margaret')
(10262, 'Callahan', 'Laura')
(10263, 'Dodsworth', 'Anne')
(10264, 'Suyama', 'Michael')
(10265, 'Fuller', 'Andrew')
(10266, 'Leverling', 'Janet')
(10267, 'Peacock', 'Margaret')
(10268, 'Callahan', 'Laura')
(10269, 'Buchanan', 'Steven')
(10270, 'Davolio', 'Nancy')
(10271, 'Suyama', 'Michael')
(10272, 'Suyama', 'Michael')
(10273, 'Leverling', 'Janet')
(10274, 'Suyama', 'Michael')
(10275, 'Davolio', 'Nancy')
(10276, 'Callahan', 'Laura')
(10277, 'Fuller', 'Andrew')
(10278, 'Callahan', 'Laura')
(10279, 'Callahan', 'Laura')
(10280, 'Fuller', 'Andrew')
(10281, 'Peacock', 'Margaret')
(10282, 'Peacock', 'Margaret')
(10283, 'Leverling', 'Janet')
(10284, 'Peacock', 'Margaret')
(10285, 'Davolio', 'Nancy')
(10286, 'Callahan', 'Laura')
(10287, 'Callahan', 'Laura')
(10288, 'Peacock', 'Margaret')
(10289, 'King', 'Robert')
(10290, 'Callahan', 'Laura')
(10291, 'Suyama', 'Michael')
(10292, 'Davolio', 'Nancy')
(10293, 'Davolio', 'Nancy')
(10294, 'Peacock', 'Margaret')
(10295, 'Fuller', 'Andrew')
(10296, 'Suyama', 'Michael')
(10297, 'Buchanan', 'Steven')
(10298, 'Suyama', 'Michael')
(10299, 'Peacock', 'Margaret')
(10300, 'Fuller', 'Andrew')
(10301, 'Callahan', 'Laura')
(10302, 'Peacock', 'Margaret')
(10303, 'King', 'Robert')
(10304, 'Davolio', 'Nancy')
(10305, 'Callahan', 'Laura')
(10306, 'Davolio', 'Nancy')
(10307, 'Fuller', 'Andrew')
(10308, 'King', 'Robert')
(10309, 'Leverling', 'Janet')
(10310, 'Callahan', 'Laura')
(10311, 'Davolio', 'Nancy')
(10312, 'Fuller', 'Andrew')
(10313, 'Fuller', 'Andrew')
(10314, 'Davolio', 'Nancy')
(10315, 'Peacock', 'Margaret')
(10316, 'Davolio', 'Nancy')
(10317, 'Suyama', 'Michael')
(10318, 'Callahan', 'Laura')
(10319, 'King', 'Robert')
(10320, 'Buchanan', 'Steven')
(10321, 'Leverling', 'Janet')
(10322, 'King', 'Robert')
(10323, 'Peacock', 'Margaret')
(10324, 'Dodsworth', 'Anne')
(10325, 'Davolio', 'Nancy')
(10326, 'Peacock', 'Margaret')
(10327, 'Fuller', 'Andrew')
(10328, 'Peacock', 'Margaret')
(10329, 'Peacock', 'Margaret')
(10330, 'Leverling', 'Janet')
(10331, 'Dodsworth', 'Anne')
(10332, 'Leverling', 'Janet')
(10333, 'Buchanan', 'Steven')
(10334, 'Callahan', 'Laura')
(10335, 'King', 'Robert')
(10336, 'King', 'Robert')
(10337, 'Peacock', 'Margaret')
(10338, 'Peacock', 'Margaret')
(10339, 'Fuller', 'Andrew')
(10340, 'Davolio', 'Nancy')
(10341, 'King', 'Robert')
(10342, 'Peacock', 'Margaret')
(10343, 'Peacock', 'Margaret')
(10344, 'Peacock', 'Margaret')
(10345, 'Fuller', 'Andrew')
(10346, 'Leverling', 'Janet')
(10347, 'Peacock', 'Margaret')
(10348, 'Peacock', 'Margaret')
(10349, 'King', 'Robert')
(10350, 'Suyama', 'Michael')
(10351, 'Davolio', 'Nancy')
(10352, 'Leverling', 'Janet')
(10353, 'King', 'Robert')
(10354, 'Callahan', 'Laura')
(10355, 'Suyama', 'Michael')
(10356, 'Suyama', 'Michael')
(10357, 'Davolio', 'Nancy')
(10358, 'Buchanan', 'Steven')
(10359, 'Buchanan', 'Steven')
(10360, 'Peacock', 'Margaret')
(10361, 'Davolio', 'Nancy')
(10362, 'Leverling', 'Janet')
(10363, 'Peacock', 'Margaret')
(10364, 'Davolio', 'Nancy')
(10365, 'Leverling', 'Janet')
(10366, 'Callahan', 'Laura')
(10367, 'King', 'Robert')
(10368, 'Fuller', 'Andrew')
(10369, 'Callahan', 'Laura')
(10370, 'Suyama', 'Michael')
(10371, 'Davolio', 'Nancy')
(10372, 'Buchanan', 'Steven')
(10373, 'Peacock', 'Margaret')
(10374, 'Davolio', 'Nancy')
(10375, 'Leverling', 'Janet')
(10376, 'Davolio', 'Nancy')
(10377, 'Davolio', 'Nancy')
(10378, 'Buchanan', 'Steven')
(10379, 'Fuller', 'Andrew')
(10380, 'Callahan', 'Laura')
(10381, 'Leverling', 'Janet')
(10382, 'Peacock', 'Margaret')
(10383, 'Callahan', 'Laura')
(10384, 'Leverling', 'Janet')
(10385, 'Davolio', 'Nancy')
(10386, 'Dodsworth', 'Anne')
(10387, 'Davolio', 'Nancy')
(10388, 'Fuller', 'Andrew')
(10389, 'Peacock', 'Margaret')
(10390, 'Suyama', 'Michael')
(10391, 'Leverling', 'Janet')
(10392, 'Fuller', 'Andrew')
(10393, 'Davolio', 'Nancy')
(10394, 'Davolio', 'Nancy')
(10395, 'Suyama', 'Michael')
(10396, 'Davolio', 'Nancy')
(10397, 'Buchanan', 'Steven')
(10398, 'Fuller', 'Andrew')
(10399, 'Callahan', 'Laura')
(10400, 'Davolio', 'Nancy')
(10401, 'Davolio', 'Nancy')
(10402, 'Callahan', 'Laura')
(10403, 'Peacock', 'Margaret')
(10404, 'Fuller', 'Andrew')
(10405, 'Davolio', 'Nancy')
(10406, 'King', 'Robert')
(10407, 'Fuller', 'Andrew')
(10408, 'Callahan', 'Laura')
(10409, 'Leverling', 'Janet')
(10410, 'Leverling', 'Janet')
(10411, 'Dodsworth', 'Anne')
(10412, 'Callahan', 'Laura')
(10413, 'Leverling', 'Janet')
(10414, 'Fuller', 'Andrew')
(10415, 'Leverling', 'Janet')
(10416, 'Callahan', 'Laura')
(10417, 'Peacock', 'Margaret')
(10418, 'Peacock', 'Margaret')
(10419, 'Peacock', 'Margaret')
(10420, 'Leverling', 'Janet')
(10421, 'Callahan', 'Laura')
(10422, 'Fuller', 'Andrew')
(10423, 'Suyama', 'Michael')
(10424, 'King', 'Robert')
(10425, 'Suyama', 'Michael')
(10426, 'Peacock', 'Margaret')
(10427, 'Peacock', 'Margaret')
(10428, 'King', 'Robert')
(10429, 'Leverling', 'Janet')
(10430, 'Peacock', 'Margaret')
(10431, 'Peacock', 'Margaret')
(10432, 'Leverling', 'Janet')
(10433, 'Leverling', 'Janet')
(10434, 'Leverling', 'Janet')
(10435, 'Callahan', 'Laura')
(10436, 'Leverling', 'Janet')
(10437, 'Callahan', 'Laura')
(10438, 'Leverling', 'Janet')
(10439, 'Suyama', 'Michael')
(10440, 'Peacock', 'Margaret')
(10441, 'Leverling', 'Janet')
(10442, 'Leverling', 'Janet')
(10443, 'Callahan', 'Laura')

### SQL FULL OUTER JOIN

In [93]:
query = '''
        SELECT Customers.CustomerName, Orders.OrderID
        FROM Customers
        FULL OUTER JOIN Orders ON Customers.CustomerID=Orders.CustomerID
        ORDER BY Customers.CustomerName;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Ana Trujillo Emparedados y helados', 10308)
('Antonio Moreno Taquería', 10365)
('Around the Horn', 10355)
('Around the Horn', 10383)
("B''s Beverages", 10289)
('Berglunds snabbköp', 10278)
('Berglunds snabbköp', 10280)
('Berglunds snabbköp', 10384)
('Blauer See Delikatessen', None)
('Blondel père et fils', 10265)
('Blondel père et fils', 10297)
('Blondel père et fils', 10360)
('Blondel père et fils', 10436)
("Bon app''", 10331)
("Bon app''", 10340)
("Bon app''", 10362)
('Bottom-Dollar Marketse', 10389)
('Bottom-Dollar Marketse', 10410)
('Bottom-Dollar Marketse', 10411)
('Bottom-Dollar Marketse', 10431)
('Bólido Comidas preparadas', 10326)
('Cactus Comidas para llevar', None)
('Centro comercial Moctezuma', 10259)
('Chop-suey Chinese', 10254)
('Chop-suey Chinese', 10370)
('Comércio Mineiro', 10290)
('Consolidated Holdings', 10435)
('Die Wandernde Kuh', 10301)
('Die Wandernde Kuh', 10312)
('Die Wandernde Kuh', 10348)
('Die Wandernde Kuh', 10356)
('Drachenblut Delikatessend', 10363)
('Drachenblut Delikatessend', 10391)
('Du monde entier', 10311)
('Eastern Connection', 10364)
('Eastern Connection', 10400)
('Ernst Handel', 10258)
('Ernst Handel', 10263)
('Ernst Handel', 10351)
('Ernst Handel', 10368)
('Ernst Handel', 10382)
('Ernst Handel', 10390)
('Ernst Handel', 10402)
('Ernst Handel', 10403)
('Ernst Handel', 10430)
('Ernst Handel', 10442)
('FISSA Fabrica Inter. Salchichas S.A.', None)
('Familia Arquibaldo', 10347)
('Familia Arquibaldo', 10386)
('Familia Arquibaldo', 10414)
('Folies gourmandes', 10408)
('Folk och fä HB', 10264)
('Folk och fä HB', 10327)
('Folk och fä HB', 10378)
('Folk och fä HB', 10434)
('France restauration', None)
('Franchi S.p.A.', 10422)
('Frankenversand', 10267)
('Frankenversand', 10337)
('Frankenversand', 10342)
('Frankenversand', 10396)
('Furia Bacalhau e Frutos do Mar', 10328)
('Furia Bacalhau e Frutos do Mar', 10352)
('GROSELLA-Restaurante', 10268)
('Galería del gastrónomo', 10366)
('Galería del gastrónomo', 10426)
('Godos Cocina Típica', 10303)
('Gourmet Lanchonetes', 10423)
('Great Lakes Food Market', None)
('HILARIÓN-Abastos', 10257)
('HILARIÓN-Abastos', 10395)
('Hanari Carnes', 10250)
('Hanari Carnes', 10253)
('Hungry Coyote Import Store', 10375)
('Hungry Coyote Import Store', 10394)
('Hungry Coyote Import Store', 10415)
('Hungry Owl All-Night Grocers', 10298)
('Hungry Owl All-Night Grocers', 10309)
('Hungry Owl All-Night Grocers', 10335)
('Hungry Owl All-Night Grocers', 10373)
('Hungry Owl All-Night Grocers', 10380)
('Hungry Owl All-Night Grocers', 10429)
('Island Trading', 10315)
('Island Trading', 10318)
('Island Trading', 10321)
('Königlich Essen', 10323)
('Königlich Essen', 10325)
('LILA-Supermercado', 10283)
('LILA-Supermercado', 10296)
('LILA-Supermercado', 10330)
('LILA-Supermercado', 10357)
('LILA-Supermercado', 10381)
('LINO-Delicateses', 10405)
("La corne d''abondance", None)
("La maison d''Asie", 10350)
("La maison d''Asie", 10358)
("La maison d''Asie", 10371)
("La maison d''Asie", 10413)
("La maison d''Asie", 10425)
('Laughing Bacchus Wine Cellars', None)
('Lazy K Kountry Store', None)
('Lehmanns Marktstand', 10279)
('Lehmanns Marktstand', 10284)
('Lehmanns Marktstand', 10343)
("Let''s Stop N Shop", None)
('Lonesome Pine Restaurant', 10307)
('Lonesome Pine Restaurant', 10317)
('Magazzini Alimentari Riuniti', 10275)
('Magazzini Alimentari Riuniti', 10300)
('Magazzini Alimentari Riuniti', 10404)
('Maison Dewey', None)
('Morgenstern Gesundkost', 10277)
('Mère Paillarde', 10332)
('Mère Paillarde', 10339)
('Mère Paillarde', 10376)
('Mère Paillarde', 10424)
('Mère Paillarde', 10439)
('North/South', None)
('Océano Atlántico Ltda.', 10409)
('Old World Delicatessen', 10260)
('Old World Delicatessen', 10305)
('Old World Delicatessen', 10338)
('Old World Delicatessen', 10441)
('Ottilies Käseladen', 10407)
('Paris spécialités', None)
('Pericles Comidas clásicas', 10322)
('Pericles Comidas clásicas', 10354)
('Piccolo und mehr', 10353)
('Piccolo und mehr', 10392)
('Piccolo und mehr', 10427)
('Princesa Isabel Vinhoss', 10336)
('Princesa Isabel Vinhoss', 10397)
('Princesa Isabel Vinhoss', 10433)
('QUICK-Stop', 10273)
('QUICK-Stop', 10285)
('QUICK-Stop', 10286)
('QUICK-Stop', 10313)
('QUICK-Stop', 10345)
('QUICK-Stop', 10361)
('QUICK-Stop', 10418)
('Que Delícia', 10261)
('Que Delícia', 10291)
('Que Delícia', 10379)
('Que Delícia', 10421)
('Queen Cozinha', 10372)
('Queen Cozinha', 10406)
('Rancho grande', None)
('Rattlesnake Canyon Grocery', 10262)
('Rattlesnake Canyon Grocery', 10272)
('Rattlesnake Canyon Grocery', 10294)
('Rattlesnake Canyon Grocery', 10314)
('Rattlesnake Canyon Grocery', 10316)
('Rattlesnake Canyon Grocery', 10346)
('Rattlesnake Canyon Grocery', 10401)
('Reggiani Caseifici', 10288)
('Reggiani Caseifici', 10428)
('Reggiani Caseifici', 10443)
('Ricardo Adocicados', 10287)
('Ricardo Adocicados', 10299)
('Richter Supermarkt', 10255)
('Richter Supermarkt', 10419)
('Romero y tomillo', 10281)
('Romero y tomillo', 10282)
('Romero y tomillo', 10306)
('Santé Gourmet', 10387)
('Save-a-lot Markets', 10324)
('Save-a-lot Markets', 10393)
('Save-a-lot Markets', 10398)
('Save-a-lot Markets', 10440)
('Seven Seas Imports', 10359)
('Seven Seas Imports', 10377)
('Seven Seas Imports', 10388)
('Simons bistro', 10341)
('Simons bistro', 10417)
('Split Rail Beer & Ale', 10271)
('Split Rail Beer & Ale', 10329)
('Split Rail Beer & Ale', 10349)
('Split Rail Beer & Ale', 10369)
('Split Rail Beer & Ale', 10385)
('Split Rail Beer & Ale', 10432)
('Spécialités du monde', None)
('Suprêmes délices', 10252)
('Suprêmes délices', 10302)
('The Big Cheese', 10310)
('The Cracker Box', None)
('Toms Spezialitäten', 10438)
('Tortuga Restaurante', 10276)
('Tortuga Restaurante', 10293)
('Tortuga Restaurante', 10304)
('Tortuga Restaurante', 10319)
('Tradição Hipermercados', 10249)
('Tradição Hipermercados', 10292)
("Trail''s Head Gourmet Provisioners", None)
('Vaffeljernet', 10367)
('Vaffeljernet', 10399)
('Victuailles en stock', 10251)
('Victuailles en stock', 10334)
('Vins et alcools Chevalier', 10274)
('Vins et alcools Chevalier', 10295)
('Wartian Herkku', 10266)
('Wartian Herkku', 10270)
('Wartian Herkku', 10320)
('Wartian Herkku', 10333)
('Wartian Herkku', 10412)
('Wartian Herkku', 10416)
('Wartian Herkku', 10437)
('Wellington Importadora', 10256)
('Wellington Importadora', 10420)
('White Clover Markets', 10269)
('White Clover Markets', 10344)
('Wilman Kala', 10248)
('Wolski', 10374)

### SQL SELF JOIN

In [94]:
query = '''
        SELECT A.CustomerName AS CustomerName1, B.CustomerName AS CustomerName2, A.City
        FROM Customers A, Customers B
        WHERE A.CustomerID <> B.CustomerID
        AND A.City = B.City
        ORDER BY A.City;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Cactus Comidas para llevar', 'Océano Atlántico Ltda.', 'Buenos Aires')
('Cactus Comidas para llevar', 'Rancho grande', 'Buenos Aires')
('Océano Atlántico Ltda.', 'Cactus Comidas para llevar', 'Buenos Aires')
('Océano Atlántico Ltda.', 'Rancho grande', 'Buenos Aires')
('Rancho grande', 'Cactus Comidas para llevar', 'Buenos Aires')
('Rancho grande', 'Océano Atlántico Ltda.', 'Buenos Aires')
('Furia Bacalhau e Frutos do Mar', 'Princesa Isabel Vinhoss', 'Lisboa')
('Princesa Isabel Vinhoss', 'Furia Bacalhau e Frutos do Mar', 'Lisboa')
('Around the Horn', "B''s Beverages", 'London')
('Around the Horn', 'Consolidated Holdings', 'London')
('Around the Horn', 'Eastern Connection', 'London')
('Around the Horn', 'North/South', 'London')
('Around the Horn', 'Seven Seas Imports', 'London')
("B''s Beverages", 'Around the Horn', 'London')
("B''s Beverages", 'Consolidated Holdings', 'London')
("B''s Beverages", 'Eastern Connection', 'London')
("B''s Beverages", 'North/South', 'London')
("B''s Beverages", 'Seven Seas Imports', 'London')
('Consolidated Holdings', 'Around the Horn', 'London')
('Consolidated Holdings', "B''s Beverages", 'London')
('Consolidated Holdings', 'Eastern Connection', 'London')
('Consolidated Holdings', 'North/South', 'London')
('Consolidated Holdings', 'Seven Seas Imports', 'London')
('Eastern Connection', 'Around the Horn', 'London')
('Eastern Connection', "B''s Beverages", 'London')
('Eastern Connection', 'Consolidated Holdings', 'London')
('Eastern Connection', 'North/South', 'London')
('Eastern Connection', 'Seven Seas Imports', 'London')
('North/South', 'Around the Horn', 'London')
('North/South', "B''s Beverages", 'London')
('North/South', 'Consolidated Holdings', 'London')
('North/South', 'Eastern Connection', 'London')
('North/South', 'Seven Seas Imports', 'London')
('Seven Seas Imports', 'Around the Horn', 'London')
('Seven Seas Imports', "B''s Beverages", 'London')
('Seven Seas Imports', 'Consolidated Holdings', 'London')
('Seven Seas Imports', 'Eastern Connection', 'London')
('Seven Seas Imports', 'North/South', 'London')
('Bólido Comidas preparadas', 'FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Bólido Comidas preparadas', 'Romero y tomillo', 'Madrid')
('FISSA Fabrica Inter. Salchichas S.A.', 'Bólido Comidas preparadas', 'Madrid')
('FISSA Fabrica Inter. Salchichas S.A.', 'Romero y tomillo', 'Madrid')
('Romero y tomillo', 'Bólido Comidas preparadas', 'Madrid')
('Romero y tomillo', 'FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Ana Trujillo Emparedados y helados', 'Antonio Moreno Taquería', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Centro comercial Moctezuma', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Pericles Comidas clásicas', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Tortuga Restaurante', 'México D.F.')
('Antonio Moreno Taquería', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Antonio Moreno Taquería', 'Centro comercial Moctezuma', 'México D.F.')
('Antonio Moreno Taquería', 'Pericles Comidas clásicas', 'México D.F.')
('Antonio Moreno Taquería', 'Tortuga Restaurante', 'México D.F.')
('Centro comercial Moctezuma', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Centro comercial Moctezuma', 'Antonio Moreno Taquería', 'México D.F.')
('Centro comercial Moctezuma', 'Pericles Comidas clásicas', 'México D.F.')
('Centro comercial Moctezuma', 'Tortuga Restaurante', 'México D.F.')
('Pericles Comidas clásicas', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Pericles Comidas clásicas', 'Antonio Moreno Taquería', 'México D.F.')
('Pericles Comidas clásicas', 'Centro comercial Moctezuma', 'México D.F.')
('Pericles Comidas clásicas', 'Tortuga Restaurante', 'México D.F.')
('Tortuga Restaurante', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Tortuga Restaurante', 'Antonio Moreno Taquería', 'México D.F.')
('Tortuga Restaurante', 'Centro comercial Moctezuma', 'México D.F.')
('Tortuga Restaurante', 'Pericles Comidas clásicas', 'México D.F.')
('Du monde entier', 'France restauration', 'Nantes')
('France restauration', 'Du monde entier', 'Nantes')
('Paris spécialités', 'Spécialités du monde', 'Paris')
('Spécialités du monde', 'Paris spécialités', 'Paris')
('Lonesome Pine Restaurant', 'The Big Cheese', 'Portland')
('The Big Cheese', 'Lonesome Pine Restaurant', 'Portland')
('Hanari Carnes', 'Que Delícia', 'Rio de Janeiro')
('Hanari Carnes', 'Ricardo Adocicados', 'Rio de Janeiro')
('Que Delícia', 'Hanari Carnes', 'Rio de Janeiro')
('Que Delícia', 'Ricardo Adocicados', 'Rio de Janeiro')
('Ricardo Adocicados', 'Hanari Carnes', 'Rio de Janeiro')
('Ricardo Adocicados', 'Que Delícia', 'Rio de Janeiro')
('Comércio Mineiro', 'Familia Arquibaldo', 'São Paulo')
('Comércio Mineiro', 'Queen Cozinha', 'São Paulo')
('Comércio Mineiro', 'Tradição Hipermercados', 'São Paulo')
('Familia Arquibaldo', 'Comércio Mineiro', 'São Paulo')
('Familia Arquibaldo', 'Queen Cozinha', 'São Paulo')
('Familia Arquibaldo', 'Tradição Hipermercados', 'São Paulo')
('Queen Cozinha', 'Comércio Mineiro', 'São Paulo')
('Queen Cozinha', 'Familia Arquibaldo', 'São Paulo')
('Queen Cozinha', 'Tradição Hipermercados', 'São Paulo')
('Tradição Hipermercados', 'Comércio Mineiro', 'São Paulo')
('Tradição Hipermercados', 'Familia Arquibaldo', 'São Paulo')
('Tradição Hipermercados', 'Queen Cozinha', 'São Paulo')

### SQL UNION

In [95]:
query = '''
        SELECT City FROM Customers
        UNION
        SELECT City FROM Suppliers
        ORDER BY City;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Aachen',)
('Albuquerque',)
('Anchorage',)
('Ann Arbor',)
('Annecy',)
('Barcelona',)
('Barquisimeto',)
('Bend',)
('Bergamo',)
('Berlin',)
('Bern',)
('Boise',)
('Boston',)
('Brandenburg',)
('Bruxelles',)
('Bräcke',)
('Buenos Aires',)
('Butte',)
('Campinas',)
('Caracas',)
('Charleroi',)
('Cork',)
('Cowes',)
('Cunewalde',)
('Cuxhaven',)
('Elgin',)
('Eugene',)
('Frankfurt',)
('Frankfurt a.M.',)
('Genève',)
('Graz',)
('Göteborg',)
('Helsinki',)
('I. de Margarita',)
('Kirkland',)
('Köln',)
('København',)
('Lander',)
('Lappeenranta',)
('Leipzig',)
('Lille',)
('Lisboa',)
('London',)
('Londona',)
('Luleå',)
('Lyngby',)
('Lyon',)
('Madrid',)
('Manchester',)
('Mannheim',)
('Marseille',)
('Melbourne',)
('Montceau',)
('Montréal',)
('México D.F.',)
('München',)
('Münster',)
('Nantes',)
('New Orleans',)
('Osaka',)
('Oulu',)
('Oviedo',)
('Paris',)
('Portland',)
('Ravenna',)
('Reggio Emilia',)
('Reims',)
('Resende',)
('Rio de Janeiro',)
('Salerno',)
('Salzburg',)
('San Cristóbal',)
('San Francisco',)
('Sandvika',)
('Seattle',)
('Sevilla',)
('Singapore',)
('Stavern',)
('Ste-Hyacinthe',)
('Stockholm',)
('Strasbourg',)
('Stuttgart',)
('Sydney',)
('São Paulo',)
('Tokyo',)
('Torino',)
('Toulouse',)
('Tsawassen',)
('Vancouver',)
('Versailles',)
('Walla',)
('Walla Walla',)
('Zaandam',)
('Århus',)

In [96]:
query = '''
        SELECT City FROM Customers
        UNION ALL
        SELECT City FROM Suppliers
        ORDER BY City;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Aachen',)
('Albuquerque',)
('Anchorage',)
('Ann Arbor',)
('Annecy',)
('Barcelona',)
('Barquisimeto',)
('Bend',)
('Bergamo',)
('Berlin',)
('Bern',)
('Boise',)
('Boston',)
('Brandenburg',)
('Bruxelles',)
('Bräcke',)
('Buenos Aires',)
('Buenos Aires',)
('Buenos Aires',)
('Butte',)
('Campinas',)
('Caracas',)
('Charleroi',)
('Cork',)
('Cowes',)
('Cunewalde',)
('Cuxhaven',)
('Elgin',)
('Eugene',)
('Frankfurt',)
('Frankfurt a.M.',)
('Genève',)
('Graz',)
('Göteborg',)
('Helsinki',)
('I. de Margarita',)
('Kirkland',)
('Köln',)
('København',)
('Lander',)
('Lappeenranta',)
('Leipzig',)
('Lille',)
('Lisboa',)
('Lisboa',)
('London',)
('London',)
('London',)
('London',)
('London',)
('London',)
('Londona',)
('Luleå',)
('Lyngby',)
('Lyon',)
('Madrid',)
('Madrid',)
('Madrid',)
('Manchester',)
('Mannheim',)
('Marseille',)
('Melbourne',)
('Montceau',)
('Montréal',)
('Montréal',)
('México D.F.',)
('México D.F.',)
('México D.F.',)
('México D.F.',)
('México D.F.',)
('München',)
('Münster',)
('Nantes',)
('Nantes',)
('New Orleans',)
('Osaka',)
('Oulu',)
('Oviedo',)
('Paris',)
('Paris',)
('Paris',)
('Portland',)
('Portland',)
('Ravenna',)
('Reggio Emilia',)
('Reims',)
('Resende',)
('Rio de Janeiro',)
('Rio de Janeiro',)
('Rio de Janeiro',)
('Salerno',)
('Salzburg',)
('San Cristóbal',)
('San Francisco',)
('Sandvika',)
('Seattle',)
('Sevilla',)
('Singapore',)
('Stavern',)
('Ste-Hyacinthe',)
('Stockholm',)
('Strasbourg',)
('Stuttgart',)
('Sydney',)
('São Paulo',)
('São Paulo',)
('São Paulo',)
('São Paulo',)
('São Paulo',)
('Tokyo',)
('Torino',)
('Toulouse',)
('Tsawassen',)
('Vancouver',)
('Versailles',)
('Walla',)
('Walla Walla',)
('Zaandam',)
('Århus',)

In [97]:
query = '''
        SELECT 'Customer' AS Type, ContactName, City, Country
        FROM Customers
        UNION
        SELECT 'Supplier', ContactName, City, Country
        FROM Suppliers;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Customer', 'Alejandra Camino', 'Madrid', 'Spain')
('Customer', 'Alexander Feuer', 'Leipzig', 'Germany')
('Customer', 'Anabela Domingues', 'São Paulo', 'Brazil')
('Customer', 'André Fonseca', 'Campinas', 'Brazil')
('Customer', 'Ann Devon', 'London', 'UK')
('Customer', 'Annette Roulet', 'Toulouse', 'France')
('Customer', 'Aria Cruz', 'São Paulo', 'Brazil')
('Customer', 'Art Braunschweiger', 'Lander', 'USA')
('Customer', 'Bernardo Batista', 'Rio de Janeiro', 'Brazil')
('Customer', 'Carine Schmitt', 'Nantes', 'France')
('Customer', 'Carlos González', 'Barquisimeto', 'Venezuela')
('Customer', 'Carlos Hernández', 'San Cristóbal', 'Venezuela')
('Customer', 'Catherine Dewey', 'Bruxelles', 'Belgium')
('Customer', 'Christina Berglund', 'Luleå', 'Sweden')
('Customer', 'Daniel Tonini', 'Versailles', 'France')
('Customer', 'Diego Roel', 'Madrid', 'Spain')
('Customer', 'Dominique Perrier', 'Paris', 'France')
('Customer', 'Eduardo Saavedra', 'Barcelona', 'Spain')
('Customer', 'Elizabeth Brown', 'London', 'UK')
('Customer', 'Elizabeth Lincoln', 'Tsawassen', 'Canada')
('Customer', 'Felipe Izquierdo', 'I. de Margarita', 'Venezuela')
('Customer', 'Fran Wilson', 'Portland', 'USA')
('Customer', 'Frédérique Citeaux', 'Strasbourg', 'France')
('Customer', 'Georg Pipps', 'Salzburg', 'Austria')
('Customer', 'Giovanni Rovelli', 'Bergamo', 'Italy')
('Customer', 'Hanna Moos', 'Mannheim', 'Germany')
('Customer', 'Hari Kumar', 'London', 'UK')
('Customer', 'Helen Bennett', 'Cowes', 'UK')
('Customer', 'Helvetius Nagy', 'Kirkland', 'USA')
('Customer', 'Henriette Pfalzheim', 'Köln', 'Germany')
('Customer', 'Horst Kloss', 'Cunewalde', 'Germany')
('Customer', 'Howard Snyder', 'Eugene', 'USA')
('Customer', 'Isabel de Castro', 'Lisboa', 'Portugal')
('Customer', 'Jaime Yorres', 'San Francisco', 'USA')
('Customer', 'Janete Limeira', 'Rio de Janeiro', 'Brazil')
('Customer', 'Janine Labrune', 'Nantes', 'France')
('Customer', 'Jean Fresnière', 'Montréal', 'Canada')
('Customer', 'John Steel', 'Walla Walla', 'USA')
('Customer', 'Jonas Bergulfsen', 'Stavern', 'Norway')
('Customer', 'Jose Pavarotti', 'Boise', 'USA')
('Customer', 'José Pedro Freyre', 'Sevilla', 'Spain')
('Customer', 'Juan', 'México D.F.', 'Mexico')
('Customer', 'Jytte Petersen', 'København', 'Denmark')
('Customer', 'Karin Josephs', 'Münster', 'Germany')
('Customer', 'Karl Jablonski', 'Seattle', 'USA')
('Customer', 'Laurence Lebihans', 'Marseille', 'France')
('Customer', 'Lino Rodriguez', 'Lisboa', 'Portugal')
('Customer', 'Liu Wong', 'Butte', 'USA')
('Customer', 'Liz Nixon', 'Portland', 'USA')
('Customer', 'Lúcia Carvalho', 'São Paulo', 'Brazil')
('Customer', 'Manuel Pereira', 'Caracas', 'Venezuela')
('Customer', 'Maria Larsson', 'Bräcke', 'Sweden')
('Customer', 'Marie Bertrand', 'Paris', 'France')
('Customer', 'Mario Pontes', 'Rio de Janeiro', 'Brazil')
('Customer', 'Martine Rancé', 'Lille', 'France')
('Customer', 'Martín Sommer', 'Madrid', 'Spain')
('Customer', 'Mary Saveley', 'Lyon', 'France')
('Customer', 'Matti Karttunen', 'Helsinki', 'Finland')
('Customer', 'Maurizio Moroni', 'Reggio Emilia', 'Italy')
('Customer', 'Michael Holz', 'Genève', 'Switzerland')
('Customer', 'Palle Ibsen', 'Århus', 'Denmark')
('Customer', 'Paolo Accorti', 'Torino', 'Italy')
('Customer', 'Pascale Cartrain', 'Charleroi', 'Belgium')
('Customer', 'Patricia McKenna', 'Cork', 'Ireland')
('Customer', 'Patricio Simpson', 'Buenos Aires', 'Argentina')
('Customer', 'Paul Henriot', 'Reims', 'France')
('Customer', 'Paula Parente', 'Resende', 'Brazil')
('Customer', 'Paula Wilson', 'Albuquerque', 'USA')
('Customer', 'Pedro Afonso', 'São Paulo', 'Brazil')
('Customer', 'Peter Franken', 'München', 'Germany')
('Customer', 'Philip Cramer', 'Brandenburg', 'Germany')
('Customer', 'Pirkko Koskitalo', 'Oulu', 'Finland')
('Customer', 'Renate Messner', 'Frankfurt a.M.', 'Germany')
('Customer', 'Rene Phillips', 'Anchorage', 'USA')
('Customer', 'Rita Müller', 'Stuttgart', 'Germany')
('Customer', 'Roland Mendel', 'Graz', 'Austria')
('Customer', 'Sergio Gutiérrez', 'Buenos Aires', 'Argentina')
('Customer', 'Simon Crowther', 'London', 'UK')
('Customer', 'Sven Ottlieb', 'Aachen', 'Germany')
('Customer', 'Thomas Hardy', 'London', 'UK')
('Customer', 'Victoria Ashworth', 'London', 'UK')
('Customer', 'Yang Wang', 'Bern', 'Switzerland')
('Customer', 'Yoshi Latimer', 'Elgin', 'USA')
('Customer', 'Yoshi Tannamuri', 'Vancouver', 'Canada')
('Customer', 'Yvonne Moncada', 'Buenos Aires', 'Argentina')
('Customer', 'Zbyszek', 'Walla', 'Poland')
('Supplier', 'Anne Heikkonen', 'Lappeenranta', 'Finland')
('Supplier', 'Antonio del Valle Saavedra', 'Oviedo', 'Spain')
('Supplier', 'Beate Vileid', 'Sandvika', 'Norway')
('Supplier', 'Carlos Diaz', 'São Paulo', 'Brazil')
('Supplier', 'Chandra Leka', 'Singapore', 'Singapore')
('Supplier', 'Chantal Goulet', 'Ste-Hyacinthe', 'Canada')
('Supplier', 'Charlotte Cooper', 'Londona', 'UK')
('Supplier', 'Cheryl Saylor', 'Bend', 'USA')
('Supplier', 'Dirk Luchte', 'Zaandam', 'Netherlands')
('Supplier', 'Eliane Noz', 'Annecy', 'France')
('Supplier', 'Elio Rossi', 'Ravenna', 'Italy')
('Supplier', 'Giovanni Giudici', 'Salerno', 'Italy')
('Supplier', 'Guylène Nodier', 'Paris', 'France')
('Supplier', 'Ian Devling', 'Melbourne', 'Australia')
('Supplier', 'Jean-Guy Lauzon', 'Montréal', 'Canada')
('Supplier', 'Lars Peterson', 'Göteborg', 'Sweden')
('Supplier', 'Marie Delamare', 'Montceau', 'France')
('Supplier', 'Martin Bein', 'Frankfurt', 'Germany')
('Supplier', 'Mayumi Ohno', 'Osaka', 'Japan')
('Supplier', 'Michael Björn', 'Stockholm', 'Sweden')
('Supplier', 'Niels Petersen', 'Lyngby', 'Denmark')
('Supplier', 'Peter Wilson', 'Manchester', 'UK')
('Supplier', 'Petra Winkler', 'Berlin', 'Germany')
('Supplier', 'Regina Murphy', 'Ann Arbor', 'USA')
('Supplier', 'Robb Merchant', 'Boston', 'USA')
('Supplier', 'Shelley Burke', 'New Orleans', 'USA')
('Supplier', 'Sven Petersen', 'Cuxhaven', 'Germany')
('Supplier', 'Wendy Mackenzie', 'Sydney', 'Australia')
('Supplier', 'Yoshi Nagase', 'Tokyo', 'Japan')

### SQL GROUP BY

In [98]:
query = '''
        SELECT COUNT(CustomerID), Country
        FROM Customers
        GROUP BY Country
        ORDER BY COUNT(CustomerID) DESC;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(13, 'USA')
(11, 'France')
(10, 'Germany')
(9, 'Brazil')
(7, 'UK')
(5, 'Spain')
(5, 'Mexico')
(4, 'Venezuela')
(3, 'Italy')
(3, 'Canada')
(3, 'Argentina')
(2, 'Switzerland')
(2, 'Sweden')
(2, 'Portugal')
(2, 'Finland')
(2, 'Denmark')
(2, 'Belgium')
(2, 'Austria')
(1, 'Poland')
(1, 'Norway')
(1, 'Ireland')

In [99]:
query = '''
        SELECT Shippers.ShipperName, COUNT(Orders.OrderID) AS NumberOfOrders FROM Orders
        LEFT JOIN Shippers ON Orders.ShipperID = Shippers.ShipperID
        GROUP BY ShipperName;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Federal Shipping', 68)
('Speedy Express', 54)
('United Package', 74)

### SQL HAVING

In [100]:
query = '''
        SELECT COUNT(CustomerID), Country
        FROM Customers
        GROUP BY Country
        HAVING COUNT(CustomerID) > 5
        ORDER BY COUNT(CustomerID) DESC;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(13, 'USA')
(11, 'France')
(10, 'Germany')
(9, 'Brazil')
(7, 'UK')

In [101]:
query = '''
        SELECT Employees.LastName, COUNT(Orders.OrderID) AS NumberOfOrders
        FROM Orders
        INNER JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID
        WHERE LastName = 'Davolio' OR LastName = 'Fuller'
        GROUP BY LastName
        HAVING COUNT(Orders.OrderID) > 25;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Davolio', 29)

### SQL EXISTS

In [102]:
query = '''
        SELECT SupplierName
        FROM Suppliers
        WHERE EXISTS (SELECT ProductName FROM Products WHERE Products.SupplierID = Suppliers.supplierID AND Price = 22);
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('New Orleans Cajun Delights',)

### SQL INSERT INTO SELECT

In [106]:
query = '''
        INSERT INTO Customers (CustomerName, City, Country)
        SELECT SupplierName, City, Country FROM Suppliers
        WHERE Country='Germany';
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

### SQL CASE

In [108]:
query = '''
        SELECT OrderID, Quantity,
        CASE
            WHEN Quantity > 30 THEN 'The quantity is greater than 30'
            WHEN Quantity = 30 THEN 'The quantity is 30'
            ELSE 'The quantity is under 30'
        END AS QuantityText
        FROM OrderDetails;
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

(10248, 12, 'The quantity is under 30')
(10248, 10, 'The quantity is under 30')
(10248, 5, 'The quantity is under 30')
(10249, 9, 'The quantity is under 30')
(10249, 40, 'The quantity is greater than 30')
(10250, 10, 'The quantity is under 30')
(10250, 35, 'The quantity is greater than 30')
(10250, 15, 'The quantity is under 30')
(10251, 6, 'The quantity is under 30')
(10251, 15, 'The quantity is under 30')
(10251, 20, 'The quantity is under 30')
(10252, 40, 'The quantity is greater than 30')
(10252, 25, 'The quantity is under 30')
(10252, 40, 'The quantity is greater than 30')
(10253, 20, 'The quantity is under 30')
(10253, 42, 'The quantity is greater than 30')
(10253, 40, 'The quantity is greater than 30')
(10254, 15, 'The quantity is under 30')
(10254, 21, 'The quantity is under 30')
(10254, 21, 'The quantity is under 30')
(10255, 20, 'The quantity is under 30')
(10255, 35, 'The quantity is greater than 30')
(10255, 25, 'The quantity is under 30')
(10255, 30, 'The quantity is 30')
(10256, 15, 'The quantity is under 30')
(10256, 12, 'The quantity is under 30')
(10257, 25, 'The quantity is under 30')
(10257, 6, 'The quantity is under 30')
(10257, 15, 'The quantity is under 30')
(10258, 50, 'The quantity is greater than 30')
(10258, 65, 'The quantity is greater than 30')
(10258, 6, 'The quantity is under 30')
(10259, 10, 'The quantity is under 30')
(10259, 1, 'The quantity is under 30')
(10260, 16, 'The quantity is under 30')
(10260, 50, 'The quantity is greater than 30')
(10260, 15, 'The quantity is under 30')
(10260, 21, 'The quantity is under 30')
(10261, 20, 'The quantity is under 30')
(10261, 20, 'The quantity is under 30')
(10262, 12, 'The quantity is under 30')
(10262, 15, 'The quantity is under 30')
(10262, 2, 'The quantity is under 30')
(10263, 60, 'The quantity is greater than 30')
(10263, 28, 'The quantity is under 30')
(10263, 60, 'The quantity is greater than 30')
(10263, 36, 'The quantity is greater than 30')
(10264, 35, 'The quantity is greater than 30')
(10264, 25, 'The quantity is under 30')
(10265, 30, 'The quantity is 30')
(10265, 20, 'The quantity is under 30')
(10266, 12, 'The quantity is under 30')
(10267, 50, 'The quantity is greater than 30')
(10267, 70, 'The quantity is greater than 30')
(10267, 15, 'The quantity is under 30')
(10268, 10, 'The quantity is under 30')
(10268, 4, 'The quantity is under 30')
(10269, 60, 'The quantity is greater than 30')
(10269, 20, 'The quantity is under 30')
(10270, 30, 'The quantity is 30')
(10270, 25, 'The quantity is under 30')
(10271, 24, 'The quantity is under 30')
(10272, 6, 'The quantity is under 30')
(10272, 40, 'The quantity is greater than 30')
(10272, 24, 'The quantity is under 30')
(10273, 24, 'The quantity is under 30')
(10273, 15, 'The quantity is under 30')
(10273, 20, 'The quantity is under 30')
(10273, 60, 'The quantity is greater than 30')
(10273, 33, 'The quantity is greater than 30')
(10274, 20, 'The quantity is under 30')
(10274, 7, 'The quantity is under 30')
(10275, 12, 'The quantity is under 30')
(10275, 6, 'The quantity is under 30')
(10276, 15, 'The quantity is under 30')
(10276, 10, 'The quantity is under 30')
(10277, 20, 'The quantity is under 30')
(10277, 12, 'The quantity is under 30')
(10278, 16, 'The quantity is under 30')
(10278, 15, 'The quantity is under 30')
(10278, 8, 'The quantity is under 30')
(10278, 25, 'The quantity is under 30')
(10279, 15, 'The quantity is under 30')
(10280, 12, 'The quantity is under 30')
(10280, 20, 'The quantity is under 30')
(10280, 30, 'The quantity is 30')
(10281, 1, 'The quantity is under 30')
(10281, 6, 'The quantity is under 30')
(10281, 4, 'The quantity is under 30')
(10282, 6, 'The quantity is under 30')
(10282, 2, 'The quantity is under 30')
(10283, 20, 'The quantity is under 30')
(10283, 18, 'The quantity is under 30')
(10283, 35, 'The quantity is greater than 30')
(10283, 3, 'The quantity is under 30')
(10284, 15, 'The quantity is under 30')
(10284, 21, 'The quantity is under 30')
(10284, 20, 'The quantity is under 30')
(10284, 5, 'The quantity is under 30')
(10285, 45, 'The quantity is greater than 30')
(10285, 40, 'The quantity is greater than 30')
(10285, 36, 'The quantity is greater than 30')
(10286, 100, 'The quantity is greater than 30')
(10286, 40, 'The quantity is greater than 30')
(10287, 40, 'The quantity is greater than 30')
(10287, 20, 'The quantity is under 30')
(10287, 15, 'The quantity is under 30')
(10288, 10, 'The quantity is under 30')
(10288, 3, 'The quantity is under 30')
(10289, 30, 'The quantity is 30')
(10289, 9, 'The quantity is under 30')
(10290, 20, 'The quantity is under 30')
(10290, 15, 'The quantity is under 30')
(10290, 15, 'The quantity is under 30')
(10290, 10, 'The quantity is under 30')
(10291, 20, 'The quantity is under 30')
(10291, 24, 'The quantity is under 30')
(10291, 2, 'The quantity is under 30')
(10292, 20, 'The quantity is under 30')
(10293, 12, 'The quantity is under 30')
(10293, 10, 'The quantity is under 30')
(10293, 5, 'The quantity is under 30')
(10293, 6, 'The quantity is under 30')
(10294, 18, 'The quantity is under 30')
(10294, 15, 'The quantity is under 30')
(10294, 15, 'The quantity is under 30')
(10294, 21, 'The quantity is under 30')
(10294, 6, 'The quantity is under 30')
(10295, 4, 'The quantity is under 30')
(10296, 12, 'The quantity is under 30')
(10296, 30, 'The quantity is 30')
(10296, 15, 'The quantity is under 30')
(10297, 60, 'The quantity is greater than 30')
(10297, 20, 'The quantity is under 30')
(10298, 40, 'The quantity is greater than 30')
(10298, 40, 'The quantity is greater than 30')
(10298, 30, 'The quantity is 30')
(10298, 15, 'The quantity is under 30')
(10299, 15, 'The quantity is under 30')
(10299, 20, 'The quantity is under 30')
(10300, 30, 'The quantity is 30')
(10300, 20, 'The quantity is under 30')
(10301, 10, 'The quantity is under 30')
(10301, 20, 'The quantity is under 30')
(10302, 40, 'The quantity is greater than 30')
(10302, 28, 'The quantity is under 30')
(10302, 12, 'The quantity is under 30')
(10303, 40, 'The quantity is greater than 30')
(10303, 30, 'The quantity is 30')
(10303, 15, 'The quantity is under 30')
(10304, 30, 'The quantity is 30')
(10304, 10, 'The quantity is under 30')
(10304, 2, 'The quantity is under 30')
(10305, 25, 'The quantity is under 30')
(10305, 25, 'The quantity is under 30')
(10305, 30, 'The quantity is 30')
(10306, 10, 'The quantity is under 30')
(10306, 10, 'The quantity is under 30')
(10306, 5, 'The quantity is under 30')
(10307, 10, 'The quantity is under 30')
(10307, 3, 'The quantity is under 30')
(10308, 1, 'The quantity is under 30')
(10308, 5, 'The quantity is under 30')
(10309, 20, 'The quantity is under 30')
(10309, 30, 'The quantity is 30')
(10309, 2, 'The quantity is under 30')
(10309, 20, 'The quantity is under 30')
(10309, 3, 'The quantity is under 30')
(10310, 10, 'The quantity is under 30')
(10310, 5, 'The quantity is under 30')
(10311, 6, 'The quantity is under 30')
(10311, 7, 'The quantity is under 30')
(10312, 4, 'The quantity is under 30')
(10312, 24, 'The quantity is under 30')
(10312, 20, 'The quantity is under 30')
(10312, 10, 'The quantity is under 30')
(10313, 12, 'The quantity is under 30')
(10314, 40, 'The quantity is greater than 30')
(10314, 30, 'The quantity is 30')
(10314, 25, 'The quantity is under 30')
(10315, 14, 'The quantity is under 30')
(10315, 30, 'The quantity is 30')
(10316, 10, 'The quantity is under 30')
(10316, 70, 'The quantity is greater than 30')
(10317, 20, 'The quantity is under 30')
(10318, 20, 'The quantity is under 30')
(10318, 6, 'The quantity is under 30')
(10319, 8, 'The quantity is under 30')
(10319, 14, 'The quantity is under 30')
(10319, 30, 'The quantity is 30')
(10320, 30, 'The quantity is 30')
(10321, 10, 'The quantity is under 30')
(10322, 20, 'The quantity is under 30')
(10323, 5, 'The quantity is under 30')
(10323, 4, 'The quantity is under 30')
(10323, 4, 'The quantity is under 30')
(10324, 21, 'The quantity is under 30')
(10324, 70, 'The quantity is greater than 30')
(10324, 30, 'The quantity is 30')
(10324, 40, 'The quantity is greater than 30')
(10324, 80, 'The quantity is greater than 30')
(10325, 6, 'The quantity is under 30')
(10325, 12, 'The quantity is under 30')
(10325, 9, 'The quantity is under 30')
(10325, 4, 'The quantity is under 30')
(10325, 40, 'The quantity is greater than 30')
(10326, 24, 'The quantity is under 30')
(10326, 16, 'The quantity is under 30')
(10326, 50, 'The quantity is greater than 30')
(10327, 25, 'The quantity is under 30')
(10327, 50, 'The quantity is greater than 30')
(10327, 35, 'The quantity is greater than 30')
(10327, 30, 'The quantity is 30')
(10328, 9, 'The quantity is under 30')
(10328, 40, 'The quantity is greater than 30')
(10328, 10, 'The quantity is under 30')
(10329, 10, 'The quantity is under 30')
(10329, 8, 'The quantity is under 30')
(10329, 20, 'The quantity is under 30')
(10329, 12, 'The quantity is under 30')
(10330, 50, 'The quantity is greater than 30')
(10330, 25, 'The quantity is under 30')
(10331, 15, 'The quantity is under 30')
(10332, 40, 'The quantity is greater than 30')
(10332, 10, 'The quantity is under 30')
(10332, 16, 'The quantity is under 30')
(10333, 10, 'The quantity is under 30')
(10333, 10, 'The quantity is under 30')
(10333, 40, 'The quantity is greater than 30')
(10334, 8, 'The quantity is under 30')
(10334, 10, 'The quantity is under 30')
(10335, 7, 'The quantity is under 30')
(10335, 25, 'The quantity is under 30')
(10335, 6, 'The quantity is under 30')
(10335, 48, 'The quantity is greater than 30')
(10336, 18, 'The quantity is under 30')
(10337, 40, 'The quantity is greater than 30')
(10337, 24, 'The quantity is under 30')
(10337, 20, 'The quantity is under 30')
(10337, 28, 'The quantity is under 30')
(10337, 25, 'The quantity is under 30')
(10338, 20, 'The quantity is under 30')
(10338, 15, 'The quantity is under 30')
(10339, 10, 'The quantity is under 30')
(10339, 70, 'The quantity is greater than 30')
(10339, 28, 'The quantity is under 30')
(10340, 20, 'The quantity is under 30')
(10340, 12, 'The quantity is under 30')
(10340, 40, 'The quantity is greater than 30')
(10341, 8, 'The quantity is under 30')
(10341, 9, 'The quantity is under 30')
(10342, 24, 'The quantity is under 30')
(10342, 56, 'The quantity is greater than 30')
(10342, 40, 'The quantity is greater than 30')
(10342, 40, 'The quantity is greater than 30')
(10343, 50, 'The quantity is greater than 30')
(10343, 4, 'The quantity is under 30')
(10343, 15, 'The quantity is under 30')
(10344, 35, 'The quantity is greater than 30')
(10344, 70, 'The quantity is greater than 30')
(10345, 70, 'The quantity is greater than 30')
(10345, 80, 'The quantity is greater than 30')
(10345, 9, 'The quantity is under 30')
(10346, 36, 'The quantity is greater than 30')
(10346, 20, 'The quantity is under 30')
(10347, 10, 'The quantity is under 30')
(10347, 50, 'The quantity is greater than 30')
(10347, 4, 'The quantity is under 30')
(10347, 6, 'The quantity is under 30')
(10348, 15, 'The quantity is under 30')
(10348, 25, 'The quantity is under 30')
(10349, 24, 'The quantity is under 30')
(10350, 15, 'The quantity is under 30')
(10350, 18, 'The quantity is under 30')
(10351, 20, 'The quantity is under 30')
(10351, 13, 'The quantity is under 30')
(10351, 77, 'The quantity is greater than 30')
(10351, 10, 'The quantity is under 30')
(10352, 10, 'The quantity is under 30')
(10352, 20, 'The quantity is under 30')
(10353, 12, 'The quantity is under 30')
(10353, 50, 'The quantity is greater than 30')
(10354, 12, 'The quantity is under 30')
(10354, 4, 'The quantity is under 30')
(10355, 25, 'The quantity is under 30')
(10355, 25, 'The quantity is under 30')
(10356, 30, 'The quantity is 30')
(10356, 12, 'The quantity is under 30')
(10356, 20, 'The quantity is under 30')
(10357, 30, 'The quantity is 30')
(10357, 16, 'The quantity is under 30')
(10357, 8, 'The quantity is under 30')
(10358, 10, 'The quantity is under 30')
(10358, 10, 'The quantity is under 30')
(10358, 20, 'The quantity is under 30')
(10359, 56, 'The quantity is greater than 30')
(10359, 70, 'The quantity is greater than 30')
(10359, 80, 'The quantity is greater than 30')
(10360, 30, 'The quantity is 30')
(10360, 35, 'The quantity is greater than 30')
(10360, 10, 'The quantity is under 30')
(10360, 35, 'The quantity is greater than 30')
(10360, 28, 'The quantity is under 30')
(10361, 54, 'The quantity is greater than 30')
(10361, 55, 'The quantity is greater than 30')
(10362, 50, 'The quantity is greater than 30')
(10362, 20, 'The quantity is under 30')
(10362, 24, 'The quantity is under 30')
(10363, 20, 'The quantity is under 30')
(10363, 12, 'The quantity is under 30')
(10363, 12, 'The quantity is under 30')
(10364, 30, 'The quantity is 30')
(10364, 5, 'The quantity is under 30')
(10365, 24, 'The quantity is under 30')
(10366, 5, 'The quantity is under 30')
(10366, 5, 'The quantity is under 30')
(10367, 36, 'The quantity is greater than 30')
(10367, 18, 'The quantity is under 30')
(10367, 15, 'The quantity is under 30')
(10367, 7, 'The quantity is under 30')
(10368, 5, 'The quantity is under 30')
(10368, 13, 'The quantity is under 30')
(10368, 25, 'The quantity is under 30')
(10368, 35, 'The quantity is greater than 30')
(10369, 20, 'The quantity is under 30')
(10369, 18, 'The quantity is under 30')
(10370, 15, 'The quantity is under 30')
(10370, 30, 'The quantity is 30')
(10370, 20, 'The quantity is under 30')
(10371, 6, 'The quantity is under 30')
(10372, 12, 'The quantity is under 30')
(10372, 40, 'The quantity is greater than 30')
(10372, 70, 'The quantity is greater than 30')
(10372, 42, 'The quantity is greater than 30')
(10373, 80, 'The quantity is greater than 30')
(10373, 50, 'The quantity is greater than 30')
(10374, 30, 'The quantity is 30')
(10374, 15, 'The quantity is under 30')
(10375, 15, 'The quantity is under 30')
(10375, 10, 'The quantity is under 30')
(10376, 42, 'The quantity is greater than 30')
(10377, 20, 'The quantity is under 30')
(10377, 20, 'The quantity is under 30')
(10378, 6, 'The quantity is under 30')
(10379, 8, 'The quantity is under 30')
(10379, 16, 'The quantity is under 30')
(10379, 20, 'The quantity is under 30')
(10380, 18, 'The quantity is under 30')
(10380, 20, 'The quantity is under 30')
(10380, 6, 'The quantity is under 30')
(10380, 30, 'The quantity is 30')
(10381, 14, 'The quantity is under 30')
(10382, 32, 'The quantity is greater than 30')
(10382, 9, 'The quantity is under 30')
(10382, 14, 'The quantity is under 30')
(10382, 60, 'The quantity is greater than 30')
(10382, 50, 'The quantity is greater than 30')
(10383, 20, 'The quantity is under 30')
(10383, 15, 'The quantity is under 30')
(10383, 20, 'The quantity is under 30')
(10384, 28, 'The quantity is under 30')
(10384, 15, 'The quantity is under 30')
(10385, 10, 'The quantity is under 30')
(10385, 20, 'The quantity is under 30')
(10385, 8, 'The quantity is under 30')
(10386, 15, 'The quantity is under 30')
(10386, 10, 'The quantity is under 30')
(10387, 15, 'The quantity is under 30')
(10387, 6, 'The quantity is under 30')
(10387, 12, 'The quantity is under 30')
(10387, 15, 'The quantity is under 30')
(10388, 15, 'The quantity is under 30')
(10388, 20, 'The quantity is under 30')
(10388, 40, 'The quantity is greater than 30')
(10389, 16, 'The quantity is under 30')
(10389, 15, 'The quantity is under 30')
(10389, 20, 'The quantity is under 30')
(10389, 30, 'The quantity is 30')
(10390, 60, 'The quantity is greater than 30')
(10390, 40, 'The quantity is greater than 30')
(10390, 45, 'The quantity is greater than 30')
(10390, 24, 'The quantity is under 30')
(10391, 18, 'The quantity is under 30')
(10392, 50, 'The quantity is greater than 30')
(10393, 25, 'The quantity is under 30')
(10393, 42, 'The quantity is greater than 30')
(10393, 7, 'The quantity is under 30')
(10393, 70, 'The quantity is greater than 30')
(10393, 32, 'The quantity is greater than 30')
(10394, 10, 'The quantity is under 30')
(10394, 10, 'The quantity is under 30')
(10395, 28, 'The quantity is under 30')
(10395, 70, 'The quantity is greater than 30')
(10395, 8, 'The quantity is under 30')
(10396, 40, 'The quantity is greater than 30')
(10396, 60, 'The quantity is greater than 30')
(10396, 21, 'The quantity is under 30')
(10397, 10, 'The quantity is under 30')
(10397, 18, 'The quantity is under 30')
(10398, 30, 'The quantity is 30')
(10398, 120, 'The quantity is greater than 30')
(10399, 60, 'The quantity is greater than 30')
(10399, 30, 'The quantity is 30')
(10399, 35, 'The quantity is greater than 30')
(10399, 14, 'The quantity is under 30')
(10400, 21, 'The quantity is under 30')
(10400, 35, 'The quantity is greater than 30')
(10400, 30, 'The quantity is 30')
(10401, 18, 'The quantity is under 30')
(10401, 70, 'The quantity is greater than 30')
(10401, 20, 'The quantity is under 30')
(10401, 60, 'The quantity is greater than 30')
(10402, 60, 'The quantity is greater than 30')
(10402, 65, 'The quantity is greater than 30')
(10403, 21, 'The quantity is under 30')
(10403, 70, 'The quantity is greater than 30')
(10404, 30, 'The quantity is 30')
(10404, 40, 'The quantity is greater than 30')
(10404, 30, 'The quantity is 30')
(10405, 50, 'The quantity is greater than 30')
(10406, 10, 'The quantity is under 30')
(10406, 30, 'The quantity is 30')
(10406, 42, 'The quantity is greater than 30')
(10406, 5, 'The quantity is under 30')
(10406, 2, 'The quantity is under 30')
(10407, 30, 'The quantity is 30')
(10407, 15, 'The quantity is under 30')
(10407, 15, 'The quantity is under 30')
(10408, 10, 'The quantity is under 30')
(10408, 6, 'The quantity is under 30')
(10408, 35, 'The quantity is greater than 30')
(10409, 12, 'The quantity is under 30')
(10409, 12, 'The quantity is under 30')
(10410, 49, 'The quantity is greater than 30')
(10410, 16, 'The quantity is under 30')
(10411, 25, 'The quantity is under 30')
(10411, 40, 'The quantity is greater than 30')
(10411, 9, 'The quantity is under 30')
(10412, 20, 'The quantity is under 30')
(10413, 24, 'The quantity is under 30')
(10413, 40, 'The quantity is greater than 30')
(10413, 14, 'The quantity is under 30')
(10414, 18, 'The quantity is under 30')
(10414, 50, 'The quantity is greater than 30')
(10415, 2, 'The quantity is under 30')
(10415, 20, 'The quantity is under 30')
(10416, 20, 'The quantity is under 30')
(10416, 10, 'The quantity is under 30')
(10416, 20, 'The quantity is under 30')
(10417, 50, 'The quantity is greater than 30')
(10417, 2, 'The quantity is under 30')
(10417, 36, 'The quantity is greater than 30')
(10417, 35, 'The quantity is greater than 30')
(10418, 60, 'The quantity is greater than 30')
(10418, 55, 'The quantity is greater than 30')
(10418, 16, 'The quantity is under 30')
(10418, 15, 'The quantity is under 30')
(10419, 60, 'The quantity is greater than 30')
(10419, 20, 'The quantity is under 30')
(10420, 20, 'The quantity is under 30')
(10420, 2, 'The quantity is under 30')
(10420, 8, 'The quantity is under 30')
(10420, 20, 'The quantity is under 30')
(10421, 4, 'The quantity is under 30')
(10421, 30, 'The quantity is 30')
(10421, 15, 'The quantity is under 30')
(10421, 10, 'The quantity is under 30')
(10422, 2, 'The quantity is under 30')
(10423, 14, 'The quantity is under 30')
(10423, 20, 'The quantity is under 30')
(10424, 60, 'The quantity is greater than 30')
(10424, 49, 'The quantity is greater than 30')
(10424, 30, 'The quantity is 30')
(10425, 10, 'The quantity is under 30')
(10425, 20, 'The quantity is under 30')
(10426, 5, 'The quantity is under 30')
(10426, 7, 'The quantity is under 30')
(10427, 35, 'The quantity is greater than 30')
(10428, 20, 'The quantity is under 30')
(10429, 40, 'The quantity is greater than 30')
(10429, 35, 'The quantity is greater than 30')
(10430, 45, 'The quantity is greater than 30')
(10430, 50, 'The quantity is greater than 30')
(10430, 30, 'The quantity is 30')
(10430, 70, 'The quantity is greater than 30')

In [109]:
query = '''
        SELECT CustomerName, City, Country
        FROM Customers
        ORDER BY
        (CASE
            WHEN City IS NULL THEN Country
            ELSE City
        END);
        '''
cursor.execute(query)
for row in cursor.fetchall():
    print(row)

('Drachenblut Delikatessend', 'Aachen', 'Germany')
('Rattlesnake Canyon Grocery', 'Albuquerque', 'USA')
('Old World Delicatessen', 'Anchorage', 'USA')
('Galería del gastrónomo', 'Barcelona', 'Spain')
('LILA-Supermercado', 'Barquisimeto', 'Venezuela')
('Magazzini Alimentari Riuniti', 'Bergamo', 'Italy')
('Heli Süßwaren GmbH & Co. KG', 'Berlin', 'Germany')
('Chop-suey Chinese', 'Bern', 'Switzerland')
('Save-a-lot Markets', 'Boise', 'USA')
('Königlich Essen', 'Brandenburg', 'Germany')
('Maison Dewey', 'Bruxelles', 'Belgium')
('Folk och fä HB', 'Bräcke', 'Sweden')
('Cactus Comidas para llevar', 'Buenos Aires', 'Argentina')
('Océano Atlántico Ltda.', 'Buenos Aires', 'Argentina')
('Rancho grande', 'Buenos Aires', 'Argentina')
('The Cracker Box', 'Butte', 'USA')
('Gourmet Lanchonetes', 'Campinas', 'Brazil')
('GROSELLA-Restaurante', 'Caracas', 'Venezuela')
('Suprêmes délices', 'Charleroi', 'Belgium')
('Hungry Owl All-Night Grocers', 'Cork', 'Ireland')
('Island Trading', 'Cowes', 'UK')
('QUICK-Stop', 'Cunewalde', 'Germany')
('Nord-Ost-Fisch Handelsgesellschaft mbH', 'Cuxhaven', 'Germany')
('Hungry Coyote Import Store', 'Elgin', 'USA')
('Great Lakes Food Market', 'Eugene', 'USA')
('Plutzer Lebensmittelgroßmärkte AG', 'Frankfurt', 'Germany')
('Lehmanns Marktstand', 'Frankfurt a.M.', 'Germany')
('Richter Supermarkt', 'Genève', 'Switzerland')
('Ernst Handel', 'Graz', 'Austria')
('Wilman Kala', 'Helsinki', 'Finland')
('LINO-Delicateses', 'I. de Margarita', 'Venezuela')
("Trail''s Head Gourmet Provisioners", 'Kirkland', 'USA')
('Ottilies Käseladen', 'Köln', 'Germany')
('Simons bistro', 'København', 'Denmark')
('Split Rail Beer & Ale', 'Lander', 'USA')
('Morgenstern Gesundkost', 'Leipzig', 'Germany')
('Folies gourmandes', 'Lille', 'France')
('Furia Bacalhau e Frutos do Mar', 'Lisboa', 'Portugal')
('Princesa Isabel Vinhoss', 'Lisboa', 'Portugal')
('Around the Horn', 'London', 'UK')
("B''s Beverages", 'London', 'UK')
('Consolidated Holdings', 'London', 'UK')
('Eastern Connection', 'London', 'UK')
('North/South', 'London', 'UK')
('Seven Seas Imports', 'London', 'UK')
('Berglunds snabbköp', 'Luleå', 'Sweden')
('Victuailles en stock', 'Lyon', 'France')
('Bólido Comidas preparadas', 'Madrid', 'Spain')
('FISSA Fabrica Inter. Salchichas S.A.', 'Madrid', 'Spain')
('Romero y tomillo', 'Madrid', 'Spain')
('Blauer See Delikatessen', 'Mannheim', 'Germany')
("Bon app''", 'Marseille', 'France')
('Mère Paillarde', 'Montréal', 'Canada')
('Ana Trujillo Emparedados y helados', 'México D.F.', 'Mexico')
('Antonio Moreno Taquería', 'México D.F.', 'Mexico')
('Centro comercial Moctezuma', 'México D.F.', 'Mexico')
('Pericles Comidas clásicas', 'México D.F.', 'Mexico')
('Tortuga Restaurante', 'México D.F.', 'Mexico')
('Frankenversand', 'München', 'Germany')
('Toms Spezialitäten', 'Münster', 'Germany')
('Du monde entier', 'Nantes', 'France')
('France restauration', 'Nantes', 'France')
('Wartian Herkku', 'Oulu', 'Finland')
('Paris spécialités', 'Paris', 'France')
('Spécialités du monde', 'Paris', 'France')
('Lonesome Pine Restaurant', 'Portland', 'USA')
('The Big Cheese', 'Portland', 'USA')
('Reggiani Caseifici', 'Reggio Emilia', 'Italy')
('Vins et alcools Chevalier', 'Reims', 'France')
('Wellington Importadora', 'Resende', 'Brazil')
('Hanari Carnes', 'Rio de Janeiro', 'Brazil')
('Que Delícia', 'Rio de Janeiro', 'Brazil')
('Ricardo Adocicados', 'Rio de Janeiro', 'Brazil')
('Piccolo und mehr', 'Salzburg', 'Austria')
('HILARIÓN-Abastos', 'San Cristóbal', 'Venezuela')
("Let''s Stop N Shop", 'San Francisco', 'USA')
('White Clover Markets', 'Seattle', 'USA')
('Godos Cocina Típica', 'Sevilla', 'Spain')
('Santé Gourmet', 'Stavern', 'Norway')
('Blondel père et fils', 'Strasbourg', 'France')
('Die Wandernde Kuh', 'Stuttgart', 'Germany')
('Comércio Mineiro', 'São Paulo', 'Brazil')
('Familia Arquibaldo', 'São Paulo', 'Brazil')
('Queen Cozinha', 'São Paulo', 'Brazil')
('Tradição Hipermercados', 'São Paulo', 'Brazil')
('Franchi S.p.A.', 'Torino', 'Italy')
("La maison d''Asie", 'Toulouse', 'France')
('Bottom-Dollar Marketse', 'Tsawassen', 'Canada')
('Laughing Bacchus Wine Cellars', 'Vancouver', 'Canada')
("La corne d''abondance", 'Versailles', 'France')
('Wolski', 'Walla', 'Poland')
('Lazy K Kountry Store', 'Walla Walla', 'USA')
('Vaffeljernet', 'Århus', 'Denmark')

### SQL NULL Functions

In [114]:
# 상황에 맞는 테이블이 없어 쿼리문만 입력하는 것으로 대체
query = '''
        SELECT ProductName, UnitPrice * (UnitsInStock + IFNULL(UnitsOnOrder, 0))
        FROM Products;
        '''

In [115]:
query = '''
        SELECT ProductName, UnitPrice * (UnitsInStock + COALESCE(UnitsOnOrder, 0))
        FROM Products;
        '''

### SQL Operators
#### SQL Arithmetic Operators
- '+' : Add
- '-' : Subtract
- '*' : Multiply
- '/' : Divide
- '%' : Modulo
#### SQL Bitwise Operators
- '&' : Bitwise AND
- '|' : Bitwise OR
- '^' : Bitwise exclusive OR
#### SQL Comparsion Operators
- '=' : Equal to
- '>' : Greater than
- '<' : Less than
- '>=' : Greater than or equal to
- '<=' : Less than or equal to
- '<>' : Not equal to
#### SQL Compound Operators
- '+=' : Add equals
- '-=' : Subtract equals
- '*=' : Multiply equals
- '/=' : Divide equals
- '%=' : Modulo equals
- '&=' : Bitwise AND equals
- '^-=' : Bitwise exclusive equals
- '!*=' : Bitwise OR equals
#### SQL Logical Operators
- ALL : TRUE if all of the subquery values meet the condition
- AND : TRUE if all the conditions separated by AND is TRUE	
- ANY : TRUE if any of the subquery values meet the condition	
- BETWEEN : TRUE if the operand is within the range of comparisons	
- EXISTS : TRUE if the subquery returns one or more records	
- IN : TRUE if the operand is equal to one of a list of expressions	
- LIKE : TRUE if the operand matches a pattern	
- NOT : Displays a record if the condition(s) is NOT TRUE	
- OR : TRUE if any of the conditions separated by OR is TRUE	
- SOME : TRUE if any of the subquery values meet the condition