In [1]:
import sqlite3

with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    cursor.execute(
        '''
        SELECT * FROM Customers
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(f'''CustomerID: {row[0]}, 
        CustomerName: {row[1]}, 
        ContactName: {row[2]}, 
        Address: {row[3]}, 
        City: {row[4]}, 
        PostalCode: {row[5]}, 
        Country: {row[6]}
        ''')

CustomerID: 1,
        CustomerName: Alfreds Futterkiste,
        ContactName: Maria Anders,
        Address: Obere Str. 57,
        City: Berlin,
        PostalCode: 12209,
        Country: Germany

CustomerID: 2,
        CustomerName: Ana Trujillo Emparedados y helados,
        ContactName: Ana Trujillo,
        Address: Avda. de la Constitución 2222,
        City: México D.F.,
        PostalCode: 5021,
        Country: Mexico

CustomerID: 3,
        CustomerName: Antonio Moreno Taquería,
        ContactName: Antonio Moreno,
        Address: Mataderos 2312,
        City: México D.F.,
        PostalCode: 5023,
        Country: Mexico

CustomerID: 4,
        CustomerName: Around the Horn,
        ContactName: Thomas Hardy,
        Address: 120 Hanover Sq.,
        City: London,
        PostalCode: WA1 1DP,
        Country: UK

CustomerID: 5,
        CustomerName: Berglunds snabbköp,
        ContactName: Christina Berglund,
        Address: Berguvsvägen 8,
        City: Luleå,
        PostalCode: S-958 22,
        Country: Sweden

CustomerID: 6,
        CustomerName: Blauer See Delikatessen,
        ContactName: Hanna Moos,
        Address: Forsterstr. 57,
        City: Mannheim,
        PostalCode: 68306,
        Country: Germany

CustomerID: 7,
        CustomerName: Blondel père et fils,
        ContactName: Frédérique Citeaux,
        Address: 24, place Kléber,
        City: Strasbourg,
        PostalCode: 67000,
        Country: France

CustomerID: 8,
        CustomerName: Bólido Comidas preparadas,
        ContactName: Martín Sommer,
        Address: C/ Araquil, 67,
        City: Madrid,
        PostalCode: 28023,
        Country: Spain

CustomerID: 9,
        CustomerName: Bon app'',
        ContactName: Laurence Lebihans,
        Address: 12, rue des Bouchers,
        City: Marseille,
        PostalCode: 13008,
        Country: France

CustomerID: 10,
        CustomerName: Bottom-Dollar Marketse,
        ContactName: Elizabeth Lincoln,
        Address: 23 Tsawassen Blvd.,
        City: Tsawassen,
        PostalCode: T2F 8M4,
        Country: Canada

CustomerID: 11,
        CustomerName: B''s Beverages,
        ContactName: Victoria Ashworth,
        Address: Fauntleroy Circus,
        City: London,
        PostalCode: EC2 5NT,
        Country: UK

CustomerID: 12,
        CustomerName: Cactus Comidas para llevar,
        ContactName: Patricio Simpson,
        Address: Cerrito 333,
        City: Buenos Aires,
        PostalCode: 1010,
        Country: Argentina

CustomerID: 13,
        CustomerName: Centro comercial Moctezuma,
        ContactName: Francisco Chang,
        Address: Sierras de Granada 9993,
        City: México D.F.,
        PostalCode: 5022,
        Country: Mexico

CustomerID: 14,
        CustomerName: Chop-suey Chinese,
        ContactName: Yang Wang,
        Address: Hauptstr. 29,
        City: Bern,
        PostalCode: 3012,
        Country: Switzerland

CustomerID: 15,
        CustomerName: Comércio Mineiro,
        ContactName: Pedro Afonso,
        Address: Av. dos Lusíadas, 23,
        City: São Paulo,
        PostalCode: 05432-043,
        Country: Brazil

CustomerID: 16,
        CustomerName: Consolidated Holdings,
        ContactName: Elizabeth Brown,
        Address: Berkeley Gardens 12 Brewery,
        City: London,
        PostalCode: WX1 6LT,
        Country: UK

CustomerID: 17,
        CustomerName: Drachenblut Delikatessend,
        ContactName: Sven Ottlieb,
        Address: Walserweg 21,
        City: Aachen,
        PostalCode: 52066,
        Country: Germany

CustomerID: 18,
        CustomerName: Du monde entier,
        ContactName: Janine Labrune,
        Address: 67, rue des Cinquante Otages,
        City: Nantes,
        PostalCode: 44000,
        Country: France

CustomerID: 19,
        CustomerName: Eastern Connection,
        ContactName: Ann Devon,
        Address: 35 King George,
        City: London,
        PostalCode: WX3 6FW,
        Country: UK

CustomerID: 20,
        CustomerName: Ernst Handel,
        ContactName: Roland Mendel,
        Address: Kirchgasse 6,
        City: Graz,
        PostalCode: 8010,
        Country: Austria

CustomerID: 21,
        CustomerName: Familia Arquibaldo,
        ContactName: Aria Cruz,
        Address: Rua Orós, 92,
        City: São Paulo,
        PostalCode: 05442-030,
        Country: Brazil

CustomerID: 22,
        CustomerName: FISSA Fabrica Inter. Salchichas S.A.,
        ContactName: Diego Roel,
        Address: C/ Moralzarzal, 86,
        City: Madrid,
        PostalCode: 28034,
        Country: Spain

CustomerID: 23,
        CustomerName: Folies gourmandes,
        ContactName: Martine Rancé,
        Address: 184, chaussée de Tournai,
        City: Lille,
        PostalCode: 59000,
        Country: France

CustomerID: 24,
        CustomerName: Folk och fä HB,
        ContactName: Maria Larsson,
        Address: Åkergatan 24,
        City: Bräcke,
        PostalCode: S-844 67,
        Country: Sweden

CustomerID: 25,
        CustomerName: Frankenversand,
        ContactName: Peter Franken,
        Address: Berliner Platz 43,
        City: München,
        PostalCode: 80805,
        Country: Germany

CustomerID: 26,
        CustomerName: France restauration,
        ContactName: Carine Schmitt,
        Address: 54, rue Royale,
        City: Nantes,
        PostalCode: 44000,
        Country: France

CustomerID: 27,
        CustomerName: Franchi S.p.A.,
        ContactName: Paolo Accorti,
        Address: Via Monte Bianco 34,
        City: Torino,
        PostalCode: 10100,
        Country: Italy

CustomerID: 28,
        CustomerName: Furia Bacalhau e Frutos do Mar,
        ContactName: Lino Rodriguez,
        Address: Jardim das rosas n. 32,
        City: Lisboa,
        PostalCode: 1675,
        Country: Portugal

CustomerID: 29,
        CustomerName: Galería del gastrónomo,
        ContactName: Eduardo Saavedra,
        Address: Rambla de Cataluña, 23,
        City: Barcelona,
        PostalCode: 8022,
        Country: Spain

CustomerID: 30,
        CustomerName: Godos Cocina Típica,
        ContactName: José Pedro Freyre,
        Address: C/ Romero, 33,
        City: Sevilla,
        PostalCode: 41101,
        Country: Spain

CustomerID: 31,
        CustomerName: Gourmet Lanchonetes,
        ContactName: André Fonseca,
        Address: Av. Brasil, 442,
        City: Campinas,
        PostalCode: 04876-786,
        Country: Brazil

CustomerID: 32,
        CustomerName: Great Lakes Food Market,
        ContactName: Howard Snyder,
        Address: 2732 Baker Blvd.,
        City: Eugene,
        PostalCode: 97403,
        Country: USA

CustomerID: 33,
        CustomerName: GROSELLA-Restaurante,
        ContactName: Manuel Pereira,
        Address: 5ª Ave. Los Palos Grandes,
        City: Caracas,
        PostalCode: 1081,
        Country: Venezuela

CustomerID: 34,
        CustomerName: Hanari Carnes,
        ContactName: Mario Pontes,
        Address: Rua do Paço, 67,
        City: Rio de Janeiro,
        PostalCode: 05454-876,
        Country: Brazil

CustomerID: 35,
        CustomerName: HILARIÓN-Abastos,
        ContactName: Carlos Hernández,
        Address: Carrera 22 con Ave. Carlos Soublette #8-35,
        City: San Cristóbal,
        PostalCode: 5022,
        Country: Venezuela

CustomerID: 36,
        CustomerName: Hungry Coyote Import Store,
        ContactName: Yoshi Latimer,
        Address: City Center Plaza 516 Main St.,
        City: Elgin,
        PostalCode: 97827,
        Country: USA

CustomerID: 37,
        CustomerName: Hungry Owl All-Night Grocers,
        ContactName: Patricia McKenna,
        Address: 8 Johnstown Road,
        City: Cork,
        PostalCode: ,
        Country: Ireland

CustomerID: 38,
        CustomerName: Island Trading,
        ContactName: Helen Bennett,
        Address: Garden House Crowther Way,
        City: Cowes,
        PostalCode: PO31 7PJ,
        Country: UK

CustomerID: 39,
        CustomerName: Königlich Essen,
        ContactName: Philip Cramer,
        Address: Maubelstr. 90,
        City: Brandenburg,
        PostalCode: 14776,
        Country: Germany

CustomerID: 40,
        CustomerName: La corne d''abondance,
        ContactName: Daniel Tonini,
        Address: 67, avenue de l''Europe,
        City: Versailles,
        PostalCode: 78000,
        Country: France

CustomerID: 41,
        CustomerName: La maison d''Asie,
        ContactName: Annette Roulet,
        Address: 1 rue Alsace-Lorraine,
        City: Toulouse,
        PostalCode: 31000,
        Country: France

CustomerID: 42,
        CustomerName: Laughing Bacchus Wine Cellars,
        ContactName: Yoshi Tannamuri,
        Address: 1900 Oak St.,
        City: Vancouver,
        PostalCode: V3F 2K1,
        Country: Canada

CustomerID: 43,
        CustomerName: Lazy K Kountry Store,
        ContactName: John Steel,
        Address: 12 Orchestra Terrace,
        City: Walla Walla,
        PostalCode: 99362,
        Country: USA

CustomerID: 44,
        CustomerName: Lehmanns Marktstand,
        ContactName: Renate Messner,
        Address: Magazinweg 7,
        City: Frankfurt a.M.,
        PostalCode: 60528,
        Country: Germany

CustomerID: 45,
        CustomerName: Let''s Stop N Shop,
        ContactName: Jaime Yorres,
        Address: 87 Polk St. Suite 5,
        City: San Francisco,
        PostalCode: 94117,
        Country: USA

CustomerID: 46,
        CustomerName: LILA-Supermercado,
        ContactName: Carlos González,
        Address: Carrera 52 con Ave. Bolívar #65-98 Llano Largo,
        City: Barquisimeto,
        PostalCode: 3508,
        Country: Venezuela

CustomerID: 47,
        CustomerName: LINO-Delicateses,
        ContactName: Felipe Izquierdo,
        Address: Ave. 5 de Mayo Porlamar,
        City: I. de Margarita,
        PostalCode: 4980,
        Country: Venezuela

CustomerID: 48,
        CustomerName: Lonesome Pine Restaurant,
        ContactName: Fran Wilson,
        Address: 89 Chiaroscuro Rd.,
        City: Portland,
        PostalCode: 97219,
        Country: USA

CustomerID: 49,
        CustomerName: Magazzini Alimentari Riuniti,
        ContactName: Giovanni Rovelli,
        Address: Via Ludovico il Moro 22,
        City: Bergamo,
        PostalCode: 24100,
        Country: Italy

CustomerID: 50,
        CustomerName: Maison Dewey,
        ContactName: Catherine Dewey,
        Address: Rue Joseph-Bens 532,
        City: Bruxelles,
        PostalCode: B-1180,
        Country: Belgium

CustomerID: 51,
        CustomerName: Mère Paillarde,
        ContactName: Jean Fresnière,
        Address: 43 rue St. Laurent,
        City: Montréal,
        PostalCode: H1J 1C3,
        Country: Canada

CustomerID: 52,
        CustomerName: Morgenstern Gesundkost,
        ContactName: Alexander Feuer,
        Address: Heerstr. 22,
        City: Leipzig,
        PostalCode: 4179,
        Country: Germany

CustomerID: 53,
        CustomerName: North/South,
        ContactName: Simon Crowther,
        Address: South House 300 Queensbridge,
        City: London,
        PostalCode: SW7 1RZ,
        Country: UK

CustomerID: 54,
        CustomerName: Océano Atlántico Ltda.,
        ContactName: Yvonne Moncada,
        Address: Ing. Gustavo Moncada 8585 Piso 20-A,
        City: Buenos Aires,
        PostalCode: 1010,
        Country: Argentina

CustomerID: 55,
        CustomerName: Old World Delicatessen,
        ContactName: Rene Phillips,
        Address: 2743 Bering St.,
        City: Anchorage,
        PostalCode: 99508,
        Country: USA

CustomerID: 56,
        CustomerName: Ottilies Käseladen,
        ContactName: Henriette Pfalzheim,
        Address: Mehrheimerstr. 369,
        City: Köln,
        PostalCode: 50739,
        Country: Germany

CustomerID: 57,
        CustomerName: Paris spécialités,
        ContactName: Marie Bertrand,
        Address: 265, boulevard Charonne,
        City: Paris,
        PostalCode: 75012,
        Country: France

CustomerID: 58,
        CustomerName: Pericles Comidas clásicas,
        ContactName: Guillermo Fernández,
        Address: Calle Dr. Jorge Cash 321,
        City: México D.F.,
        PostalCode: 5033,
        Country: Mexico

CustomerID: 59,
        CustomerName: Piccolo und mehr,
        ContactName: Georg Pipps,
        Address: Geislweg 14,
        City: Salzburg,
        PostalCode: 5020,
        Country: Austria

CustomerID: 60,
        CustomerName: Princesa Isabel Vinhoss,
        ContactName: Isabel de Castro,
        Address: Estrada da saúde n. 58,
        City: Lisboa,
        PostalCode: 1756,
        Country: Portugal

CustomerID: 61,
        CustomerName: Que Delícia,
        ContactName: Bernardo Batista,
        Address: Rua da Panificadora, 12,
        City: Rio de Janeiro,
        PostalCode: 02389-673,
        Country: Brazil

CustomerID: 62,
        CustomerName: Queen Cozinha,
        ContactName: Lúcia Carvalho,
        Address: Alameda dos Canàrios, 891,
        City: São Paulo,
        PostalCode: 05487-020,
        Country: Brazil

CustomerID: 63,
        CustomerName: QUICK-Stop,
        ContactName: Horst Kloss,
        Address: Taucherstraße 10,
        City: Cunewalde,
        PostalCode: 1307,
        Country: Germany

CustomerID: 64,
        CustomerName: Rancho grande,
        ContactName: Sergio Gutiérrez,
        Address: Av. del Libertador 900,
        City: Buenos Aires,
        PostalCode: 1010,
        Country: Argentina

CustomerID: 65,
        CustomerName: Rattlesnake Canyon Grocery,
        ContactName: Paula Wilson,
        Address: 2817 Milton Dr.,
        City: Albuquerque,
        PostalCode: 87110,
        Country: USA

CustomerID: 66,
        CustomerName: Reggiani Caseifici,
        ContactName: Maurizio Moroni,
        Address: Strada Provinciale 124,
        City: Reggio Emilia,
        PostalCode: 42100,
        Country: Italy

CustomerID: 67,
        CustomerName: Ricardo Adocicados,
        ContactName: Janete Limeira,
        Address: Av. Copacabana, 267,
        City: Rio de Janeiro,
        PostalCode: 02389-890,
        Country: Brazil

CustomerID: 68,
        CustomerName: Richter Supermarkt,
        ContactName: Michael Holz,
        Address: Grenzacherweg 237,
        City: Genève,
        PostalCode: 1203,
        Country: Switzerland

CustomerID: 69,
        CustomerName: Romero y tomillo,
        ContactName: Alejandra Camino,
        Address: Gran Vía, 1,
        City: Madrid,
        PostalCode: 28001,
        Country: Spain

CustomerID: 70,
        CustomerName: Santé Gourmet,
        ContactName: Jonas Bergulfsen,
        Address: Erling Skakkes gate 78,
        City: Stavern,
        PostalCode: 4110,
        Country: Norway

CustomerID: 71,
        CustomerName: Save-a-lot Markets,
        ContactName: Jose Pavarotti,
        Address: 187 Suffolk Ln.,
        City: Boise,
        PostalCode: 83720,
        Country: USA

CustomerID: 72,
        CustomerName: Seven Seas Imports,
        ContactName: Hari Kumar,
        Address: 90 Wadhurst Rd.,
        City: London,
        PostalCode: OX15 4NB,
        Country: UK

CustomerID: 73,
        CustomerName: Simons bistro,
        ContactName: Jytte Petersen,
        Address: Vinbæltet 34,
        City: København,
        PostalCode: 1734,
        Country: Denmark

CustomerID: 74,
        CustomerName: Spécialités du monde,
        ContactName: Dominique Perrier,
        Address: 25, rue Lauriston,
        City: Paris,
        PostalCode: 75016,
        Country: France

CustomerID: 75,
        CustomerName: Split Rail Beer & Ale,
        ContactName: Art Braunschweiger,
        Address: P.O. Box 555,
        City: Lander,
        PostalCode: 82520,
        Country: USA

CustomerID: 76,
        CustomerName: Suprêmes délices,
        ContactName: Pascale Cartrain,
        Address: Boulevard Tirou, 255,
        City: Charleroi,
        PostalCode: B-6000,
        Country: Belgium

CustomerID: 77,
        CustomerName: The Big Cheese,
        ContactName: Liz Nixon,
        Address: 89 Jefferson Way Suite 2,
        City: Portland,
        PostalCode: 97201,
        Country: USA

CustomerID: 78,
        CustomerName: The Cracker Box,
        ContactName: Liu Wong,
        Address: 55 Grizzly Peak Rd.,
        City: Butte,
        PostalCode: 59801,
        Country: USA

CustomerID: 79,
        CustomerName: Toms Spezialitäten,
        ContactName: Karin Josephs,
        Address: Luisenstr. 48,
        City: Münster,
        PostalCode: 44087,
        Country: Germany

CustomerID: 80,
        CustomerName: Tortuga Restaurante,
        ContactName: Miguel Angel Paolino,
        Address: Avda. Azteca 123,
        City: México D.F.,
        PostalCode: 5033,
        Country: Mexico

CustomerID: 81,
        CustomerName: Tradição Hipermercados,
        ContactName: Anabela Domingues,
        Address: Av. Inês de Castro, 414,
        City: São Paulo,
        PostalCode: 05634-030,
        Country: Brazil

CustomerID: 82,
        CustomerName: Trail''s Head Gourmet Provisioners,
        ContactName: Helvetius Nagy,
        Address: 722 DaVinci Blvd.,
        City: Kirkland,
        PostalCode: 98034,
        Country: USA

CustomerID: 83,
        CustomerName: Vaffeljernet,
        ContactName: Palle Ibsen,
        Address: Smagsløget 45,
        City: Århus,
        PostalCode: 8200,
        Country: Denmark

CustomerID: 84,
        CustomerName: Victuailles en stock,
        ContactName: Mary Saveley,
        Address: 2, rue du Commerce,
        City: Lyon,
        PostalCode: 69004,
        Country: France

CustomerID: 85,
        CustomerName: Vins et alcools Chevalier,
        ContactName: Paul Henriot,
        Address: 59 rue de l''Abbaye,
        City: Reims,
        PostalCode: 51100,
        Country: France

CustomerID: 86,
        CustomerName: Die Wandernde Kuh,
        ContactName: Rita Müller,
        Address: Adenauerallee 900,
        City: Stuttgart,
        PostalCode: 70563,
        Country: Germany

CustomerID: 87,
        CustomerName: Wartian Herkku,
        ContactName: Pirkko Koskitalo,
        Address: Torikatu 38,
        City: Oulu,
        PostalCode: 90110,
        Country: Finland

CustomerID: 88,
        CustomerName: Wellington Importadora,
        ContactName: Paula Parente,
        Address: Rua do Mercado, 12,
        City: Resende,
        PostalCode: 08737-363,
        Country: Brazil

CustomerID: 89,
        CustomerName: White Clover Markets,
        ContactName: Karl Jablonski,
        Address: 305 - 14th Ave. S. Suite 3B,
        City: Seattle,
        PostalCode: 98128,
        Country: USA

CustomerID: 90,
        CustomerName: Wilman Kala,
        ContactName: Matti Karttunen,
        Address: Keskuskatu 45,
        City: Helsinki,
        PostalCode: 21240,
        Country: Finland

CustomerID: 91,
        CustomerName: Wolski,
        ContactName: Zbyszek,
        Address: ul. Filtrowa 68,
        City: Walla,
        PostalCode: 01-012,
        Country: Poland

### SQL HOME

In [3]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()
    cursor.execute(
        '''
        SELECT * FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

### SQL Intro

가능한 것
- 쿼리 실행
- db에서 데이터 받기
- INSERT
- UPDATE
- DELETE
- CREATE DB, Tables
- CREATE Stored Procedures
- CREATE VIEW
- SET permissions on tb, prcd, views


RDBMS
- DB 관리 프로그램
- MySQL,Oracle, postgresql 등 존재.

Field = Column = Attribute

Record = Row = Tuple

In [4]:
with sqlite3.connect('northwind.db') as conn:
    cursor.execute(
        '''
        SELECT * FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

### SQL Syntax

- STATEMENT는 대소문자 가리지 않음.
- 세미콜론(;) 붙이기
- SELECT - extracts data from a database
- UPDATE - updates data in a database
- DELETE - deletes data from a database
- INSERT INTO - inserts new data into a database
- CREATE DATABASE - creates a new database
- ALTER DATABASE - modifies a database
- CREATE TABLE - creates a new table
- ALTER TABLE - modifies a table
- DROP TABLE - deletes a table
- CREATE INDEX - creates an index (search key)
- DROP INDEX - deletes an index

In [5]:
with sqlite3.connect('northwind.db') as conn:
    cursor.execute(
        '''
        SELECT * FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

### SQL SELECT Statement

In [6]:
with sqlite3.connect('northwind.db') as conn:
    cursor.execute(
        '''
        SELECT CustomerName, City FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

('Alfreds Futterkiste', 'Berlin')
('Ana Trujillo Emparedados y helados', 'México D.F.')
('Antonio Moreno Taquería', 'México D.F.')
('Around the Horn', 'London')
('Berglunds snabbköp', 'Luleå')
('Blauer See Delikatessen', 'Mannheim')
('Blondel père et fils', 'Strasbourg')
('Bólido Comidas preparadas', 'Madrid')
("Bon app''", 'Marseille')
('Bottom-Dollar Marketse', 'Tsawassen')
("B''s Beverages", 'London')
('Cactus Comidas para llevar', 'Buenos Aires')
('Centro comercial Moctezuma', 'México D.F.')
('Chop-suey Chinese', 'Bern')
('Comércio Mineiro', 'São Paulo')
('Consolidated Holdings', 'London')
('Drachenblut Delikatessend', 'Aachen')
('Du monde entier', 'Nantes')
('Eastern Connection', 'London')
('Ernst Handel', 'Graz')
('Familia Arquibaldo', 'São Paulo')
('FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Folies gourmandes', 'Lille')
('Folk och fä HB', 'Bräcke')
('Frankenversand', 'München')
('France restauration', 'Nantes')
('Franchi S.p.A.', 'Torino')
('Furia Bacalhau e Frutos do Mar', 'Lisboa')
('Galería del gastrónomo', 'Barcelona')
('Godos Cocina Típica', 'Sevilla')
('Gourmet Lanchonetes', 'Campinas')
('Great Lakes Food Market', 'Eugene')
('GROSELLA-Restaurante', 'Caracas')
('Hanari Carnes', 'Rio de Janeiro')
('HILARIÓN-Abastos', 'San Cristóbal')
('Hungry Coyote Import Store', 'Elgin')
('Hungry Owl All-Night Grocers', 'Cork')
('Island Trading', 'Cowes')
('Königlich Essen', 'Brandenburg')
("La corne d''abondance", 'Versailles')
("La maison d''Asie", 'Toulouse')
('Laughing Bacchus Wine Cellars', 'Vancouver')
('Lazy K Kountry Store', 'Walla Walla')
('Lehmanns Marktstand', 'Frankfurt a.M.')
("Let''s Stop N Shop", 'San Francisco')
('LILA-Supermercado', 'Barquisimeto')
('LINO-Delicateses', 'I. de Margarita')
('Lonesome Pine Restaurant', 'Portland')
('Magazzini Alimentari Riuniti', 'Bergamo')
('Maison Dewey', 'Bruxelles')
('Mère Paillarde', 'Montréal')
('Morgenstern Gesundkost', 'Leipzig')
('North/South', 'London')
('Océano Atlántico Ltda.', 'Buenos Aires')
('Old World Delicatessen', 'Anchorage')
('Ottilies Käseladen', 'Köln')
('Paris spécialités', 'Paris')
('Pericles Comidas clásicas', 'México D.F.')
('Piccolo und mehr', 'Salzburg')
('Princesa Isabel Vinhoss', 'Lisboa')
('Que Delícia', 'Rio de Janeiro')
('Queen Cozinha', 'São Paulo')
('QUICK-Stop', 'Cunewalde')
('Rancho grande', 'Buenos Aires')
('Rattlesnake Canyon Grocery', 'Albuquerque')
('Reggiani Caseifici', 'Reggio Emilia')
('Ricardo Adocicados', 'Rio de Janeiro')
('Richter Supermarkt', 'Genève')
('Romero y tomillo', 'Madrid')
('Santé Gourmet', 'Stavern')
('Save-a-lot Markets', 'Boise')
('Seven Seas Imports', 'London')
('Simons bistro', 'København')
('Spécialités du monde', 'Paris')
('Split Rail Beer & Ale', 'Lander')
('Suprêmes délices', 'Charleroi')
('The Big Cheese', 'Portland')
('The Cracker Box', 'Butte')
('Toms Spezialitäten', 'Münster')
('Tortuga Restaurante', 'México D.F.')
('Tradição Hipermercados', 'São Paulo')
("Trail''s Head Gourmet Provisioners", 'Kirkland')
('Vaffeljernet', 'Århus')
('Victuailles en stock', 'Lyon')
('Vins et alcools Chevalier', 'Reims')
('Die Wandernde Kuh', 'Stuttgart')
('Wartian Herkku', 'Oulu')
('Wellington Importadora', 'Resende')
('White Clover Markets', 'Seattle')
('Wilman Kala', 'Helsinki')
('Wolski', 'Walla')

In [7]:
with sqlite3.connect('northwind.db') as conn:
    # Select ALL
    cursor.execute(
        '''
        SELECT * FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')

### SQL SELECT DISTINCT Statement


- 중복 제거에는 다양한 방법이 있음.
1. GROUP BY
대상: 집계가 필요한 테이블 (판매, 로그, 통계 데이터)
상황: COUNT, SUM, AVG 등의 집계가 필요할 때

```sql
-- 예: 국가별 총 주문액
SELECT Country, COUNT(*) as OrderCount, SUM(Amount) as TotalAmount
FROM Orders
GROUP BY Country
```

2. ROW_NUMBER() OVER(PARTITION BY)
대상: 타임스탬프가 있는 테이블 (이벤트 로그, 센서 데이터)
상황: 시간순으로 가장 최근 데이터만 필요할 때

```sql
-- 예: 각 고객의 가장 최근 주문
SELECT * FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY CustomerID ORDER BY OrderDate DESC) as rn
    FROM Orders
) tmp
WHERE rn = 1
```

3. EXISTS
대상: 대용량 테이블
상황: 인덱스가 잘 구성되어 있고, 전체 칼럼이 필요할 때 (왜지?)

```sql
-- 예: 중복된 이메일을 가진 첫 번째 사용자만 선택
SELECT a.* 
FROM Users a
WHERE NOT EXISTS (
    SELECT 1 FROM Users b
    WHERE b.Email = a.Email 
    AND b.ID < a.ID
)
```

4. UNION
대상: 여러 테이블의 데이터를 합칠 때
상황: 테이블 구조는 같지만 데이터가 분산되어 있을 때

```sql
-- 예: 현재 고객과 이전 고객 데이터 통합
SELECT CustomerID, Name, Email FROM CurrentCustomers
UNION
SELECT CustomerID, Name, Email FROM ArchivedCustomers
```

5. DISTINCT
대상: 작은 테이블
상황: 단순한 중복 제거가 필요하고 성능이 중요하지 않을 때

```sql
-- 예: 주문이 있는 고객 목록
SELECT DISTINCT CustomerID 
FROM Orders
```

In [8]:
with sqlite3.connect('northwind.db') as conn:
    # Select DISTINCT
    print("SELECT DISTINCT")
    cursor.execute(
        '''
        SELECT DISTINCT Country FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # SELECT Example Without DISTINCT
    print("SELECT Example Without DISTINCT")
    cursor.execute(
        '''
        SELECT Country FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    
    # COUNT DISTINCT
    print("COUNT DISTINCT")
    cursor.execute(
        '''
        SELECT COUNT(DISTINCT Country) FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # IN MS Access
    print("IN MS Access")
    cursor.execute(
        '''
        SELECT COUNT(*) AS DistinctCountries
        FROM (SELECT DISTINCT Country FROM Customers);
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    conn.commit()

SELECT DISTINCT
('Germany',)
('Mexico',)
('UK',)
('Sweden',)
('France',)
('Spain',)
('Canada',)
('Argentina',)
('Switzerland',)
('Brazil',)
('Austria',)
('Italy',)
('Portugal',)
('USA',)
('Venezuela',)
('Ireland',)
('Belgium',)
('Norway',)
('Denmark',)
('Finland',)
('Poland',)
SELECT Example Without DISTINCT
('Germany',)
('Mexico',)
('Mexico',)
('UK',)
('Sweden',)
('Germany',)
('France',)
('Spain',)
('France',)
('Canada',)
('UK',)
('Argentina',)
('Mexico',)
('Switzerland',)
('Brazil',)
('UK',)
('Germany',)
('France',)
('UK',)
('Austria',)
('Brazil',)
('Spain',)
('France',)
('Sweden',)
('Germany',)
('France',)
('Italy',)
('Portugal',)
('Spain',)
('Spain',)
('Brazil',)
('USA',)
('Venezuela',)
('Brazil',)
('Venezuela',)
('USA',)
('Ireland',)
('UK',)
('Germany',)
('France',)
('France',)
('Canada',)
('USA',)
('Germany',)
('USA',)
('Venezuela',)
('Venezuela',)
('USA',)
('Italy',)
('Belgium',)
('Canada',)
('Germany',)
('UK',)
('Argentina',)
('USA',)
('Germany',)
('France',)
('Mexico',)
('Austria',)
('Portugal',)
('Brazil',)
('Brazil',)
('Germany',)
('Argentina',)
('USA',)
('Italy',)
('Brazil',)
('Switzerland',)
('Spain',)
('Norway',)
('USA',)
('UK',)
('Denmark',)
('France',)
('USA',)
('Belgium',)
('USA',)
('USA',)
('Germany',)
('Mexico',)
('Brazil',)
('USA',)
('Denmark',)
('France',)
('France',)
('Germany',)
('Finland',)
('Brazil',)
('USA',)
('Finland',)
('Poland',)
COUNT DISTINCT
(21,)
IN MS Access
(21,)

- DISTINCT는 SELECT 오른쪽의 모든 값이 동일할 때 중복으로 판단함.

### SQL WHERE Clause
WHERE는 records를 필터링하는 데 사용됨.

- SELECT 뿐 아니라 UPDATE, DELETE 문에서도 사용 가능.

In [9]:
with sqlite3.connect('northwind.db') as conn:
    # The SQL WHERE Clause

    print("The SQL WHERE Clause")
    cursor.execute(
        '''
        SELECT *  FROM Customers
        WHERE Country='Mexico';
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # Text Fields vs. Numeric Fields

    print("Text Fields vs. Numeric Fields")
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerID=1;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # Operators in The WHERE Clause
    print("Operators > in The WHERE Clause")
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerID > 4;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    print("Operators > in The WHERE Clause")
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerID > 4;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    print("Operators <> in The WHERE Clause") # Not Equal
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerID <> 4;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    print("Operators BETWEEN in The WHERE Clause")
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName BETWEEN "A" AND "C";
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    print("Operators LIKE in The WHERE Clause") 
    # Indexing을 위하여 앞에 %를 붙이는 것은 좋지 않다. 뒤에 붙이는 것이 좋다.
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE "A%";
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
        
    print("Operators IN in The WHERE Clause")
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName IN ("Alfreds Futterkiste", "Ana Trujillo Emparedados y helados");
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

The SQL WHERE Clause
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
Text Fields vs. Numeric Fields
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
Operators > in The WHERE Clause
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
Operators > in The WHERE Clause
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
Operators <> in The WHERE Clause
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')

### SQL ORDER BY Keyword
ORDER BY는 결과를 정렬하는 데 사용됨.

```sql
SELECT column1, column2, ...
FROM table_name
ORDER BY column1, column2, ... ASC|DESC;
```

In [10]:
with sqlite3.connect('northwind.db') as conn:
    # The SQL ORDER BY

    print("The SQL ORDER BY")
    cursor.execute(
        '''
        SELECT * FROM Products
        ORDER BY Price;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # DESC

    print("DESC")
    cursor.execute(
        '''
        SELECT * FROM Products
        ORDER BY Price DESC;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Order Alphabetically

    print("Order Alphabetically")
    cursor.execute(
        '''
        SELECT * FROM Products
        ORDER BY ProductName;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Alphabetically DESC

    print("Alphabetically DESC") 
    cursor.execute(
        '''
        SELECT * FROM Products
        ORDER BY ProductName DESC; 
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # ORDER BY Several Columns

    print("ORDER BY Several Columns") 
    
    cursor.execute(
        '''
        SELECT * FROM Customers
        ORDER BY Country, CustomerName; 
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Using Both ASC and DESC

    print("Using Both ASC and DESC") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        ORDER BY Country ASC, CustomerName DESC; 
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)

The SQL ORDER BY
(33, 'Geitost', 15, 4, '500 g', 2.5)
(24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5)
(13, 'Konbu', 6, 8, '2 kg box', 6)
(52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7)
(54, 'Tourtière', 25, 6, '16 pies', 7.45)
(75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75)
(23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9)
(19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2)
(45, 'Røgede sild', 21, 8, '1k pkg.', 9.5)
(47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5)
(41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10)
(74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10)
(46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12)
(31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13)
(58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14)
(42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15)
(73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18)
(76, 'Lakkalikööri', 23, 1, '500 ml', 18)
(40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19)
(36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20)
(11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21)
(22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21)
(65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05)
(5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)
(71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21.5)
(4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22)
(14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25)
(55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24)
(6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25)
(30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89)
(37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26)
(61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 28.5)
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38)
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
DESC
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 28.5)
(37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26)
(30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89)
(6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25)
(55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24)
(14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25)
(4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22)
(71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21.5)
(5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)
(65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05)
(11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21)
(22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20)
(57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19)
(36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19)
(40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4)
(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18)
(76, 'Lakkalikööri', 23, 1, '500 ml', 18)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15)
(73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14)
(42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14)
(58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10)
(74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10)
(41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65)
(45, 'Røgede sild', 21, 8, '1k pkg.', 9.5)
(47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5)
(19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2)
(23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9)
(75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75)
(54, 'Tourtière', 25, 6, '16 pies', 7.45)
(52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7)
(13, 'Konbu', 6, 8, '2 kg box', 6)
(24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5)
(33, 'Geitost', 15, 4, '500 g', 2.5)
Order Alphabetically
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10)
(40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18)
(4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22)
(5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
(58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25)
(52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7)
(71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21.5)
(33, 'Geitost', 15, 4, '500 g', 2.5)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38)
(31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5)
(6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25)
(37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26)
(24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65)
(13, 'Konbu', 6, 8, '2 kg box', 6)
(76, 'Lakkalikööri', 23, 1, '500 ml', 18)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14)
(74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10)
(65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)
(30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24)
(11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55)
(57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5)
(75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75)
(73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(45, 'Røgede sild', 21, 8, '1k pkg.', 9.5)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10)
(61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 28.5)
(46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25)
(54, 'Tourtière', 25, 6, '16 pies', 7.45)
(23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9)
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5)
Alphabetically DESC
(47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9)
(54, 'Tourtière', 25, 6, '16 pies', 7.45)
(14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18)
(46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12)
(61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 28.5)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14)
(45, 'Røgede sild', 21, 8, '1k pkg.', 9.5)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15)
(75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75)
(57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21)
(55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17)
(65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05)
(74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14)
(76, 'Lakkalikööri', 23, 1, '500 ml', 18)
(13, 'Konbu', 6, 8, '2 kg box', 6)
(41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36)
(24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5)
(37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26)
(6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25)
(31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(33, 'Geitost', 15, 4, '500 g', 2.5)
(71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21.5)
(52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7)
(58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)
(4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19)
(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34)
(40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10)
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
ORDER BY Several Columns
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')

### SQL AND Operator
AND는 WHERE 절에 두 개 이상의 조건을 지정하는 데 사용됨.

```sql
SELECT column1, column2, ...
FROM table_name
WHERE condition1 AND condition2 AND condition3 ...;
```

OR은 하나라도 참이면 됨.

In [11]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    # The SQL AND Operator

    print("The SQL AND Operator") 
    
    cursor.execute(
        '''
        SELECT * 
        FROM Customers
        WHERE Country = 'Spain' AND CustomerName LIKE 'G%';
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # All Conditions Must Be True

    print("All Conditions Must Be True") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country = 'Germany'
        AND City = 'Berlin'
        AND PostalCode > 12000;
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Combining AND and OR

    print("Combining AND and OR") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country = 'Spain' AND (CustomerName LIKE 'G%' OR CustomerName LIKE 'R%');
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Without Parentheses

    print("Without Parentheses") 
    # AND 절과 OR 절이 별개가 된다.
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country = 'Spain' AND CustomerName LIKE 'G%' OR CustomerName LIKE 'R%';
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)

The SQL AND Operator
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
All Conditions Must Be True
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
Combining AND and OR
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
Without Parentheses
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')

### SQL OR Operator

In [12]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    # The SQL OR Operator

    print("The SQL OR Operator") 
    
    cursor.execute(
        '''
        SELECT *
        FROM Customers
        WHERE Country = 'Germany' OR Country = 'Spain';
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # At Least One Condition Must Be True

    print("At Least One Condition Must Be True") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE City = 'Berlin' 
        OR CustomerName LIKE 'G%' 
        OR Country = 'Norway';
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Combining AND and OR

    print("Combining AND and OR") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country = 'Spain' AND (CustomerName LIKE 'G%' OR CustomerName LIKE 'R%');
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)

The SQL OR Operator
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
At Least One Condition Must Be True
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
Combining AND and OR
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')

### SQL NOT Operator

```sql
SELECT column1, column2, ...
FROM table_name
WHERE NOT condition;
```

In [13]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    # The NOT Operator

    print("The NOT Operator") 
    
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE NOT Country = 'Spain';
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # NOT LIKE

    print("NOT LIKE") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName NOT LIKE 'A%';
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # NOT BETWEEN

    print("NOT BETWEEN") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerID NOT BETWEEN 10 AND 60;
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # NOT IN

    print("NOT IN") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE City NOT IN ('Paris', 'London');
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    # NOT Greater Than

    print("NOT Greater Than") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE NOT CustomerID > 50;
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # NOT Less Than

    print("NOT Less Than") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE NOT CustomerId < 50;
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)

The NOT Operator
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
NOT LIKE
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
NOT BETWEEN
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')

## SQL INSERT INTO Statement

- 부분적인 컬럼만 Insert
```sql
INSERT INTO table_name (column1, column2, column3, ...)
VALUES (value1, value2, value3, ...);
```

- 테이블 전체에 Insert
```sql
INSERT INTO table_name
VALUES (value1, value2, value3, ...);
```

In [14]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    # INSERT INTO Example

    print("INSERT INTO Example") 
    
    cursor.execute(
        '''
        INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country)
        VALUES ('Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway');
        '''
    )
    res = cursor.lastrowid
    print("Insert 시작 row id", res)

    # CustomerID는 AutoIncrement.
    conn.rollback()
    
    # Insert Data Only in Specified Columns

    print("Insert Data Only in Specified Columns") 

    cursor.execute(
        '''
        INSERT INTO Customers (CustomerName, City, Country)
        VALUES ('Cardinal', 'Stavanger', 'Norway');
        '''
    )
    res = cursor.lastrowid
    print("Insert 시작 row id", res)

    conn.rollback()
    
    # Insert Multiple Rows

    print("Insert Multiple Rows") 

    cursor.execute(
        '''
        INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country)
        VALUES
        ('Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway'),
        ('Greasy Burger', 'Per Olsen', 'Gateveien 15', 'Sandnes', '4306', 'Norway'),
        ('Tasty Tee', 'Finn Egan', 'Streetroad 19B', 'Liverpool', 'L1 0AA', 'UK');
        '''
    )

    res = cursor.lastrowid
    print("Insert 시작 row id", res)

    conn.rollback()

INSERT INTO Example
Insert 시작 row id 92
Insert Data Only in Specified Columns
Insert 시작 row id 92
Insert Multiple Rows
Insert 시작 row id 94

### SQL NULL Values

- NULL 값은 필드에 데이터가 없음을 의미함. 0이나 공백과 다름.
- 비교 연산자는 NULL 값과 비교할 때 항상 FALSE를 반환함.
- IS NULL, IS NOT NULL을 사용하여 NULL 값과 비교함.

In [15]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    # The IS NULL Operator

    print("The IS NULL Operator") 
    
    cursor.execute(
        '''
        SELECT CustomerName, ContactName, Address
        FROM Customers
        WHERE Address IS NULL;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # The IS NOT NULL Operator

    print("The IS NOT NULL Operator") 

    cursor.execute(
        '''
        SELECT CustomerName, ContactName, Address
        FROM Customers
        WHERE Address IS NOT NULL;
        '''
    )
    
    rows = cursor.fetchall()
    for row in rows:
        print(row)

The IS NULL Operator
The IS NOT NULL Operator
('Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57')
('Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222')
('Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312')
('Around the Horn', 'Thomas Hardy', '120 Hanover Sq.')
('Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8')
('Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57')
('Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber')
('Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67')
("Bon app''", 'Laurence Lebihans', '12, rue des Bouchers')
('Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.')
("B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus')
('Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333')
('Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993')
('Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29')
('Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23')
('Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery')
('Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21')
('Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages')
('Eastern Connection', 'Ann Devon', '35 King George')
('Ernst Handel', 'Roland Mendel', 'Kirchgasse 6')
('Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92')
('FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86')
('Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai')
('Folk och fä HB', 'Maria Larsson', 'Åkergatan 24')
('Frankenversand', 'Peter Franken', 'Berliner Platz 43')
('France restauration', 'Carine Schmitt', '54, rue Royale')
('Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34')
('Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32')
('Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23')
('Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33')
('Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442')
('Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.')
('GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes')
('Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67')
('HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35')
('Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.')
('Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road')
('Island Trading', 'Helen Bennett', 'Garden House Crowther Way')
('Königlich Essen', 'Philip Cramer', 'Maubelstr. 90')
("La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe")
("La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine')
('Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.')
('Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace')
('Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7')
("Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5')
('LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo')
('LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar')
('Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.')
('Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22')
('Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532')
('Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent')
('Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22')
('North/South', 'Simon Crowther', 'South House 300 Queensbridge')
('Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A')
('Old World Delicatessen', 'Rene Phillips', '2743 Bering St.')
('Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369')
('Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne')
('Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321')
('Piccolo und mehr', 'Georg Pipps', 'Geislweg 14')
('Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58')
('Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12')
('Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891')
('QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10')
('Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900')
('Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.')
('Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124')
('Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267')
('Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237')
('Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1')
('Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78')
('Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.')
('Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.')
('Simons bistro', 'Jytte Petersen', 'Vinbæltet 34')
('Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston')
('Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555')
('Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255')
('The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2')
('The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.')
('Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48')
('Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123')
('Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414')
("Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.')
('Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45')
('Victuailles en stock', 'Mary Saveley', '2, rue du Commerce')
('Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye")
('Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900')
('Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38')
('Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12')
('White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B')
('Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45')
('Wolski', 'Zbyszek', 'ul. Filtrowa 68')

### SQL UPDATE Statement
- 데이터베이스의 기존 레코드를 업데이트하는 데 사용됨.

```sql
UPDATE table_name
SET column1 = value1, column2 = value2, ...
WHERE condition;
```

- [주의] WHERE 절을 생략하면 모든 레코드가 업데이트됨.

In [16]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    # The SQL UPDATE Statement

    print("The SQL UPDATE Statement") 
    
    cursor.execute(
        '''
        UPDATE Customers
        SET ContactName = 'Alfred Schmidt', City= 'Frankfurt'
        WHERE CustomerID = 1;
        '''
    )
    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()
    
    # Update Multiple Columns

    print("Update Multiple Columns") 

    cursor.execute(
        '''
        UPDATE Customers
        SET ContactName='Juan'
        WHERE Country='Mexico';
        '''
    )
    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()
    
    # Update Warning!

    print("Update Warning!") 

    cursor.execute(
        '''
        UPDATE Customers
        SET ContactName='Juan';
        '''
    )
    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()

The SQL UPDATE Statement
영향받은 행의 수: 1
Update Multiple Columns
영향받은 행의 수: 5
Update Warning!
영향받은 행의 수: 91

### SQL DELETE Statement
- 데이터베이스의 기존 레코드를 삭제하는 데 사용됨.

```sql
DELETE FROM table_name WHERE condition;
```
- [주의] WHERE 절을 생략하면 모든 레코드가 삭제됨.

In [20]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    # SQL DELETE Example

    print("SQL DELETE Example") 
    
    cursor.execute(
        '''
        DELETE FROM Customers 
        WHERE CustomerName='Alfreds Futterkiste';
        '''
    )
    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()
    
    # Delete All Records, Not table

    print("Delete All Records") 

    cursor.execute(
        '''
        DELETE FROM Customers;
        '''
    )
    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()
    
    # Delete a Table

    print("Delete a Table") 

    cursor.execute(
        '''
        DROP TABLE Customers;
        '''
    )
    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()

SQL DELETE Example
영향받은 행의 수: 1
Delete All Records
영향받은 행의 수: 91
Delete a Table
영향받은 행의 수: -1

### SQL TOP, LIMIT, FETCH FIRST or ROWNUM Clause

- TOP은 상위 n개의 레코드를 선택하는 데 사용됨. 큰 테이블에서 확인할 때 유용함. 
- MySQL에선 LIMIT

```sql
SELECT TOP number|percent column_name(s)
FROM table_name
WHERE condition;
```

Oracle 12
```sql
SELECT column_name(s)
FROM table_name
ORDER BY column_name(s)
FETCH FIRST number ROWS ONLY;
```

In [3]:
with sqlite3.connect('northwind.db') as conn:
    cursor = conn.cursor()

    # LIMIT

    print("LIMIT") 
    
    cursor.execute(
        '''
        SELECT * FROM Customers
        LIMIT 3;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # FETCH FIRST (Oracle)

    print("FETCH FIRST (Oracle)") 

    # cursor.execute(
    #     '''
    #     SELECT * FROM Customers
    #     FETCH FIRST 3 ROWS ONLY;
    #     '''
    # )
    
    # rows = cursor.fetchall()
    # for row in rows:
    #     print(row)
    
    # SQL TOP PERCENT Example

    print("SQL TOP PERCENT Example (SQL Server/MS Access)") 

    # cursor.execute(
    #     '''
    #     SELECT TOP 50 PERCENT * FROM Customers;
    #     '''
    # )
    
    # rows = cursor.fetchall()
    # for row in rows:
    #     print(row)

    # Oracle Percent

    """
    SELECT * FROM Customers
    FETCH FIRST 50 PERCENT ROWS ONLY;
    """

    # ADD a WHERE CLAUSE

    print("ADD a WHERE CLAUSE (SQL Server, MS Access)") 
    
    '''
    SELECT TOP 3 * FROM Customers
    WHERE Country='Germany';
    '''

    print("ADD a WHERE CLAUSE (MySQL)") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country='Germany'
        LIMIT 3;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    print("ADD a WHERE CLAUSE (Oracle)") 
    
    '''
    SELECT * FROM Customers
    WHERE Country='Germany'
    FETCH FIRST 3 ROWS ONLY;
    '''

    # ADD the ORDER BY Keyword

    print("ADD the ORDER BY Keyword (MySQL)") 

    cursor.execute(
        '''
        SELECT * FROM Customers
        ORDER BY CustomerName DESC
        LIMIT 3;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

LIMIT
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
FETCH FIRST (Oracle)
SQL TOP PERCENT Example (SQL Server/MS Access)
ADD a WHERE CLAUSE (SQL Server, MS Access)
ADD a WHERE CLAUSE (MySQL)
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
ADD a WHERE CLAUSE (Oracle)
ADD the ORDER BY Keyword (MySQL)
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')

### SQL Aggregate Functions
- GROUP BY와 같이 자주 사용된다.
- COUNT() 빼고 NULL을 무시한다.

- MIN()
- MAX()
- COUNT()
- SUM()
- AVG()

### SQL MIN() and MAX() Functions

In [6]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # MIN Example
    print("MIN Example")

    cursor.execute(
        '''
        SELECT MIN(Price)
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # MAX Example
    print("MAX Example")

    cursor.execute(
        '''
        SELECT MAX(Price)
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # Set Column Name (Alias)
    print("Set Column Name (Alias)")

    cursor.execute(
        '''
        SELECT MIN(Price) AS SmallestPrice
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Use MIN() with GROUP BY
    print("Use MIN() with GROUP BY")
    print("CategoryID 기준 Grouping 후 가장 작은 Price")

    cursor.execute(
        '''
        SELECT MIN(Price) AS SmallestPrice, CategoryID
        FROM Products
        GROUP BY CategoryID;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

MIN Example
(2.5,)
MAX Example
(263.5,)
Set Column Name (Alias)
(2.5,)
Use MIN() with GROUP BY
CategoryID 기준 Grouping 후 가장 작은 Price
(4.5, 1)
(10, 2)
(9.2, 3)
(2.5, 4)
(7, 5)
(7.45, 6)
(10, 7)
(6, 8)

### The SQL COUNT() Function
```sql
SELECT COUNT(*)
FROM Products;
```

- Column을 지정하면 NULL이 아닌 값만 Count한다.

In [11]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # Specify Column
    print("Specify Column")

    cursor.execute(
        '''
        SELECT COUNT(ProductName)
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Add a WHERE Clause
    print("Add a WHERE Clause")

    cursor.execute(
        '''
        SELECT COUNT(ProductID)
        FROM Products
        WHERE Price > 20;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # Ignore Duplicates
    print("Ignore Duplicates")

    cursor.execute(
        '''
        SELECT COUNT(DISTINCT Price)
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Use an Alias
    print("Use an Alias")
    
    cursor.execute(
        '''
        SELECT COUNT(*) AS [Number of records]
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    
    # Use COUNT() with GROUP BY
    print("Use COUNT() with GROUP BY")
    
    cursor.execute(
        '''
        SELECT COUNT(*) AS [Number of records], CategoryID
        FROM Products
        GROUP BY CategoryID;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

Specify Column
(77,)
Add a WHERE Clause
(37,)
Ignore Duplicates
(62,)
Use an Alias
(77,)
Use COUNT() with GROUP BY
(12, 1)
(12, 2)
(13, 3)
(10, 4)
(7, 5)
(6, 6)
(5, 7)
(12, 8)

### The SQL SUM() Function
```sql
SELECT SUM(Quantity)
FROM OrderDetails;
```

JOIN 하고 SUM도 가능.

In [17]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # Add a WHERE Clause
    print("Add a WHERE Clause")

    cursor.execute(
        '''
        SELECT SUM(Quantity)
        FROM OrderDetails
        WHERE ProductId = 11;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Use an Alias
    print("Use an Alias")

    cursor.execute(
        '''
        SELECT SUM(Quantity) AS total
        FROM OrderDetails;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # Use SUM() with GROUP BY
    print("Use SUM() with GROUP BY")

    cursor.execute(
        '''
        SELECT OrderID, SUM(Quantity) AS [Total Quantity]
        FROM OrderDetails
        GROUP BY OrderID;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # SUM() With an Expression
    print("SUM() With an Expression") 
    # 각 Quantity에 곱하여 더할 수 있다.
    
    cursor.execute(
        '''
        SELECT SUM(Quantity * 10)
        FROM OrderDetails;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    
    # Join the OrderDetails table to the Products table to find the actual amount
    print("Join the OrderDetails table to the Products table to find the actual amount")
    
    cursor.execute(
        '''
        SELECT SUM(Products.Price * OrderDetails.Quantity)
        FROM OrderDetails
        LEFT JOIN Products ON OrderDetails.ProductID = Products.ProductID;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

Add a WHERE Clause
(182,)
Use an Alias
(12743,)
Use SUM() with GROUP BY
(10248, 27)
(10249, 49)
(10250, 60)
(10251, 41)
(10252, 105)
(10253, 102)
(10254, 57)
(10255, 110)
(10256, 27)
(10257, 46)
(10258, 121)
(10259, 11)
(10260, 102)
(10261, 40)
(10262, 29)
(10263, 184)
(10264, 60)
(10265, 50)
(10266, 12)
(10267, 135)
(10268, 14)
(10269, 80)
(10270, 55)
(10271, 24)
(10272, 70)
(10273, 152)
(10274, 27)
(10275, 18)
(10276, 25)
(10277, 32)
(10278, 64)
(10279, 15)
(10280, 62)
(10281, 11)
(10282, 8)
(10283, 76)
(10284, 61)
(10285, 121)
(10286, 140)
(10287, 75)
(10288, 13)
(10289, 39)
(10290, 60)
(10291, 46)
(10292, 20)
(10293, 33)
(10294, 75)
(10295, 4)
(10296, 57)
(10297, 80)
(10298, 125)
(10299, 35)
(10300, 50)
(10301, 30)
(10302, 80)
(10303, 85)
(10304, 42)
(10305, 80)
(10306, 25)
(10307, 13)
(10308, 6)
(10309, 75)
(10310, 15)
(10311, 13)
(10312, 58)
(10313, 12)
(10314, 95)
(10315, 44)
(10316, 80)
(10317, 20)
(10318, 26)
(10319, 52)
(10320, 30)
(10321, 10)
(10322, 20)
(10323, 13)
(10324, 241)
(10325, 71)
(10326, 90)
(10327, 140)
(10328, 59)
(10329, 50)
(10330, 75)
(10331, 15)
(10332, 66)
(10333, 60)
(10334, 18)
(10335, 86)
(10336, 18)
(10337, 137)
(10338, 35)
(10339, 108)
(10340, 72)
(10341, 17)
(10342, 160)
(10343, 69)
(10344, 105)
(10345, 159)
(10346, 56)
(10347, 70)
(10348, 40)
(10349, 24)
(10350, 33)
(10351, 120)
(10352, 30)
(10353, 62)
(10354, 16)
(10355, 50)
(10356, 62)
(10357, 54)
(10358, 40)
(10359, 206)
(10360, 138)
(10361, 109)
(10362, 94)
(10363, 44)
(10364, 35)
(10365, 24)
(10366, 10)
(10367, 76)
(10368, 78)
(10369, 38)
(10370, 65)
(10371, 6)
(10372, 164)
(10373, 130)
(10374, 45)
(10375, 25)
(10376, 42)
(10377, 40)
(10378, 6)
(10379, 44)
(10380, 74)
(10381, 14)
(10382, 165)
(10383, 55)
(10384, 43)
(10385, 38)
(10386, 25)
(10387, 48)
(10388, 75)
(10389, 81)
(10390, 169)
(10391, 18)
(10392, 50)
(10393, 176)
(10394, 20)
(10395, 106)
(10396, 121)
(10397, 28)
(10398, 150)
(10399, 139)
(10400, 86)
(10401, 168)
(10402, 125)
(10403, 91)
(10404, 100)
(10405, 50)
(10406, 89)
(10407, 60)
(10408, 51)
(10409, 24)
(10410, 65)
(10411, 74)
(10412, 20)
(10413, 78)
(10414, 68)
(10415, 22)
(10416, 50)
(10417, 123)
(10418, 146)
(10419, 80)
(10420, 50)
(10421, 59)
(10422, 2)
(10423, 34)
(10424, 139)
(10425, 30)
(10426, 12)
(10427, 35)
(10428, 20)
(10429, 75)
(10430, 195)
(10431, 130)
(10432, 50)
(10433, 28)
(10434, 24)
(10435, 32)
(10436, 99)
(10437, 15)
(10438, 50)
(10439, 67)
(10440, 208)
(10441, 50)
(10442, 170)
(10443, 18)
SUM() With an Expression
(127430,)
Join the OrderDetails table to the Products table to find the actual amount
(386424.23,)

### The SQL AVG() Function

In [4]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # Add a WHERE Clause
    print("Add a WHERE Clause")

    cursor.execute(
        '''
        SELECT AVG(Price)
        FROM Products
        WHERE CategoryID = 1;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Use an Alias
    print("Use an Alias")

    cursor.execute(
        '''
        SELECT AVG(Price) AS [average price]
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # Higher Than Average
    print("Higher Than Average: 서브쿼리")

    cursor.execute(
        '''
        SELECT * FROM Products
        WHERE 
        price > (SELECT AVG(price) FROM Products);
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Use AVG() with GROUP BY
    print("Use AVG() with GROUP BY") 
    # 각 Quantity에 곱하여 더할 수 있다.
    
    cursor.execute(
        '''
        SELECT AVG(Price) AS AveragePrice, CategoryID
        FROM Products
        GROUP BY CategoryID;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

Add a WHERE Clause
(37.979166666666664,)
Use an Alias
(28.866363636363637,)
Higher Than Average: 서브쿼리
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)
Use AVG() with GROUP BY
(37.979166666666664, 1)
(23.0625, 2)
(25.16, 3)
(28.73, 4)
(20.25, 5)
(54.00666666666667, 6)
(32.37, 7)
(20.6825, 8)

### SQL LIKE Operator
- WHERE 절에서 패턴 매칭을 위해 사용됨.
- %는 0개 이상의 문자와 매칭됨.
- _는 한 문자와 매칭됨.

```sql
SELECT * FROM Customers
WHERE CustomerName LIKE 'a%';
```

In [11]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # The SQL LIKE Operator
    print("The SQL LIKE Operator")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE 'a%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # The _ Wildcard
    print("The _ Wildcard")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE city LIKE 'L_nd__';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    # The % Wildcard
    print("The % Wildcard")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE city LIKE '%L%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    # Starts With
    print("Starts With")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE 'La%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Ends With
    print("Ends With")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '%a';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Contains
    print("Contains")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '%or%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    # Combine Wildcards
    print("Combine Wildcards")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE 'a__%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Without Wildcard
    print("Without Wildcard: db 설정에 따라 대소문자 구분하지 않음. = 과 같음")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country LIKE 'Spain';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

The SQL LIKE Operator
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
The _ Wildcard
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
The % Wildcard
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
Starts With
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
Ends With
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
Contains
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
Combine Wildcards
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
Without Wildcard: db 설정에 따라 대소문자 구분하지 않음. = 과 같음
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')

### SQL Wildcard Characters
- %는 0개 이상의 문자와 매칭됨.
- _는 한 문자와 매칭됨.
- []는 내부 문자 범위와 매칭됨. PostgreSQL, MySQL에서는 사용 불가.
- [^]는 내부 문자 범위를 제외하고 매칭됨. PostgreSQL, MySQL에서는 사용 불가.
- -는 [] 안에서 범위를 지정함. PostgreSQL, MySQL에서는 사용 불가.
- {n}는 n번 반복되는 문자와 매칭됨. Oracle에서만 가능.

다음은 MS Access에서 사용 가능한 와일드카드임.
- #는 숫자와 매칭됨.
- ?는 한 문자와 매칭됨.
- !는 NOT 연산자로 사용됨.
- -는 범위 중 하나를 지정함.
- *는 0개 이상의 문자와 매칭됨.

In [14]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # Using the % Wildcard
    print("Using the % Wildcard")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '%es';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '%mer%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Using the _ Wildcard
    print("Using the _ Wildcard")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE City LIKE '_ondon';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE City LIKE 'L___on';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    # Using the [] Wildcard
    print("Using the [] Wildcard")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '[bsp]%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Using the - Wildcard
    print("Using the - Wildcard")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '[a-f]%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    #  Combine Wildcards
    print("Combine Wildcards")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE 'a__%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerName LIKE '_r%';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

    #  Without Wildcard
    print("Without Wildcard")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country LIKE 'Spain';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

Using the % Wildcard
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
Using the _ Wildcard
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
Using the [] Wildcard
Using the - Wildcard
Combine Wildcards
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
Without Wildcard
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')

### SQL IN Operator
- WHERE 절에서 여러 값을 비교하는 데 사용됨.

```sql
SELECT column_name(s)
FROM table_name
WHERE column_name IN (value1, value2, ...);
```

In [18]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # The SQL IN Operator
    print("The SQL IN Operator")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country IN ('Germany', 'France', 'UK');
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # NOT IN
    print("NOT IN")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE Country NOT IN ('Germany', 'France', 'UK');
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    # IN (SELECT)
    print("IN (SELECT): 서브쿼리 사용.")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerID IN (SELECT CustomerID FROM Orders);
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # NOT IN (SELECT)

    print("NOT IN (SELECT)")

    cursor.execute(
        '''
        SELECT * FROM Customers
        WHERE CustomerID NOT IN (SELECT CustomerID FROM Orders);
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    # NOT BETWEEN

    print("NOT BETWEEN")

    cursor.execute(
        '''
        SELECT * FROM Products
        WHERE Price NOT BETWEEN 10 AND 20;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    #  BETWEEN with IN

    print("BETWEEN with IN")

    cursor.execute(
        '''
        SELECT * FROM Products
        WHERE Price BETWEEN 10 AND 20
        AND CategoryID IN (1,2,3);
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    #  BETWEEN Text Values

    print("BETWEEN Text Values")

    cursor.execute(
        '''
        SELECT * FROM Products
        WHERE ProductName BETWEEN 'Carnarvon Tigers' AND 'Mozzarella di Giovanni'
        ORDER BY ProductName;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    cursor.execute(
        '''
        SELECT * FROM Products
        WHERE ProductName BETWEEN "Carnarvon Tigers" AND "Chef Anton's Cajun Seasoning"
        ORDER BY ProductName;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

    #  NOT BETWEEN Text Values

    print("NOT BETWEEN Text Values")

    cursor.execute(
        '''
        SELECT * FROM Products
        WHERE ProductName NOT BETWEEN 'Carnarvon Tigers' AND 'Mozzarella di Giovanni'
        ORDER BY ProductName;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    #  BETWEEN Dates
    print("BETWEEN Dates")

    # 아래는 MS Access.
    '''
    SELECT * FROM Orders
    WHERE OrderDate BETWEEN #07/01/1996# AND #07/31/1996#;
    '''
    

    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    cursor.execute(
        '''
        SELECT * FROM Orders
        WHERE OrderDate BETWEEN '1996-07-01' AND '1996-07-31';
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

The SQL IN Operator
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
NOT IN
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
IN (SELECT): 서브쿼리 사용.
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
NOT IN (SELECT)
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
NOT BETWEEN
(4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22)
(5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)
(6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25)
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31)
(11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38)
(13, 'Konbu', 6, 8, '2 kg box', 6)
(14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25)
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81)
(22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21)
(23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9)
(24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32)
(33, 'Geitost', 15, 4, '500 g', 2.5)
(37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)
(41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46)
(45, 'Røgede sild', 21, 8, '1k pkg.', 9.5)
(47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53)

### SQL Aliases
- table, column에 대한 별칭을 지정함.
- AS는 생략 가능함.

사용이 용이한 경우:
- 컬럼명이 길거나 복잡한 경우
- 여러 테이블을 조인할 때
- 집계 함수를 사용할 때
- 서브쿼리를 사용할 때
- 두 개 이상의 컬럼을 합칠 때

```sql
SELECT CustomerID AS ID
FROM Customers;
```

In [22]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL Aliases
    print("SQL Aliases")

    cursor.execute(
        '''
        SELECT CustomerID AS ID
        FROM Customers;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # AS is Optional
    print("AS is Optional")

    cursor.execute(
        '''
        SELECT CustomerID ID
        FROM Customers;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
   
    # Alias for Columns
    print("Alias for Columns")

    cursor.execute(
        '''
        SELECT CustomerID AS ID, CustomerName AS Customer
        FROM Customers;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Using Aliases With a Space Character

    print("Using Aliases With a Space Character")

    cursor.execute(
        '''
        SELECT ProductName AS [My Great Products]
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Double Quotes도 가능.
    print("Double Quotes로는 띄어쓰기 포함 가능.")
    cursor.execute(
        '''
        SELECT ProductName AS "My Great Products"
        FROM Products;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)


    # Concatenate Columns

    print("Concatenate Columns")

    cursor.execute(
        '''
        SELECT CustomerName, Address + ', ' + PostalCode + ' ' + City + ', ' + Country AS Address
        FROM Customers;
        '''
    )
    

    # Concatenate Columns (MySQL)

    print("Concatenate Columns (MySQL). sqlite는 안됨.")

    '''
    SELECT CustomerName, CONCAT(Address,', ',PostalCode,', ',City,', ',Country) AS Address
    FROM Customers;
    '''

    # Oracle Example
    '''
    SELECT CustomerName, (Address || ', ' || PostalCode || ' ' || City || ', ' || Country) AS Address
    FROM Customers;
    '''

    #  Alias for Tables

    print("Alias for Tables")

    cursor.execute(
        '''
       SELECT * FROM Customers AS Persons;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    #  More shorter queries with Alias

    print("More shorter queries with Alias")

    cursor.execute(
        '''
        SELECT o.OrderID, o.OrderDate, c.CustomerName
        FROM Customers AS c, Orders AS o
        WHERE c.CustomerName='Around the Horn' AND c.CustomerID=o.CustomerID;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    #  Same but without Alias

    print("Same but without Alias")

    cursor.execute(
        '''
        SELECT Orders.OrderID, Orders.OrderDate, Customers.CustomerName
        FROM Customers, Orders
        WHERE Customers.CustomerName='Around the Horn' AND Customers.CustomerID=Orders.CustomerID;
        '''
    )

    rows = cursor.fetchall()
    for row in rows:
        print(row)

SQL Aliases
(1,)
(2,)
(3,)
(4,)
(5,)
(6,)
(7,)
(8,)
(9,)
(10,)
(11,)
(12,)
(13,)
(14,)
(15,)
(16,)
(17,)
(18,)
(19,)
(20,)
(21,)
(22,)
(23,)
(24,)
(25,)
(26,)
(27,)
(28,)
(29,)
(30,)
(31,)
(32,)
(33,)
(34,)
(35,)
(36,)
(37,)
(38,)
(39,)
(40,)
(41,)
(42,)
(43,)
(44,)
(45,)
(46,)
(47,)
(48,)
(49,)
(50,)
(51,)
(52,)
(53,)
(54,)
(55,)
(56,)
(57,)
(58,)
(59,)
(60,)
(61,)
(62,)
(63,)
(64,)
(65,)
(66,)
(67,)
(68,)
(69,)
(70,)
(71,)
(72,)
(73,)
(74,)
(75,)
(76,)
(77,)
(78,)
(79,)
(80,)
(81,)
(82,)
(83,)
(84,)
(85,)
(86,)
(87,)
(88,)
(89,)
(90,)
(91,)
AS is Optional
(1,)
(2,)
(3,)
(4,)
(5,)
(6,)
(7,)
(8,)
(9,)
(10,)
(11,)
(12,)
(13,)
(14,)
(15,)
(16,)
(17,)
(18,)
(19,)
(20,)
(21,)
(22,)
(23,)
(24,)
(25,)
(26,)
(27,)
(28,)
(29,)
(30,)
(31,)
(32,)
(33,)
(34,)
(35,)
(36,)
(37,)
(38,)
(39,)
(40,)
(41,)
(42,)
(43,)
(44,)
(45,)
(46,)
(47,)
(48,)
(49,)
(50,)
(51,)
(52,)
(53,)
(54,)
(55,)
(56,)
(57,)
(58,)
(59,)
(60,)
(61,)
(62,)
(63,)
(64,)
(65,)
(66,)
(67,)
(68,)
(69,)
(70,)
(71,)
(72,)
(73,)
(74,)
(75,)
(76,)
(77,)
(78,)
(79,)
(80,)
(81,)
(82,)
(83,)
(84,)
(85,)
(86,)
(87,)
(88,)
(89,)
(90,)
(91,)
Alias for Columns
(1, 'Alfreds Futterkiste')
(2, 'Ana Trujillo Emparedados y helados')
(3, 'Antonio Moreno Taquería')
(4, 'Around the Horn')
(5, 'Berglunds snabbköp')
(6, 'Blauer See Delikatessen')
(7, 'Blondel père et fils')
(8, 'Bólido Comidas preparadas')
(9, "Bon app''")
(10, 'Bottom-Dollar Marketse')
(11, "B''s Beverages")
(12, 'Cactus Comidas para llevar')
(13, 'Centro comercial Moctezuma')
(14, 'Chop-suey Chinese')
(15, 'Comércio Mineiro')
(16, 'Consolidated Holdings')
(17, 'Drachenblut Delikatessend')
(18, 'Du monde entier')
(19, 'Eastern Connection')
(20, 'Ernst Handel')
(21, 'Familia Arquibaldo')
(22, 'FISSA Fabrica Inter. Salchichas S.A.')
(23, 'Folies gourmandes')
(24, 'Folk och fä HB')
(25, 'Frankenversand')
(26, 'France restauration')
(27, 'Franchi S.p.A.')
(28, 'Furia Bacalhau e Frutos do Mar')
(29, 'Galería del gastrónomo')
(30, 'Godos Cocina Típica')
(31, 'Gourmet Lanchonetes')
(32, 'Great Lakes Food Market')
(33, 'GROSELLA-Restaurante')
(34, 'Hanari Carnes')
(35, 'HILARIÓN-Abastos')
(36, 'Hungry Coyote Import Store')
(37, 'Hungry Owl All-Night Grocers')
(38, 'Island Trading')
(39, 'Königlich Essen')
(40, "La corne d''abondance")
(41, "La maison d''Asie")
(42, 'Laughing Bacchus Wine Cellars')
(43, 'Lazy K Kountry Store')
(44, 'Lehmanns Marktstand')
(45, "Let''s Stop N Shop")
(46, 'LILA-Supermercado')
(47, 'LINO-Delicateses')
(48, 'Lonesome Pine Restaurant')
(49, 'Magazzini Alimentari Riuniti')
(50, 'Maison Dewey')
(51, 'Mère Paillarde')
(52, 'Morgenstern Gesundkost')
(53, 'North/South')
(54, 'Océano Atlántico Ltda.')
(55, 'Old World Delicatessen')
(56, 'Ottilies Käseladen')
(57, 'Paris spécialités')
(58, 'Pericles Comidas clásicas')
(59, 'Piccolo und mehr')
(60, 'Princesa Isabel Vinhoss')
(61, 'Que Delícia')
(62, 'Queen Cozinha')
(63, 'QUICK-Stop')
(64, 'Rancho grande')
(65, 'Rattlesnake Canyon Grocery')
(66, 'Reggiani Caseifici')
(67, 'Ricardo Adocicados')
(68, 'Richter Supermarkt')
(69, 'Romero y tomillo')
(70, 'Santé Gourmet')
(71, 'Save-a-lot Markets')
(72, 'Seven Seas Imports')
(73, 'Simons bistro')
(74, 'Spécialités du monde')
(75, 'Split Rail Beer & Ale')
(76, 'Suprêmes délices')
(77, 'The Big Cheese')
(78, 'The Cracker Box')
(79, 'Toms Spezialitäten')
(80, 'Tortuga Restaurante')
(81, 'Tradição Hipermercados')
(82, "Trail''s Head Gourmet Provisioners")
(83, 'Vaffeljernet')
(84, 'Victuailles en stock')
(85, 'Vins et alcools Chevalier')
(86, 'Die Wandernde Kuh')
(87, 'Wartian Herkku')
(88, 'Wellington Importadora')
(89, 'White Clover Markets')
(90, 'Wilman Kala')
(91, 'Wolski')
Using Aliases With a Space Character
('Chais',)
('Chang',)
('Aniseed Syrup',)
("Chef Anton's Cajun Seasoning",)
("Chef Anton's Gumbo Mix",)
("Grandma's Boysenberry Spread",)
("Uncle Bob's Organic Dried Pears",)
('Northwoods Cranberry Sauce',)
('Mishi Kobe Niku',)
('Ikura',)
('Queso Cabrales',)
('Queso Manchego La Pastora',)
('Konbu',)
('Tofu',)
('Genen Shouyu',)
('Pavlova',)
('Alice Mutton',)
('Carnarvon Tigers',)
('Teatime Chocolate Biscuits',)
("Sir Rodney's Marmalade",)
("Sir Rodney's Scones",)
("Gustaf's Knäckebröd",)
('Tunnbröd',)
('Guaraná Fantástica',)
('NuNuCa Nuß-Nougat-Creme',)
('Gumbär Gummibärchen',)
('Schoggi Schokolade',)
('Rössle Sauerkraut',)
('Thüringer Rostbratwurst',)
('Nord-Ost Matjeshering',)
('Gorgonzola Telino',)
('Mascarpone Fabioli',)
('Geitost',)
('Sasquatch Ale',)
('Steeleye Stout',)
('Inlagd Sill',)
('Gravad lax',)
('Côte de Blaye',)
('Chartreuse verte',)
('Boston Crab Meat',)
("Jack's New England Clam Chowder",)
('Singaporean Hokkien Fried Mee',)
('Ipoh Coffee',)
('Gula Malacca',)
('Røgede sild',)
('Spegesild',)
('Zaanse koeken',)
('Chocolade',)
('Maxilaku',)
('Valkoinen suklaa',)
('Manjimup Dried Apples',)
('Filo Mix',)
('Perth Pasties',)
('Tourtière',)
('Pâté chinois',)
('Gnocchi di nonna Alice',)
('Ravioli Angelo',)
('Escargots de Bourgogne',)
('Raclette Courdavault',)
('Camembert Pierrot',)
("Sirop d'érable",)
('Tarte au sucre',)
('Vegie-spread',)
('Wimmers gute Semmelknödel',)
('Louisiana Fiery Hot Pepper Sauce',)
('Louisiana Hot Spiced Okra',)
('Laughing Lumberjack Lager',)
('Scottish Longbreads',)
('Gudbrandsdalsost',)
('Outback Lager',)
('Fløtemysost',)
('Mozzarella di Giovanni',)
('Röd Kaviar',)
('Longlife Tofu',)
('Rhönbräu Klosterbier',)
('Lakkalikööri',)
('Original Frankfurter grüne Soße',)
Double Quotes로는 띄어쓰기 포함 가능.
('Chais',)
('Chang',)
('Aniseed Syrup',)
("Chef Anton's Cajun Seasoning",)
("Chef Anton's Gumbo Mix",)
("Grandma's Boysenberry Spread",)
("Uncle Bob's Organic Dried Pears",)
('Northwoods Cranberry Sauce',)
('Mishi Kobe Niku',)
('Ikura',)
('Queso Cabrales',)
('Queso Manchego La Pastora',)
('Konbu',)
('Tofu',)
('Genen Shouyu',)
('Pavlova',)
('Alice Mutton',)
('Carnarvon Tigers',)
('Teatime Chocolate Biscuits',)
("Sir Rodney's Marmalade",)
("Sir Rodney's Scones",)
("Gustaf's Knäckebröd",)
('Tunnbröd',)
('Guaraná Fantástica',)
('NuNuCa Nuß-Nougat-Creme',)
('Gumbär Gummibärchen',)
('Schoggi Schokolade',)
('Rössle Sauerkraut',)
('Thüringer Rostbratwurst',)
('Nord-Ost Matjeshering',)
('Gorgonzola Telino',)
('Mascarpone Fabioli',)
('Geitost',)
('Sasquatch Ale',)
('Steeleye Stout',)
('Inlagd Sill',)
('Gravad lax',)
('Côte de Blaye',)
('Chartreuse verte',)
('Boston Crab Meat',)
("Jack's New England Clam Chowder",)
('Singaporean Hokkien Fried Mee',)
('Ipoh Coffee',)
('Gula Malacca',)
('Røgede sild',)
('Spegesild',)
('Zaanse koeken',)
('Chocolade',)
('Maxilaku',)
('Valkoinen suklaa',)
('Manjimup Dried Apples',)
('Filo Mix',)
('Perth Pasties',)
('Tourtière',)
('Pâté chinois',)
('Gnocchi di nonna Alice',)
('Ravioli Angelo',)
('Escargots de Bourgogne',)
('Raclette Courdavault',)
('Camembert Pierrot',)
("Sirop d'érable",)
('Tarte au sucre',)
('Vegie-spread',)
('Wimmers gute Semmelknödel',)
('Louisiana Fiery Hot Pepper Sauce',)
('Louisiana Hot Spiced Okra',)
('Laughing Lumberjack Lager',)
('Scottish Longbreads',)
('Gudbrandsdalsost',)
('Outback Lager',)
('Fløtemysost',)
('Mozzarella di Giovanni',)
('Röd Kaviar',)
('Longlife Tofu',)
('Rhönbräu Klosterbier',)
('Lakkalikööri',)
('Original Frankfurter grüne Soße',)
Concatenate Columns
Concatenate Columns (MySQL). sqlite는 안됨.
Alias for Tables
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
More shorter queries with Alias
(10355, '1996-11-15', 'Around the Horn')
(10383, '1996-12-16', 'Around the Horn')
Same but without Alias
(10355, '1996-11-15', 'Around the Horn')
(10383, '1996-12-16', 'Around the Horn')

### SQL JOIN

- 두 개 이상의 테이블을 결합하는 데 사용됨.
- 여러 형태의 JOIN이 있음.
- INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL JOIN, CROSS JOIN
- (INNER) JOIN은 두 테이블 간의 key가 일치하는 레코드를 반환함.
- LEFT (OUTER) JOIN은 왼쪽 테이블의 모든 레코드와 오른쪽 테이블의 일치하는 레코드를 반환함.
- RIGHT (OUTER) JOIN은 오른쪽 테이블의 모든 레코드와 왼쪽 테이블의 일치하는 레코드를 반환함.
- FULL (OUTER) JOIN은 두 테이블의 모든 레코드를 반환함.

In [29]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL JOIN
    print("SQL JOIN")

    cursor.execute(
        '''
        SELECT Orders.OrderID, Customers.CustomerName, Orders.OrderDate
        FROM Orders
        INNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL JOIN
조회된 행의 수: 196
(10248, 'Wilman Kala', '1996-07-04')
(10249, 'Tradição Hipermercados', '1996-07-05')
(10250, 'Hanari Carnes', '1996-07-08')
(10251, 'Victuailles en stock', '1996-07-08')
(10252, 'Suprêmes délices', '1996-07-09')
(10253, 'Hanari Carnes', '1996-07-10')
(10254, 'Chop-suey Chinese', '1996-07-11')
(10255, 'Richter Supermarkt', '1996-07-12')
(10256, 'Wellington Importadora', '1996-07-15')
(10257, 'HILARIÓN-Abastos', '1996-07-16')
(10258, 'Ernst Handel', '1996-07-17')
(10259, 'Centro comercial Moctezuma', '1996-07-18')
(10260, 'Old World Delicatessen', '1996-07-19')
(10261, 'Que Delícia', '1996-07-19')
(10262, 'Rattlesnake Canyon Grocery', '1996-07-22')
(10263, 'Ernst Handel', '1996-07-23')
(10264, 'Folk och fä HB', '1996-07-24')
(10265, 'Blondel père et fils', '1996-07-25')
(10266, 'Wartian Herkku', '1996-07-26')
(10267, 'Frankenversand', '1996-07-29')
(10268, 'GROSELLA-Restaurante', '1996-07-30')
(10269, 'White Clover Markets', '1996-07-31')
(10270, 'Wartian Herkku', '1996-08-01')
(10271, 'Split Rail Beer & Ale', '1996-08-01')
(10272, 'Rattlesnake Canyon Grocery', '1996-08-02')
(10273, 'QUICK-Stop', '1996-08-05')
(10274, 'Vins et alcools Chevalier', '1996-08-06')
(10275, 'Magazzini Alimentari Riuniti', '1996-08-07')
(10276, 'Tortuga Restaurante', '1996-08-08')
(10277, 'Morgenstern Gesundkost', '1996-08-09')
(10278, 'Berglunds snabbköp', '1996-08-12')
(10279, 'Lehmanns Marktstand', '1996-08-13')
(10280, 'Berglunds snabbköp', '1996-08-14')
(10281, 'Romero y tomillo', '1996-08-14')
(10282, 'Romero y tomillo', '1996-08-15')
(10283, 'LILA-Supermercado', '1996-08-16')
(10284, 'Lehmanns Marktstand', '1996-08-19')
(10285, 'QUICK-Stop', '1996-08-20')
(10286, 'QUICK-Stop', '1996-08-21')
(10287, 'Ricardo Adocicados', '1996-08-22')
(10288, 'Reggiani Caseifici', '1996-08-23')
(10289, "B''s Beverages", '1996-08-26')
(10290, 'Comércio Mineiro', '1996-08-27')
(10291, 'Que Delícia', '1996-08-27')
(10292, 'Tradição Hipermercados', '1996-08-28')
(10293, 'Tortuga Restaurante', '1996-08-29')
(10294, 'Rattlesnake Canyon Grocery', '1996-08-30')
(10295, 'Vins et alcools Chevalier', '1996-09-02')
(10296, 'LILA-Supermercado', '1996-09-03')
(10297, 'Blondel père et fils', '1996-09-04')
(10298, 'Hungry Owl All-Night Grocers', '1996-09-05')
(10299, 'Ricardo Adocicados', '1996-09-06')
(10300, 'Magazzini Alimentari Riuniti', '1996-09-09')
(10301, 'Die Wandernde Kuh', '1996-09-09')
(10302, 'Suprêmes délices', '1996-09-10')
(10303, 'Godos Cocina Típica', '1996-09-11')
(10304, 'Tortuga Restaurante', '1996-09-12')
(10305, 'Old World Delicatessen', '1996-09-13')
(10306, 'Romero y tomillo', '1996-09-16')
(10307, 'Lonesome Pine Restaurant', '1996-09-17')
(10308, 'Ana Trujillo Emparedados y helados', '1996-09-18')
(10309, 'Hungry Owl All-Night Grocers', '1996-09-19')
(10310, 'The Big Cheese', '1996-09-20')
(10311, 'Du monde entier', '1996-09-20')
(10312, 'Die Wandernde Kuh', '1996-09-23')
(10313, 'QUICK-Stop', '1996-09-24')
(10314, 'Rattlesnake Canyon Grocery', '1996-09-25')
(10315, 'Island Trading', '1996-09-26')
(10316, 'Rattlesnake Canyon Grocery', '1996-09-27')
(10317, 'Lonesome Pine Restaurant', '1996-09-30')
(10318, 'Island Trading', '1996-10-01')
(10319, 'Tortuga Restaurante', '1996-10-02')
(10320, 'Wartian Herkku', '1996-10-03')
(10321, 'Island Trading', '1996-10-03')
(10322, 'Pericles Comidas clásicas', '1996-10-04')
(10323, 'Königlich Essen', '1996-10-07')
(10324, 'Save-a-lot Markets', '1996-10-08')
(10325, 'Königlich Essen', '1996-10-09')
(10326, 'Bólido Comidas preparadas', '1996-10-10')
(10327, 'Folk och fä HB', '1996-10-11')
(10328, 'Furia Bacalhau e Frutos do Mar', '1996-10-14')
(10329, 'Split Rail Beer & Ale', '1996-10-15')
(10330, 'LILA-Supermercado', '1996-10-16')
(10331, "Bon app''", '1996-10-16')
(10332, 'Mère Paillarde', '1996-10-17')
(10333, 'Wartian Herkku', '1996-10-18')
(10334, 'Victuailles en stock', '1996-10-21')
(10335, 'Hungry Owl All-Night Grocers', '1996-10-22')
(10336, 'Princesa Isabel Vinhoss', '1996-10-23')
(10337, 'Frankenversand', '1996-10-24')
(10338, 'Old World Delicatessen', '1996-10-25')
(10339, 'Mère Paillarde', '1996-10-28')
(10340, "Bon app''", '1996-10-29')
(10341, 'Simons bistro', '1996-10-29')
(10342, 'Frankenversand', '1996-10-30')
(10343, 'Lehmanns Marktstand', '1996-10-31')
(10344, 'White Clover Markets', '1996-11-01')
(10345, 'QUICK-Stop', '1996-11-04')
(10346, 'Rattlesnake Canyon Grocery', '1996-11-05')
(10347, 'Familia Arquibaldo', '1996-11-06')
(10348, 'Die Wandernde Kuh', '1996-11-07')
(10349, 'Split Rail Beer & Ale', '1996-11-08')
(10350, "La maison d''Asie", '1996-11-11')
(10351, 'Ernst Handel', '1996-11-11')
(10352, 'Furia Bacalhau e Frutos do Mar', '1996-11-12')
(10353, 'Piccolo und mehr', '1996-11-13')
(10354, 'Pericles Comidas clásicas', '1996-11-14')
(10355, 'Around the Horn', '1996-11-15')
(10356, 'Die Wandernde Kuh', '1996-11-18')
(10357, 'LILA-Supermercado', '1996-11-19')
(10358, "La maison d''Asie", '1996-11-20')
(10359, 'Seven Seas Imports', '1996-11-21')
(10360, 'Blondel père et fils', '1996-11-22')
(10361, 'QUICK-Stop', '1996-11-22')
(10362, "Bon app''", '1996-11-25')
(10363, 'Drachenblut Delikatessend', '1996-11-26')
(10364, 'Eastern Connection', '1996-11-26')
(10365, 'Antonio Moreno Taquería', '1996-11-27')
(10366, 'Galería del gastrónomo', '1996-11-28')
(10367, 'Vaffeljernet', '1996-11-28')
(10368, 'Ernst Handel', '1996-11-29')
(10369, 'Split Rail Beer & Ale', '1996-12-02')
(10370, 'Chop-suey Chinese', '1996-12-03')
(10371, "La maison d''Asie", '1996-12-03')
(10372, 'Queen Cozinha', '1996-12-04')
(10373, 'Hungry Owl All-Night Grocers', '1996-12-05')
(10374, 'Wolski', '1996-12-05')
(10375, 'Hungry Coyote Import Store', '1996-12-06')
(10376, 'Mère Paillarde', '1996-12-09')
(10377, 'Seven Seas Imports', '1996-12-09')
(10378, 'Folk och fä HB', '1996-12-10')
(10379, 'Que Delícia', '1996-12-11')
(10380, 'Hungry Owl All-Night Grocers', '1996-12-12')
(10381, 'LILA-Supermercado', '1996-12-12')
(10382, 'Ernst Handel', '1996-12-13')
(10383, 'Around the Horn', '1996-12-16')
(10384, 'Berglunds snabbköp', '1996-12-16')
(10385, 'Split Rail Beer & Ale', '1996-12-17')
(10386, 'Familia Arquibaldo', '1996-12-18')
(10387, 'Santé Gourmet', '1996-12-18')
(10388, 'Seven Seas Imports', '1996-12-19')
(10389, 'Bottom-Dollar Marketse', '1996-12-20')
(10390, 'Ernst Handel', '1996-12-23')
(10391, 'Drachenblut Delikatessend', '1996-12-23')
(10392, 'Piccolo und mehr', '1996-12-24')
(10393, 'Save-a-lot Markets', '1996-12-25')
(10394, 'Hungry Coyote Import Store', '1996-12-25')
(10395, 'HILARIÓN-Abastos', '1996-12-26')
(10396, 'Frankenversand', '1996-12-27')
(10397, 'Princesa Isabel Vinhoss', '1996-12-27')
(10398, 'Save-a-lot Markets', '1996-12-30')
(10399, 'Vaffeljernet', '1996-12-31')
(10400, 'Eastern Connection', '1997-01-01')
(10401, 'Rattlesnake Canyon Grocery', '1997-01-01')
(10402, 'Ernst Handel', '1997-01-02')
(10403, 'Ernst Handel', '1997-01-03')
(10404, 'Magazzini Alimentari Riuniti', '1997-01-03')
(10405, 'LINO-Delicateses', '1997-01-06')
(10406, 'Queen Cozinha', '1997-01-07')
(10407, 'Ottilies Käseladen', '1997-01-07')
(10408, 'Folies gourmandes', '1997-01-08')
(10409, 'Océano Atlántico Ltda.', '1997-01-09')
(10410, 'Bottom-Dollar Marketse', '1997-01-10')
(10411, 'Bottom-Dollar Marketse', '1997-01-10')
(10412, 'Wartian Herkku', '1997-01-13')
(10413, "La maison d''Asie", '1997-01-14')
(10414, 'Familia Arquibaldo', '1997-01-14')
(10415, 'Hungry Coyote Import Store', '1997-01-15')
(10416, 'Wartian Herkku', '1997-01-16')
(10417, 'Simons bistro', '1997-01-16')
(10418, 'QUICK-Stop', '1997-01-17')
(10419, 'Richter Supermarkt', '1997-01-20')
(10420, 'Wellington Importadora', '1997-01-21')
(10421, 'Que Delícia', '1997-01-21')
(10422, 'Franchi S.p.A.', '1997-01-22')
(10423, 'Gourmet Lanchonetes', '1997-01-23')
(10424, 'Mère Paillarde', '1997-01-23')
(10425, "La maison d''Asie", '1997-01-24')
(10426, 'Galería del gastrónomo', '1997-01-27')
(10427, 'Piccolo und mehr', '1997-01-27')
(10428, 'Reggiani Caseifici', '1997-01-28')
(10429, 'Hungry Owl All-Night Grocers', '1997-01-29')
(10430, 'Ernst Handel', '1997-01-30')
(10431, 'Bottom-Dollar Marketse', '1997-01-30')
(10432, 'Split Rail Beer & Ale', '1997-01-31')
(10433, 'Princesa Isabel Vinhoss', '1997-02-03')
(10434, 'Folk och fä HB', '1997-02-03')
(10435, 'Consolidated Holdings', '1997-02-04')
(10436, 'Blondel père et fils', '1997-02-05')
(10437, 'Wartian Herkku', '1997-02-05')
(10438, 'Toms Spezialitäten', '1997-02-06')
(10439, 'Mère Paillarde', '1997-02-07')
(10440, 'Save-a-lot Markets', '1997-02-10')
(10441, 'Old World Delicatessen', '1997-02-10')
(10442, 'Ernst Handel', '1997-02-11')
(10443, 'Reggiani Caseifici', '1997-02-12')

### SQL INNER JOIN

- 컬럼에 테이블 이름을 지정해주는 것은 좋은 관행이다
- INNER JOIN과 JOIN은 동일하다.
```sql
SELECT column_name(s)
FROM table1
INNER JOIN table2
ON table1.column_name = table2.column_name
```

In [35]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL JOIN
    print("SQL JOIN")

    cursor.execute(
        '''
        SELECT ProductID, ProductName, Products.CategoryID
        FROM Products
        INNER JOIN Categories ON Products.CategoryID = Categories.CategoryID;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # Naming the Columns
    print("Naming the Columns: 컬럼에 테이블 이름을 지정해주는 것은 좋은 관행이다.")

    cursor.execute(
        '''
        SELECT Products.ProductID, Products.ProductName, Categories.CategoryName
        FROM Products
        INNER JOIN Categories ON Products.CategoryID = Categories.CategoryID;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # JOIN or INNER JOIN
    print("JOIN or INNER JOIN")

    cursor.execute(
        '''
        SELECT Products.ProductID, Products.ProductName, Categories.CategoryName
        FROM Products
        JOIN Categories ON Products.CategoryID = Categories.CategoryID;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # JOIN Three Tables
    print("JOIN Three Tables")

    cursor.execute(
        '''
        SELECT Orders.OrderID, Customers.CustomerName, Shippers.ShipperName
        FROM ((Orders
        INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID)
        INNER JOIN Shippers ON Orders.ShipperID = Shippers.ShipperID);
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL JOIN
조회된 행의 수: 77
(1, 'Chais', 1)
(2, 'Chang', 1)
(3, 'Aniseed Syrup', 2)
(4, "Chef Anton's Cajun Seasoning", 2)
(5, "Chef Anton's Gumbo Mix", 2)
(6, "Grandma's Boysenberry Spread", 2)
(7, "Uncle Bob's Organic Dried Pears", 7)
(8, 'Northwoods Cranberry Sauce', 2)
(9, 'Mishi Kobe Niku', 6)
(10, 'Ikura', 8)
(11, 'Queso Cabrales', 4)
(12, 'Queso Manchego La Pastora', 4)
(13, 'Konbu', 8)
(14, 'Tofu', 7)
(15, 'Genen Shouyu', 2)
(16, 'Pavlova', 3)
(17, 'Alice Mutton', 6)
(18, 'Carnarvon Tigers', 8)
(19, 'Teatime Chocolate Biscuits', 3)
(20, "Sir Rodney's Marmalade", 3)
(21, "Sir Rodney's Scones", 3)
(22, "Gustaf's Knäckebröd", 5)
(23, 'Tunnbröd', 5)
(24, 'Guaraná Fantástica', 1)
(25, 'NuNuCa Nuß-Nougat-Creme', 3)
(26, 'Gumbär Gummibärchen', 3)
(27, 'Schoggi Schokolade', 3)
(28, 'Rössle Sauerkraut', 7)
(29, 'Thüringer Rostbratwurst', 6)
(30, 'Nord-Ost Matjeshering', 8)
(31, 'Gorgonzola Telino', 4)
(32, 'Mascarpone Fabioli', 4)
(33, 'Geitost', 4)
(34, 'Sasquatch Ale', 1)
(35, 'Steeleye Stout', 1)
(36, 'Inlagd Sill', 8)
(37, 'Gravad lax', 8)
(38, 'Côte de Blaye', 1)
(39, 'Chartreuse verte', 1)
(40, 'Boston Crab Meat', 8)
(41, "Jack's New England Clam Chowder", 8)
(42, 'Singaporean Hokkien Fried Mee', 5)
(43, 'Ipoh Coffee', 1)
(44, 'Gula Malacca', 2)
(45, 'Røgede sild', 8)
(46, 'Spegesild', 8)
(47, 'Zaanse koeken', 3)
(48, 'Chocolade', 3)
(49, 'Maxilaku', 3)
(50, 'Valkoinen suklaa', 3)
(51, 'Manjimup Dried Apples', 7)
(52, 'Filo Mix', 5)
(53, 'Perth Pasties', 6)
(54, 'Tourtière', 6)
(55, 'Pâté chinois', 6)
(56, 'Gnocchi di nonna Alice', 5)
(57, 'Ravioli Angelo', 5)
(58, 'Escargots de Bourgogne', 8)
(59, 'Raclette Courdavault', 4)
(60, 'Camembert Pierrot', 4)
(61, "Sirop d'érable", 2)
(62, 'Tarte au sucre', 3)
(63, 'Vegie-spread', 2)
(64, 'Wimmers gute Semmelknödel', 5)
(65, 'Louisiana Fiery Hot Pepper Sauce', 2)
(66, 'Louisiana Hot Spiced Okra', 2)
(67, 'Laughing Lumberjack Lager', 1)
(68, 'Scottish Longbreads', 3)
(69, 'Gudbrandsdalsost', 4)
(70, 'Outback Lager', 1)
(71, 'Fløtemysost', 4)
(72, 'Mozzarella di Giovanni', 4)
(73, 'Röd Kaviar', 8)
(74, 'Longlife Tofu', 7)
(75, 'Rhönbräu Klosterbier', 1)
(76, 'Lakkalikööri', 1)
(77, 'Original Frankfurter grüne Soße', 2)
Naming the Columns: 컬럼에 테이블 이름을 지정해주는 것은 좋은 관행이다.
조회된 행의 수: 77
(1, 'Chais', 'Beverages')
(2, 'Chang', 'Beverages')
(3, 'Aniseed Syrup', 'Condiments')
(4, "Chef Anton's Cajun Seasoning", 'Condiments')
(5, "Chef Anton's Gumbo Mix", 'Condiments')
(6, "Grandma's Boysenberry Spread", 'Condiments')
(7, "Uncle Bob's Organic Dried Pears", 'Produce')
(8, 'Northwoods Cranberry Sauce', 'Condiments')
(9, 'Mishi Kobe Niku', 'Meat/Poultry')
(10, 'Ikura', 'Seafood')
(11, 'Queso Cabrales', 'Dairy Products')
(12, 'Queso Manchego La Pastora', 'Dairy Products')
(13, 'Konbu', 'Seafood')
(14, 'Tofu', 'Produce')
(15, 'Genen Shouyu', 'Condiments')
(16, 'Pavlova', 'Confections')
(17, 'Alice Mutton', 'Meat/Poultry')
(18, 'Carnarvon Tigers', 'Seafood')
(19, 'Teatime Chocolate Biscuits', 'Confections')
(20, "Sir Rodney's Marmalade", 'Confections')
(21, "Sir Rodney's Scones", 'Confections')
(22, "Gustaf's Knäckebröd", 'Grains/Cereals')
(23, 'Tunnbröd', 'Grains/Cereals')
(24, 'Guaraná Fantástica', 'Beverages')
(25, 'NuNuCa Nuß-Nougat-Creme', 'Confections')
(26, 'Gumbär Gummibärchen', 'Confections')
(27, 'Schoggi Schokolade', 'Confections')
(28, 'Rössle Sauerkraut', 'Produce')
(29, 'Thüringer Rostbratwurst', 'Meat/Poultry')
(30, 'Nord-Ost Matjeshering', 'Seafood')
(31, 'Gorgonzola Telino', 'Dairy Products')
(32, 'Mascarpone Fabioli', 'Dairy Products')
(33, 'Geitost', 'Dairy Products')
(34, 'Sasquatch Ale', 'Beverages')
(35, 'Steeleye Stout', 'Beverages')
(36, 'Inlagd Sill', 'Seafood')
(37, 'Gravad lax', 'Seafood')
(38, 'Côte de Blaye', 'Beverages')
(39, 'Chartreuse verte', 'Beverages')
(40, 'Boston Crab Meat', 'Seafood')
(41, "Jack's New England Clam Chowder", 'Seafood')
(42, 'Singaporean Hokkien Fried Mee', 'Grains/Cereals')
(43, 'Ipoh Coffee', 'Beverages')
(44, 'Gula Malacca', 'Condiments')
(45, 'Røgede sild', 'Seafood')
(46, 'Spegesild', 'Seafood')
(47, 'Zaanse koeken', 'Confections')
(48, 'Chocolade', 'Confections')
(49, 'Maxilaku', 'Confections')
(50, 'Valkoinen suklaa', 'Confections')
(51, 'Manjimup Dried Apples', 'Produce')
(52, 'Filo Mix', 'Grains/Cereals')
(53, 'Perth Pasties', 'Meat/Poultry')
(54, 'Tourtière', 'Meat/Poultry')
(55, 'Pâté chinois', 'Meat/Poultry')
(56, 'Gnocchi di nonna Alice', 'Grains/Cereals')
(57, 'Ravioli Angelo', 'Grains/Cereals')
(58, 'Escargots de Bourgogne', 'Seafood')
(59, 'Raclette Courdavault', 'Dairy Products')
(60, 'Camembert Pierrot', 'Dairy Products')
(61, "Sirop d'érable", 'Condiments')
(62, 'Tarte au sucre', 'Confections')
(63, 'Vegie-spread', 'Condiments')
(64, 'Wimmers gute Semmelknödel', 'Grains/Cereals')
(65, 'Louisiana Fiery Hot Pepper Sauce', 'Condiments')
(66, 'Louisiana Hot Spiced Okra', 'Condiments')
(67, 'Laughing Lumberjack Lager', 'Beverages')
(68, 'Scottish Longbreads', 'Confections')
(69, 'Gudbrandsdalsost', 'Dairy Products')
(70, 'Outback Lager', 'Beverages')
(71, 'Fløtemysost', 'Dairy Products')
(72, 'Mozzarella di Giovanni', 'Dairy Products')
(73, 'Röd Kaviar', 'Seafood')
(74, 'Longlife Tofu', 'Produce')
(75, 'Rhönbräu Klosterbier', 'Beverages')
(76, 'Lakkalikööri', 'Beverages')
(77, 'Original Frankfurter grüne Soße', 'Condiments')
JOIN or INNER JOIN
조회된 행의 수: 77
(1, 'Chais', 'Beverages')
(2, 'Chang', 'Beverages')
(3, 'Aniseed Syrup', 'Condiments')
(4, "Chef Anton's Cajun Seasoning", 'Condiments')
(5, "Chef Anton's Gumbo Mix", 'Condiments')
(6, "Grandma's Boysenberry Spread", 'Condiments')
(7, "Uncle Bob's Organic Dried Pears", 'Produce')
(8, 'Northwoods Cranberry Sauce', 'Condiments')
(9, 'Mishi Kobe Niku', 'Meat/Poultry')
(10, 'Ikura', 'Seafood')
(11, 'Queso Cabrales', 'Dairy Products')
(12, 'Queso Manchego La Pastora', 'Dairy Products')
(13, 'Konbu', 'Seafood')
(14, 'Tofu', 'Produce')
(15, 'Genen Shouyu', 'Condiments')
(16, 'Pavlova', 'Confections')
(17, 'Alice Mutton', 'Meat/Poultry')
(18, 'Carnarvon Tigers', 'Seafood')
(19, 'Teatime Chocolate Biscuits', 'Confections')
(20, "Sir Rodney's Marmalade", 'Confections')
(21, "Sir Rodney's Scones", 'Confections')
(22, "Gustaf's Knäckebröd", 'Grains/Cereals')
(23, 'Tunnbröd', 'Grains/Cereals')
(24, 'Guaraná Fantástica', 'Beverages')
(25, 'NuNuCa Nuß-Nougat-Creme', 'Confections')
(26, 'Gumbär Gummibärchen', 'Confections')
(27, 'Schoggi Schokolade', 'Confections')
(28, 'Rössle Sauerkraut', 'Produce')
(29, 'Thüringer Rostbratwurst', 'Meat/Poultry')
(30, 'Nord-Ost Matjeshering', 'Seafood')
(31, 'Gorgonzola Telino', 'Dairy Products')
(32, 'Mascarpone Fabioli', 'Dairy Products')
(33, 'Geitost', 'Dairy Products')
(34, 'Sasquatch Ale', 'Beverages')
(35, 'Steeleye Stout', 'Beverages')
(36, 'Inlagd Sill', 'Seafood')
(37, 'Gravad lax', 'Seafood')
(38, 'Côte de Blaye', 'Beverages')
(39, 'Chartreuse verte', 'Beverages')
(40, 'Boston Crab Meat', 'Seafood')
(41, "Jack's New England Clam Chowder", 'Seafood')
(42, 'Singaporean Hokkien Fried Mee', 'Grains/Cereals')
(43, 'Ipoh Coffee', 'Beverages')
(44, 'Gula Malacca', 'Condiments')
(45, 'Røgede sild', 'Seafood')
(46, 'Spegesild', 'Seafood')
(47, 'Zaanse koeken', 'Confections')
(48, 'Chocolade', 'Confections')
(49, 'Maxilaku', 'Confections')
(50, 'Valkoinen suklaa', 'Confections')
(51, 'Manjimup Dried Apples', 'Produce')
(52, 'Filo Mix', 'Grains/Cereals')
(53, 'Perth Pasties', 'Meat/Poultry')
(54, 'Tourtière', 'Meat/Poultry')
(55, 'Pâté chinois', 'Meat/Poultry')
(56, 'Gnocchi di nonna Alice', 'Grains/Cereals')
(57, 'Ravioli Angelo', 'Grains/Cereals')
(58, 'Escargots de Bourgogne', 'Seafood')
(59, 'Raclette Courdavault', 'Dairy Products')
(60, 'Camembert Pierrot', 'Dairy Products')
(61, "Sirop d'érable", 'Condiments')
(62, 'Tarte au sucre', 'Confections')
(63, 'Vegie-spread', 'Condiments')
(64, 'Wimmers gute Semmelknödel', 'Grains/Cereals')
(65, 'Louisiana Fiery Hot Pepper Sauce', 'Condiments')
(66, 'Louisiana Hot Spiced Okra', 'Condiments')
(67, 'Laughing Lumberjack Lager', 'Beverages')
(68, 'Scottish Longbreads', 'Confections')
(69, 'Gudbrandsdalsost', 'Dairy Products')
(70, 'Outback Lager', 'Beverages')
(71, 'Fløtemysost', 'Dairy Products')
(72, 'Mozzarella di Giovanni', 'Dairy Products')
(73, 'Röd Kaviar', 'Seafood')
(74, 'Longlife Tofu', 'Produce')
(75, 'Rhönbräu Klosterbier', 'Beverages')
(76, 'Lakkalikööri', 'Beverages')
(77, 'Original Frankfurter grüne Soße', 'Condiments')
JOIN Three Tables
조회된 행의 수: 196
(10248, 'Wilman Kala', 'Federal Shipping')
(10249, 'Tradição Hipermercados', 'Speedy Express')
(10250, 'Hanari Carnes', 'United Package')
(10251, 'Victuailles en stock', 'Speedy Express')
(10252, 'Suprêmes délices', 'United Package')
(10253, 'Hanari Carnes', 'United Package')
(10254, 'Chop-suey Chinese', 'United Package')
(10255, 'Richter Supermarkt', 'Federal Shipping')
(10256, 'Wellington Importadora', 'United Package')
(10257, 'HILARIÓN-Abastos', 'Federal Shipping')
(10258, 'Ernst Handel', 'Speedy Express')
(10259, 'Centro comercial Moctezuma', 'Federal Shipping')
(10260, 'Old World Delicatessen', 'Speedy Express')
(10261, 'Que Delícia', 'United Package')
(10262, 'Rattlesnake Canyon Grocery', 'Federal Shipping')
(10263, 'Ernst Handel', 'Federal Shipping')
(10264, 'Folk och fä HB', 'Federal Shipping')
(10265, 'Blondel père et fils', 'Speedy Express')
(10266, 'Wartian Herkku', 'Federal Shipping')
(10267, 'Frankenversand', 'Speedy Express')
(10268, 'GROSELLA-Restaurante', 'Federal Shipping')
(10269, 'White Clover Markets', 'Speedy Express')
(10270, 'Wartian Herkku', 'Speedy Express')
(10271, 'Split Rail Beer & Ale', 'United Package')
(10272, 'Rattlesnake Canyon Grocery', 'United Package')
(10273, 'QUICK-Stop', 'Federal Shipping')
(10274, 'Vins et alcools Chevalier', 'Speedy Express')
(10275, 'Magazzini Alimentari Riuniti', 'Speedy Express')
(10276, 'Tortuga Restaurante', 'Federal Shipping')
(10277, 'Morgenstern Gesundkost', 'Federal Shipping')
(10278, 'Berglunds snabbköp', 'United Package')
(10279, 'Lehmanns Marktstand', 'United Package')
(10280, 'Berglunds snabbköp', 'Speedy Express')
(10281, 'Romero y tomillo', 'Speedy Express')
(10282, 'Romero y tomillo', 'Speedy Express')
(10283, 'LILA-Supermercado', 'Federal Shipping')
(10284, 'Lehmanns Marktstand', 'Speedy Express')
(10285, 'QUICK-Stop', 'United Package')
(10286, 'QUICK-Stop', 'Federal Shipping')
(10287, 'Ricardo Adocicados', 'Federal Shipping')
(10288, 'Reggiani Caseifici', 'Speedy Express')
(10289, "B''s Beverages", 'Federal Shipping')
(10290, 'Comércio Mineiro', 'Speedy Express')
(10291, 'Que Delícia', 'United Package')
(10292, 'Tradição Hipermercados', 'United Package')
(10293, 'Tortuga Restaurante', 'Federal Shipping')
(10294, 'Rattlesnake Canyon Grocery', 'United Package')
(10295, 'Vins et alcools Chevalier', 'United Package')
(10296, 'LILA-Supermercado', 'Speedy Express')
(10297, 'Blondel père et fils', 'United Package')
(10298, 'Hungry Owl All-Night Grocers', 'United Package')
(10299, 'Ricardo Adocicados', 'United Package')
(10300, 'Magazzini Alimentari Riuniti', 'United Package')
(10301, 'Die Wandernde Kuh', 'United Package')
(10302, 'Suprêmes délices', 'United Package')
(10303, 'Godos Cocina Típica', 'United Package')
(10304, 'Tortuga Restaurante', 'United Package')
(10305, 'Old World Delicatessen', 'Federal Shipping')
(10306, 'Romero y tomillo', 'Federal Shipping')
(10307, 'Lonesome Pine Restaurant', 'United Package')
(10308, 'Ana Trujillo Emparedados y helados', 'Federal Shipping')
(10309, 'Hungry Owl All-Night Grocers', 'Speedy Express')
(10310, 'The Big Cheese', 'United Package')
(10311, 'Du monde entier', 'Federal Shipping')
(10312, 'Die Wandernde Kuh', 'United Package')
(10313, 'QUICK-Stop', 'United Package')
(10314, 'Rattlesnake Canyon Grocery', 'United Package')
(10315, 'Island Trading', 'United Package')
(10316, 'Rattlesnake Canyon Grocery', 'Federal Shipping')
(10317, 'Lonesome Pine Restaurant', 'Speedy Express')
(10318, 'Island Trading', 'United Package')
(10319, 'Tortuga Restaurante', 'Federal Shipping')
(10320, 'Wartian Herkku', 'Federal Shipping')
(10321, 'Island Trading', 'United Package')
(10322, 'Pericles Comidas clásicas', 'Federal Shipping')
(10323, 'Königlich Essen', 'Speedy Express')
(10324, 'Save-a-lot Markets', 'Speedy Express')
(10325, 'Königlich Essen', 'Federal Shipping')
(10326, 'Bólido Comidas preparadas', 'United Package')
(10327, 'Folk och fä HB', 'Speedy Express')
(10328, 'Furia Bacalhau e Frutos do Mar', 'Federal Shipping')
(10329, 'Split Rail Beer & Ale', 'United Package')
(10330, 'LILA-Supermercado', 'Speedy Express')
(10331, "Bon app''", 'Speedy Express')
(10332, 'Mère Paillarde', 'United Package')
(10333, 'Wartian Herkku', 'Federal Shipping')
(10334, 'Victuailles en stock', 'United Package')
(10335, 'Hungry Owl All-Night Grocers', 'United Package')
(10336, 'Princesa Isabel Vinhoss', 'United Package')
(10337, 'Frankenversand', 'Federal Shipping')
(10338, 'Old World Delicatessen', 'Federal Shipping')
(10339, 'Mère Paillarde', 'United Package')
(10340, "Bon app''", 'Federal Shipping')
(10341, 'Simons bistro', 'Federal Shipping')
(10342, 'Frankenversand', 'United Package')
(10343, 'Lehmanns Marktstand', 'Speedy Express')
(10344, 'White Clover Markets', 'United Package')
(10345, 'QUICK-Stop', 'United Package')
(10346, 'Rattlesnake Canyon Grocery', 'Federal Shipping')
(10347, 'Familia Arquibaldo', 'Federal Shipping')
(10348, 'Die Wandernde Kuh', 'United Package')
(10349, 'Split Rail Beer & Ale', 'Speedy Express')
(10350, "La maison d''Asie", 'United Package')
(10351, 'Ernst Handel', 'Speedy Express')
(10352, 'Furia Bacalhau e Frutos do Mar', 'Federal Shipping')
(10353, 'Piccolo und mehr', 'Federal Shipping')
(10354, 'Pericles Comidas clásicas', 'Federal Shipping')
(10355, 'Around the Horn', 'Speedy Express')
(10356, 'Die Wandernde Kuh', 'United Package')
(10357, 'LILA-Supermercado', 'Federal Shipping')
(10358, "La maison d''Asie", 'Speedy Express')
(10359, 'Seven Seas Imports', 'Federal Shipping')
(10360, 'Blondel père et fils', 'Federal Shipping')
(10361, 'QUICK-Stop', 'United Package')
(10362, "Bon app''", 'Speedy Express')
(10363, 'Drachenblut Delikatessend', 'Federal Shipping')
(10364, 'Eastern Connection', 'Speedy Express')
(10365, 'Antonio Moreno Taquería', 'United Package')
(10366, 'Galería del gastrónomo', 'United Package')
(10367, 'Vaffeljernet', 'Federal Shipping')
(10368, 'Ernst Handel', 'United Package')
(10369, 'Split Rail Beer & Ale', 'United Package')
(10370, 'Chop-suey Chinese', 'United Package')
(10371, "La maison d''Asie", 'Speedy Express')
(10372, 'Queen Cozinha', 'United Package')
(10373, 'Hungry Owl All-Night Grocers', 'Federal Shipping')
(10374, 'Wolski', 'Federal Shipping')
(10375, 'Hungry Coyote Import Store', 'United Package')
(10376, 'Mère Paillarde', 'United Package')
(10377, 'Seven Seas Imports', 'Federal Shipping')
(10378, 'Folk och fä HB', 'Federal Shipping')
(10379, 'Que Delícia', 'Speedy Express')
(10380, 'Hungry Owl All-Night Grocers', 'Federal Shipping')
(10381, 'LILA-Supermercado', 'Federal Shipping')
(10382, 'Ernst Handel', 'Speedy Express')
(10383, 'Around the Horn', 'Federal Shipping')
(10384, 'Berglunds snabbköp', 'Federal Shipping')
(10385, 'Split Rail Beer & Ale', 'United Package')
(10386, 'Familia Arquibaldo', 'Federal Shipping')
(10387, 'Santé Gourmet', 'United Package')
(10388, 'Seven Seas Imports', 'Speedy Express')
(10389, 'Bottom-Dollar Marketse', 'United Package')
(10390, 'Ernst Handel', 'Speedy Express')
(10391, 'Drachenblut Delikatessend', 'Federal Shipping')
(10392, 'Piccolo und mehr', 'Federal Shipping')
(10393, 'Save-a-lot Markets', 'Federal Shipping')
(10394, 'Hungry Coyote Import Store', 'Federal Shipping')
(10395, 'HILARIÓN-Abastos', 'Speedy Express')
(10396, 'Frankenversand', 'Federal Shipping')
(10397, 'Princesa Isabel Vinhoss', 'Speedy Express')
(10398, 'Save-a-lot Markets', 'Federal Shipping')
(10399, 'Vaffeljernet', 'Federal Shipping')
(10400, 'Eastern Connection', 'Federal Shipping')
(10401, 'Rattlesnake Canyon Grocery', 'Speedy Express')
(10402, 'Ernst Handel', 'United Package')
(10403, 'Ernst Handel', 'Federal Shipping')
(10404, 'Magazzini Alimentari Riuniti', 'Speedy Express')
(10405, 'LINO-Delicateses', 'Speedy Express')
(10406, 'Queen Cozinha', 'Speedy Express')
(10407, 'Ottilies Käseladen', 'United Package')
(10408, 'Folies gourmandes', 'Speedy Express')
(10409, 'Océano Atlántico Ltda.', 'Speedy Express')
(10410, 'Bottom-Dollar Marketse', 'Federal Shipping')
(10411, 'Bottom-Dollar Marketse', 'Federal Shipping')
(10412, 'Wartian Herkku', 'United Package')
(10413, "La maison d''Asie", 'United Package')
(10414, 'Familia Arquibaldo', 'Federal Shipping')
(10415, 'Hungry Coyote Import Store', 'Speedy Express')
(10416, 'Wartian Herkku', 'Federal Shipping')
(10417, 'Simons bistro', 'Federal Shipping')
(10418, 'QUICK-Stop', 'Speedy Express')
(10419, 'Richter Supermarkt', 'United Package')
(10420, 'Wellington Importadora', 'Speedy Express')
(10421, 'Que Delícia', 'Speedy Express')
(10422, 'Franchi S.p.A.', 'Speedy Express')
(10423, 'Gourmet Lanchonetes', 'Federal Shipping')
(10424, 'Mère Paillarde', 'United Package')
(10425, "La maison d''Asie", 'United Package')
(10426, 'Galería del gastrónomo', 'Speedy Express')
(10427, 'Piccolo und mehr', 'United Package')
(10428, 'Reggiani Caseifici', 'Speedy Express')
(10429, 'Hungry Owl All-Night Grocers', 'United Package')
(10430, 'Ernst Handel', 'Speedy Express')
(10431, 'Bottom-Dollar Marketse', 'United Package')
(10432, 'Split Rail Beer & Ale', 'United Package')
(10433, 'Princesa Isabel Vinhoss', 'Federal Shipping')
(10434, 'Folk och fä HB', 'United Package')
(10435, 'Consolidated Holdings', 'United Package')
(10436, 'Blondel père et fils', 'United Package')
(10437, 'Wartian Herkku', 'Speedy Express')
(10438, 'Toms Spezialitäten', 'United Package')
(10439, 'Mère Paillarde', 'Federal Shipping')
(10440, 'Save-a-lot Markets', 'United Package')
(10441, 'Old World Delicatessen', 'United Package')
(10442, 'Ernst Handel', 'United Package')
(10443, 'Reggiani Caseifici', 'Speedy Express')

### SQL LEFT JOIN Keyword

- 왼쪽 테이블의 모든 레코드와 오른쪽 테이블의 일치하는 레코드를 반환함.

```sql
SELECT column_name(s)
FROM table1
LEFT JOIN table2
ON table1.column_name = table2.column_name;
```

In [38]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL LEFT JOIN Example
    print("SQL LEFT JOIN Example")

    cursor.execute(
        '''
        SELECT c.CustomerName, o.OrderID FROM Customers c
        LEFT JOIN ORDERS o ON c.CustomerID = o.CustomerID
        ORDER BY c.CustomerName;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL LEFT JOIN Example
조회된 행의 수: 213
('Alfreds Futterkiste', None)
('Ana Trujillo Emparedados y helados', 10308)
('Antonio Moreno Taquería', 10365)
('Around the Horn', 10355)
('Around the Horn', 10383)
("B''s Beverages", 10289)
('Berglunds snabbköp', 10278)
('Berglunds snabbköp', 10280)
('Berglunds snabbköp', 10384)
('Blauer See Delikatessen', None)
('Blondel père et fils', 10265)
('Blondel père et fils', 10297)
('Blondel père et fils', 10360)
('Blondel père et fils', 10436)
("Bon app''", 10331)
("Bon app''", 10340)
("Bon app''", 10362)
('Bottom-Dollar Marketse', 10389)
('Bottom-Dollar Marketse', 10410)
('Bottom-Dollar Marketse', 10411)
('Bottom-Dollar Marketse', 10431)
('Bólido Comidas preparadas', 10326)
('Cactus Comidas para llevar', None)
('Centro comercial Moctezuma', 10259)
('Chop-suey Chinese', 10254)
('Chop-suey Chinese', 10370)
('Comércio Mineiro', 10290)
('Consolidated Holdings', 10435)
('Die Wandernde Kuh', 10301)
('Die Wandernde Kuh', 10312)
('Die Wandernde Kuh', 10348)
('Die Wandernde Kuh', 10356)
('Drachenblut Delikatessend', 10363)
('Drachenblut Delikatessend', 10391)
('Du monde entier', 10311)
('Eastern Connection', 10364)
('Eastern Connection', 10400)
('Ernst Handel', 10258)
('Ernst Handel', 10263)
('Ernst Handel', 10351)
('Ernst Handel', 10368)
('Ernst Handel', 10382)
('Ernst Handel', 10390)
('Ernst Handel', 10402)
('Ernst Handel', 10403)
('Ernst Handel', 10430)
('Ernst Handel', 10442)
('FISSA Fabrica Inter. Salchichas S.A.', None)
('Familia Arquibaldo', 10347)
('Familia Arquibaldo', 10386)
('Familia Arquibaldo', 10414)
('Folies gourmandes', 10408)
('Folk och fä HB', 10264)
('Folk och fä HB', 10327)
('Folk och fä HB', 10378)
('Folk och fä HB', 10434)
('France restauration', None)
('Franchi S.p.A.', 10422)
('Frankenversand', 10267)
('Frankenversand', 10337)
('Frankenversand', 10342)
('Frankenversand', 10396)
('Furia Bacalhau e Frutos do Mar', 10328)
('Furia Bacalhau e Frutos do Mar', 10352)
('GROSELLA-Restaurante', 10268)
('Galería del gastrónomo', 10366)
('Galería del gastrónomo', 10426)
('Godos Cocina Típica', 10303)
('Gourmet Lanchonetes', 10423)
('Great Lakes Food Market', None)
('HILARIÓN-Abastos', 10257)
('HILARIÓN-Abastos', 10395)
('Hanari Carnes', 10250)
('Hanari Carnes', 10253)
('Hungry Coyote Import Store', 10375)
('Hungry Coyote Import Store', 10394)
('Hungry Coyote Import Store', 10415)
('Hungry Owl All-Night Grocers', 10298)
('Hungry Owl All-Night Grocers', 10309)
('Hungry Owl All-Night Grocers', 10335)
('Hungry Owl All-Night Grocers', 10373)
('Hungry Owl All-Night Grocers', 10380)
('Hungry Owl All-Night Grocers', 10429)
('Island Trading', 10315)
('Island Trading', 10318)
('Island Trading', 10321)
('Königlich Essen', 10323)
('Königlich Essen', 10325)
('LILA-Supermercado', 10283)
('LILA-Supermercado', 10296)
('LILA-Supermercado', 10330)
('LILA-Supermercado', 10357)
('LILA-Supermercado', 10381)
('LINO-Delicateses', 10405)
("La corne d''abondance", None)
("La maison d''Asie", 10350)
("La maison d''Asie", 10358)
("La maison d''Asie", 10371)
("La maison d''Asie", 10413)
("La maison d''Asie", 10425)
('Laughing Bacchus Wine Cellars', None)
('Lazy K Kountry Store', None)
('Lehmanns Marktstand', 10279)
('Lehmanns Marktstand', 10284)
('Lehmanns Marktstand', 10343)
("Let''s Stop N Shop", None)
('Lonesome Pine Restaurant', 10307)
('Lonesome Pine Restaurant', 10317)
('Magazzini Alimentari Riuniti', 10275)
('Magazzini Alimentari Riuniti', 10300)
('Magazzini Alimentari Riuniti', 10404)
('Maison Dewey', None)
('Morgenstern Gesundkost', 10277)
('Mère Paillarde', 10332)
('Mère Paillarde', 10339)
('Mère Paillarde', 10376)
('Mère Paillarde', 10424)
('Mère Paillarde', 10439)
('North/South', None)
('Océano Atlántico Ltda.', 10409)
('Old World Delicatessen', 10260)
('Old World Delicatessen', 10305)
('Old World Delicatessen', 10338)
('Old World Delicatessen', 10441)
('Ottilies Käseladen', 10407)
('Paris spécialités', None)
('Pericles Comidas clásicas', 10322)
('Pericles Comidas clásicas', 10354)
('Piccolo und mehr', 10353)
('Piccolo und mehr', 10392)
('Piccolo und mehr', 10427)
('Princesa Isabel Vinhoss', 10336)
('Princesa Isabel Vinhoss', 10397)
('Princesa Isabel Vinhoss', 10433)
('QUICK-Stop', 10273)
('QUICK-Stop', 10285)
('QUICK-Stop', 10286)
('QUICK-Stop', 10313)
('QUICK-Stop', 10345)
('QUICK-Stop', 10361)
('QUICK-Stop', 10418)
('Que Delícia', 10261)
('Que Delícia', 10291)
('Que Delícia', 10379)
('Que Delícia', 10421)
('Queen Cozinha', 10372)
('Queen Cozinha', 10406)
('Rancho grande', None)
('Rattlesnake Canyon Grocery', 10262)
('Rattlesnake Canyon Grocery', 10272)
('Rattlesnake Canyon Grocery', 10294)
('Rattlesnake Canyon Grocery', 10314)
('Rattlesnake Canyon Grocery', 10316)
('Rattlesnake Canyon Grocery', 10346)
('Rattlesnake Canyon Grocery', 10401)
('Reggiani Caseifici', 10288)
('Reggiani Caseifici', 10428)
('Reggiani Caseifici', 10443)
('Ricardo Adocicados', 10287)
('Ricardo Adocicados', 10299)
('Richter Supermarkt', 10255)
('Richter Supermarkt', 10419)
('Romero y tomillo', 10281)
('Romero y tomillo', 10282)
('Romero y tomillo', 10306)
('Santé Gourmet', 10387)
('Save-a-lot Markets', 10324)
('Save-a-lot Markets', 10393)
('Save-a-lot Markets', 10398)
('Save-a-lot Markets', 10440)
('Seven Seas Imports', 10359)
('Seven Seas Imports', 10377)
('Seven Seas Imports', 10388)
('Simons bistro', 10341)
('Simons bistro', 10417)
('Split Rail Beer & Ale', 10271)
('Split Rail Beer & Ale', 10329)
('Split Rail Beer & Ale', 10349)
('Split Rail Beer & Ale', 10369)
('Split Rail Beer & Ale', 10385)
('Split Rail Beer & Ale', 10432)
('Spécialités du monde', None)
('Suprêmes délices', 10252)
('Suprêmes délices', 10302)
('The Big Cheese', 10310)
('The Cracker Box', None)
('Toms Spezialitäten', 10438)
('Tortuga Restaurante', 10276)
('Tortuga Restaurante', 10293)
('Tortuga Restaurante', 10304)
('Tortuga Restaurante', 10319)
('Tradição Hipermercados', 10249)
('Tradição Hipermercados', 10292)
("Trail''s Head Gourmet Provisioners", None)
('Vaffeljernet', 10367)
('Vaffeljernet', 10399)
('Victuailles en stock', 10251)
('Victuailles en stock', 10334)
('Vins et alcools Chevalier', 10274)
('Vins et alcools Chevalier', 10295)
('Wartian Herkku', 10266)
('Wartian Herkku', 10270)
('Wartian Herkku', 10320)
('Wartian Herkku', 10333)
('Wartian Herkku', 10412)
('Wartian Herkku', 10416)
('Wartian Herkku', 10437)
('Wellington Importadora', 10256)
('Wellington Importadora', 10420)
('White Clover Markets', 10269)
('White Clover Markets', 10344)
('Wilman Kala', 10248)
('Wolski', 10374)

### SQL RIGHT JOIN Keyword

- 오른쪽 테이블의 모든 레코드와 왼쪽 테이블의 일치하는 레코드를 반환함.

```sql
SELECT column_name(s)
FROM table1
RIGHT JOIN table2
ON table1.column_name = table2.column_name;
```

In [40]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL RIGHT JOIN Example
    print("SQL RIGHT JOIN Example")

    cursor.execute(
        '''
        SELECT e.LastName + ', ' + e.FirstName AS ename, o.OrderID
        FROM Employees e
        RIGHT JOIN Orders o ON e.EmployeeID = o.EmployeeID
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL RIGHT JOIN Example
조회된 행의 수: 196
(0, 10258)
(0, 10270)
(0, 10275)
(0, 10285)
(0, 10292)
(0, 10293)
(0, 10304)
(0, 10306)
(0, 10311)
(0, 10314)
(0, 10316)
(0, 10325)
(0, 10340)
(0, 10351)
(0, 10357)
(0, 10361)
(0, 10364)
(0, 10371)
(0, 10374)
(0, 10376)
(0, 10377)
(0, 10385)
(0, 10387)
(0, 10393)
(0, 10394)
(0, 10396)
(0, 10400)
(0, 10401)
(0, 10405)
(0, 10265)
(0, 10277)
(0, 10280)
(0, 10295)
(0, 10300)
(0, 10307)
(0, 10312)
(0, 10313)
(0, 10327)
(0, 10339)
(0, 10345)
(0, 10368)
(0, 10379)
(0, 10388)
(0, 10392)
(0, 10398)
(0, 10404)
(0, 10407)
(0, 10414)
(0, 10422)
(0, 10251)
(0, 10253)
(0, 10256)
(0, 10266)
(0, 10273)
(0, 10283)
(0, 10309)
(0, 10321)
(0, 10330)
(0, 10332)
(0, 10346)
(0, 10352)
(0, 10362)
(0, 10365)
(0, 10375)
(0, 10381)
(0, 10384)
(0, 10391)
(0, 10409)
(0, 10410)
(0, 10413)
(0, 10415)
(0, 10420)
(0, 10429)
(0, 10432)
(0, 10433)
(0, 10434)
(0, 10436)
(0, 10438)
(0, 10441)
(0, 10442)
(0, 10250)
(0, 10252)
(0, 10257)
(0, 10259)
(0, 10260)
(0, 10261)
(0, 10267)
(0, 10281)
(0, 10282)
(0, 10284)
(0, 10288)
(0, 10294)
(0, 10299)
(0, 10302)
(0, 10315)
(0, 10323)
(0, 10326)
(0, 10328)
(0, 10329)
(0, 10337)
(0, 10338)
(0, 10342)
(0, 10343)
(0, 10344)
(0, 10347)
(0, 10348)
(0, 10360)
(0, 10363)
(0, 10373)
(0, 10382)
(0, 10389)
(0, 10403)
(0, 10417)
(0, 10418)
(0, 10419)
(0, 10426)
(0, 10427)
(0, 10430)
(0, 10431)
(0, 10440)
(0, 10248)
(0, 10254)
(0, 10269)
(0, 10297)
(0, 10320)
(0, 10333)
(0, 10358)
(0, 10359)
(0, 10372)
(0, 10378)
(0, 10397)
(0, 10249)
(0, 10264)
(0, 10271)
(0, 10272)
(0, 10274)
(0, 10291)
(0, 10296)
(0, 10298)
(0, 10317)
(0, 10350)
(0, 10355)
(0, 10356)
(0, 10370)
(0, 10390)
(0, 10395)
(0, 10423)
(0, 10425)
(0, 10439)
(0, 10289)
(0, 10303)
(0, 10308)
(0, 10319)
(0, 10322)
(0, 10335)
(0, 10336)
(0, 10341)
(0, 10349)
(0, 10353)
(0, 10367)
(0, 10406)
(0, 10424)
(0, 10428)
(0, 10262)
(0, 10268)
(0, 10276)
(0, 10278)
(0, 10279)
(0, 10286)
(0, 10287)
(0, 10290)
(0, 10301)
(0, 10305)
(0, 10310)
(0, 10318)
(0, 10334)
(0, 10354)
(0, 10366)
(0, 10369)
(0, 10380)
(0, 10383)
(0, 10399)
(0, 10402)
(0, 10408)
(0, 10412)
(0, 10416)
(0, 10421)
(0, 10435)
(0, 10437)
(0, 10443)
(0, 10255)
(0, 10263)
(0, 10324)
(0, 10331)
(0, 10386)
(0, 10411)

### SQL FULL OUTER JOIN Keyword

- 오른쪽 테이블의 모든 레코드와 왼쪽 테이블의 모든 레코드를 key가 일치하든 일치하지 않든 반환함.

```sql
SELECT column_name(s)
FROM table1
FULL (OUTER) JOIN table2
ON table1.column_name = table2.column_name;
```

In [41]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL FULL OUTER JOIN Example
    print("SQL FULL OUTER JOIN Example")

    cursor.execute(
        '''
        SELECT c.CustomerName, o.OrderID
        FROM Customers c
        FULL OUTER JOIN Orders o ON c.CustomerID = o.CustomerID
        ORDER BY c.CustomerName;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL FULL OUTER JOIN Example
조회된 행의 수: 213
('Alfreds Futterkiste', None)
('Ana Trujillo Emparedados y helados', 10308)
('Antonio Moreno Taquería', 10365)
('Around the Horn', 10355)
('Around the Horn', 10383)
("B''s Beverages", 10289)
('Berglunds snabbköp', 10278)
('Berglunds snabbköp', 10280)
('Berglunds snabbköp', 10384)
('Blauer See Delikatessen', None)
('Blondel père et fils', 10265)
('Blondel père et fils', 10297)
('Blondel père et fils', 10360)
('Blondel père et fils', 10436)
("Bon app''", 10331)
("Bon app''", 10340)
("Bon app''", 10362)
('Bottom-Dollar Marketse', 10389)
('Bottom-Dollar Marketse', 10410)
('Bottom-Dollar Marketse', 10411)
('Bottom-Dollar Marketse', 10431)
('Bólido Comidas preparadas', 10326)
('Cactus Comidas para llevar', None)
('Centro comercial Moctezuma', 10259)
('Chop-suey Chinese', 10254)
('Chop-suey Chinese', 10370)
('Comércio Mineiro', 10290)
('Consolidated Holdings', 10435)
('Die Wandernde Kuh', 10301)
('Die Wandernde Kuh', 10312)
('Die Wandernde Kuh', 10348)
('Die Wandernde Kuh', 10356)
('Drachenblut Delikatessend', 10363)
('Drachenblut Delikatessend', 10391)
('Du monde entier', 10311)
('Eastern Connection', 10364)
('Eastern Connection', 10400)
('Ernst Handel', 10258)
('Ernst Handel', 10263)
('Ernst Handel', 10351)
('Ernst Handel', 10368)
('Ernst Handel', 10382)
('Ernst Handel', 10390)
('Ernst Handel', 10402)
('Ernst Handel', 10403)
('Ernst Handel', 10430)
('Ernst Handel', 10442)
('FISSA Fabrica Inter. Salchichas S.A.', None)
('Familia Arquibaldo', 10347)
('Familia Arquibaldo', 10386)
('Familia Arquibaldo', 10414)
('Folies gourmandes', 10408)
('Folk och fä HB', 10264)
('Folk och fä HB', 10327)
('Folk och fä HB', 10378)
('Folk och fä HB', 10434)
('France restauration', None)
('Franchi S.p.A.', 10422)
('Frankenversand', 10267)
('Frankenversand', 10337)
('Frankenversand', 10342)
('Frankenversand', 10396)
('Furia Bacalhau e Frutos do Mar', 10328)
('Furia Bacalhau e Frutos do Mar', 10352)
('GROSELLA-Restaurante', 10268)
('Galería del gastrónomo', 10366)
('Galería del gastrónomo', 10426)
('Godos Cocina Típica', 10303)
('Gourmet Lanchonetes', 10423)
('Great Lakes Food Market', None)
('HILARIÓN-Abastos', 10257)
('HILARIÓN-Abastos', 10395)
('Hanari Carnes', 10250)
('Hanari Carnes', 10253)
('Hungry Coyote Import Store', 10375)
('Hungry Coyote Import Store', 10394)
('Hungry Coyote Import Store', 10415)
('Hungry Owl All-Night Grocers', 10298)
('Hungry Owl All-Night Grocers', 10309)
('Hungry Owl All-Night Grocers', 10335)
('Hungry Owl All-Night Grocers', 10373)
('Hungry Owl All-Night Grocers', 10380)
('Hungry Owl All-Night Grocers', 10429)
('Island Trading', 10315)
('Island Trading', 10318)
('Island Trading', 10321)
('Königlich Essen', 10323)
('Königlich Essen', 10325)
('LILA-Supermercado', 10283)
('LILA-Supermercado', 10296)
('LILA-Supermercado', 10330)
('LILA-Supermercado', 10357)
('LILA-Supermercado', 10381)
('LINO-Delicateses', 10405)
("La corne d''abondance", None)
("La maison d''Asie", 10350)
("La maison d''Asie", 10358)
("La maison d''Asie", 10371)
("La maison d''Asie", 10413)
("La maison d''Asie", 10425)
('Laughing Bacchus Wine Cellars', None)
('Lazy K Kountry Store', None)
('Lehmanns Marktstand', 10279)
('Lehmanns Marktstand', 10284)
('Lehmanns Marktstand', 10343)
("Let''s Stop N Shop", None)
('Lonesome Pine Restaurant', 10307)
('Lonesome Pine Restaurant', 10317)
('Magazzini Alimentari Riuniti', 10275)
('Magazzini Alimentari Riuniti', 10300)
('Magazzini Alimentari Riuniti', 10404)
('Maison Dewey', None)
('Morgenstern Gesundkost', 10277)
('Mère Paillarde', 10332)
('Mère Paillarde', 10339)
('Mère Paillarde', 10376)
('Mère Paillarde', 10424)
('Mère Paillarde', 10439)
('North/South', None)
('Océano Atlántico Ltda.', 10409)
('Old World Delicatessen', 10260)
('Old World Delicatessen', 10305)
('Old World Delicatessen', 10338)
('Old World Delicatessen', 10441)
('Ottilies Käseladen', 10407)
('Paris spécialités', None)
('Pericles Comidas clásicas', 10322)
('Pericles Comidas clásicas', 10354)
('Piccolo und mehr', 10353)
('Piccolo und mehr', 10392)
('Piccolo und mehr', 10427)
('Princesa Isabel Vinhoss', 10336)
('Princesa Isabel Vinhoss', 10397)
('Princesa Isabel Vinhoss', 10433)
('QUICK-Stop', 10273)
('QUICK-Stop', 10285)
('QUICK-Stop', 10286)
('QUICK-Stop', 10313)
('QUICK-Stop', 10345)
('QUICK-Stop', 10361)
('QUICK-Stop', 10418)
('Que Delícia', 10261)
('Que Delícia', 10291)
('Que Delícia', 10379)
('Que Delícia', 10421)
('Queen Cozinha', 10372)
('Queen Cozinha', 10406)
('Rancho grande', None)
('Rattlesnake Canyon Grocery', 10262)
('Rattlesnake Canyon Grocery', 10272)
('Rattlesnake Canyon Grocery', 10294)
('Rattlesnake Canyon Grocery', 10314)
('Rattlesnake Canyon Grocery', 10316)
('Rattlesnake Canyon Grocery', 10346)
('Rattlesnake Canyon Grocery', 10401)
('Reggiani Caseifici', 10288)
('Reggiani Caseifici', 10428)
('Reggiani Caseifici', 10443)
('Ricardo Adocicados', 10287)
('Ricardo Adocicados', 10299)
('Richter Supermarkt', 10255)
('Richter Supermarkt', 10419)
('Romero y tomillo', 10281)
('Romero y tomillo', 10282)
('Romero y tomillo', 10306)
('Santé Gourmet', 10387)
('Save-a-lot Markets', 10324)
('Save-a-lot Markets', 10393)
('Save-a-lot Markets', 10398)
('Save-a-lot Markets', 10440)
('Seven Seas Imports', 10359)
('Seven Seas Imports', 10377)
('Seven Seas Imports', 10388)
('Simons bistro', 10341)
('Simons bistro', 10417)
('Split Rail Beer & Ale', 10271)
('Split Rail Beer & Ale', 10329)
('Split Rail Beer & Ale', 10349)
('Split Rail Beer & Ale', 10369)
('Split Rail Beer & Ale', 10385)
('Split Rail Beer & Ale', 10432)
('Spécialités du monde', None)
('Suprêmes délices', 10252)
('Suprêmes délices', 10302)
('The Big Cheese', 10310)
('The Cracker Box', None)
('Toms Spezialitäten', 10438)
('Tortuga Restaurante', 10276)
('Tortuga Restaurante', 10293)
('Tortuga Restaurante', 10304)
('Tortuga Restaurante', 10319)
('Tradição Hipermercados', 10249)
('Tradição Hipermercados', 10292)
("Trail''s Head Gourmet Provisioners", None)
('Vaffeljernet', 10367)
('Vaffeljernet', 10399)
('Victuailles en stock', 10251)
('Victuailles en stock', 10334)
('Vins et alcools Chevalier', 10274)
('Vins et alcools Chevalier', 10295)
('Wartian Herkku', 10266)
('Wartian Herkku', 10270)
('Wartian Herkku', 10320)
('Wartian Herkku', 10333)
('Wartian Herkku', 10412)
('Wartian Herkku', 10416)
('Wartian Herkku', 10437)
('Wellington Importadora', 10256)
('Wellington Importadora', 10420)
('White Clover Markets', 10269)
('White Clover Markets', 10344)
('Wilman Kala', 10248)
('Wolski', 10374)

### SQL SELF JOIN
- 테이블을 자신 테이블과 결합하는 데 사용됨.
- 테이블 별칭을 사용하여 자신 테이블을 참조함.

```sql
SELECT column_name(s)
FROM table1 T1, table1 T2
WHERE condition;
```

In [42]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL FULL OUTER JOIN Example
    print("SQL FULL OUTER JOIN Example")

    cursor.execute(
        '''
        SELECT a.CustomerName AS CustomerName1, b.CustomerName AS CustomerName2, a.City
        FROM Customers a, Customers b
        WHERE a.CustomerID <> b.CustomerID
        AND a.City = b.City
        ORDER BY a.City;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL FULL OUTER JOIN Example
조회된 행의 수: 88
('Cactus Comidas para llevar', 'Océano Atlántico Ltda.', 'Buenos Aires')
('Cactus Comidas para llevar', 'Rancho grande', 'Buenos Aires')
('Océano Atlántico Ltda.', 'Cactus Comidas para llevar', 'Buenos Aires')
('Océano Atlántico Ltda.', 'Rancho grande', 'Buenos Aires')
('Rancho grande', 'Cactus Comidas para llevar', 'Buenos Aires')
('Rancho grande', 'Océano Atlántico Ltda.', 'Buenos Aires')
('Furia Bacalhau e Frutos do Mar', 'Princesa Isabel Vinhoss', 'Lisboa')
('Princesa Isabel Vinhoss', 'Furia Bacalhau e Frutos do Mar', 'Lisboa')
('Around the Horn', "B''s Beverages", 'London')
('Around the Horn', 'Consolidated Holdings', 'London')
('Around the Horn', 'Eastern Connection', 'London')
('Around the Horn', 'North/South', 'London')
('Around the Horn', 'Seven Seas Imports', 'London')
("B''s Beverages", 'Around the Horn', 'London')
("B''s Beverages", 'Consolidated Holdings', 'London')
("B''s Beverages", 'Eastern Connection', 'London')
("B''s Beverages", 'North/South', 'London')
("B''s Beverages", 'Seven Seas Imports', 'London')
('Consolidated Holdings', 'Around the Horn', 'London')
('Consolidated Holdings', "B''s Beverages", 'London')
('Consolidated Holdings', 'Eastern Connection', 'London')
('Consolidated Holdings', 'North/South', 'London')
('Consolidated Holdings', 'Seven Seas Imports', 'London')
('Eastern Connection', 'Around the Horn', 'London')
('Eastern Connection', "B''s Beverages", 'London')
('Eastern Connection', 'Consolidated Holdings', 'London')
('Eastern Connection', 'North/South', 'London')
('Eastern Connection', 'Seven Seas Imports', 'London')
('North/South', 'Around the Horn', 'London')
('North/South', "B''s Beverages", 'London')
('North/South', 'Consolidated Holdings', 'London')
('North/South', 'Eastern Connection', 'London')
('North/South', 'Seven Seas Imports', 'London')
('Seven Seas Imports', 'Around the Horn', 'London')
('Seven Seas Imports', "B''s Beverages", 'London')
('Seven Seas Imports', 'Consolidated Holdings', 'London')
('Seven Seas Imports', 'Eastern Connection', 'London')
('Seven Seas Imports', 'North/South', 'London')
('Bólido Comidas preparadas', 'FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Bólido Comidas preparadas', 'Romero y tomillo', 'Madrid')
('FISSA Fabrica Inter. Salchichas S.A.', 'Bólido Comidas preparadas', 'Madrid')
('FISSA Fabrica Inter. Salchichas S.A.', 'Romero y tomillo', 'Madrid')
('Romero y tomillo', 'Bólido Comidas preparadas', 'Madrid')
('Romero y tomillo', 'FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Ana Trujillo Emparedados y helados', 'Antonio Moreno Taquería', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Centro comercial Moctezuma', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Pericles Comidas clásicas', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Tortuga Restaurante', 'México D.F.')
('Antonio Moreno Taquería', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Antonio Moreno Taquería', 'Centro comercial Moctezuma', 'México D.F.')
('Antonio Moreno Taquería', 'Pericles Comidas clásicas', 'México D.F.')
('Antonio Moreno Taquería', 'Tortuga Restaurante', 'México D.F.')
('Centro comercial Moctezuma', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Centro comercial Moctezuma', 'Antonio Moreno Taquería', 'México D.F.')
('Centro comercial Moctezuma', 'Pericles Comidas clásicas', 'México D.F.')
('Centro comercial Moctezuma', 'Tortuga Restaurante', 'México D.F.')
('Pericles Comidas clásicas', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Pericles Comidas clásicas', 'Antonio Moreno Taquería', 'México D.F.')
('Pericles Comidas clásicas', 'Centro comercial Moctezuma', 'México D.F.')
('Pericles Comidas clásicas', 'Tortuga Restaurante', 'México D.F.')
('Tortuga Restaurante', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Tortuga Restaurante', 'Antonio Moreno Taquería', 'México D.F.')
('Tortuga Restaurante', 'Centro comercial Moctezuma', 'México D.F.')
('Tortuga Restaurante', 'Pericles Comidas clásicas', 'México D.F.')
('Du monde entier', 'France restauration', 'Nantes')
('France restauration', 'Du monde entier', 'Nantes')
('Paris spécialités', 'Spécialités du monde', 'Paris')
('Spécialités du monde', 'Paris spécialités', 'Paris')
('Lonesome Pine Restaurant', 'The Big Cheese', 'Portland')
('The Big Cheese', 'Lonesome Pine Restaurant', 'Portland')
('Hanari Carnes', 'Que Delícia', 'Rio de Janeiro')
('Hanari Carnes', 'Ricardo Adocicados', 'Rio de Janeiro')
('Que Delícia', 'Hanari Carnes', 'Rio de Janeiro')
('Que Delícia', 'Ricardo Adocicados', 'Rio de Janeiro')
('Ricardo Adocicados', 'Hanari Carnes', 'Rio de Janeiro')
('Ricardo Adocicados', 'Que Delícia', 'Rio de Janeiro')
('Comércio Mineiro', 'Familia Arquibaldo', 'São Paulo')
('Comércio Mineiro', 'Queen Cozinha', 'São Paulo')
('Comércio Mineiro', 'Tradição Hipermercados', 'São Paulo')
('Familia Arquibaldo', 'Comércio Mineiro', 'São Paulo')
('Familia Arquibaldo', 'Queen Cozinha', 'São Paulo')
('Familia Arquibaldo', 'Tradição Hipermercados', 'São Paulo')
('Queen Cozinha', 'Comércio Mineiro', 'São Paulo')
('Queen Cozinha', 'Familia Arquibaldo', 'São Paulo')
('Queen Cozinha', 'Tradição Hipermercados', 'São Paulo')
('Tradição Hipermercados', 'Comércio Mineiro', 'São Paulo')
('Tradição Hipermercados', 'Familia Arquibaldo', 'São Paulo')
('Tradição Hipermercados', 'Queen Cozinha', 'São Paulo')

### SQL UNION Operator
- 두 개 이상의 SELECT 문의 결과를 결합하는 데 사용됨.
- 각 SELECT 문은 동일한 컬럼 수, 데이터 타입을 가져야 함.
- 컬럼도 같은 순서여야 함.


```sql
SELECT column_name(s) FROM table1
UNION
SELECT column_name(s) FROM table2;
```

### SQL UNION ALL Operator
- UNION과 동일하지만 중복된 레코드도 모두 반환함.

```sql
SELECT column_name(s) FROM table1
UNION ALL
SELECT column_name(s) FROM table2;
```

In [45]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL UNION Example
    print("SQL UNION Example: 중복이 없다")

    cursor.execute(
        '''
        SELECT City FROM Customers
        UNION
        SELECT City FROM Suppliers
        ORDER BY City;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # SQL UNION ALL Example
    print("SQL UNION ALL Example: 중복이 있다.")

    cursor.execute(
        '''
        SELECT City FROM Customers
        UNION ALL
        SELECT City FROM Suppliers
        ORDER BY City;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # SQL UNION With WHERE
    print("SQL UNION With WHERE: 중복이 있다.")

    cursor.execute(
        '''
        SELECT City, Country FROM Customers
        WHERE Country='Germany'
        UNION
        SELECT City, Country FROM Suppliers
        WHERE Country='Germany'
        ORDER BY City;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
   
    # SQL UNION ALL With WHERE
    print("SQL UNION ALL With WHERE: 중복이 있다.")

    cursor.execute(
        '''
        SELECT City, Country FROM Customers
        WHERE Country='Germany'
        UNION ALL
        SELECT City, Country FROM Suppliers
        WHERE Country='Germany'
        ORDER BY City;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # Another UNION Example
    print("Another UNION Example: Alias를 사용하여 컬럼명을 바꾸고, 어느 소속인지 알 수 있게 한다.")

    cursor.execute(
        '''
        SELECT 'Customer' AS Type, ContactName, City, Country
        FROM Customers
        UNION
        SELECT 'Supplier', ContactName, City, Country
        FROM Suppliers;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL UNION Example: 중복이 없다
조회된 행의 수: 94
('Aachen',)
('Albuquerque',)
('Anchorage',)
('Ann Arbor',)
('Annecy',)
('Barcelona',)
('Barquisimeto',)
('Bend',)
('Bergamo',)
('Berlin',)
('Bern',)
('Boise',)
('Boston',)
('Brandenburg',)
('Bruxelles',)
('Bräcke',)
('Buenos Aires',)
('Butte',)
('Campinas',)
('Caracas',)
('Charleroi',)
('Cork',)
('Cowes',)
('Cunewalde',)
('Cuxhaven',)
('Elgin',)
('Eugene',)
('Frankfurt',)
('Frankfurt a.M.',)
('Genève',)
('Graz',)
('Göteborg',)
('Helsinki',)
('I. de Margarita',)
('Kirkland',)
('Köln',)
('København',)
('Lander',)
('Lappeenranta',)
('Leipzig',)
('Lille',)
('Lisboa',)
('London',)
('Londona',)
('Luleå',)
('Lyngby',)
('Lyon',)
('Madrid',)
('Manchester',)
('Mannheim',)
('Marseille',)
('Melbourne',)
('Montceau',)
('Montréal',)
('México D.F.',)
('München',)
('Münster',)
('Nantes',)
('New Orleans',)
('Osaka',)
('Oulu',)
('Oviedo',)
('Paris',)
('Portland',)
('Ravenna',)
('Reggio Emilia',)
('Reims',)
('Resende',)
('Rio de Janeiro',)
('Salerno',)
('Salzburg',)
('San Cristóbal',)
('San Francisco',)
('Sandvika',)
('Seattle',)
('Sevilla',)
('Singapore',)
('Stavern',)
('Ste-Hyacinthe',)
('Stockholm',)
('Strasbourg',)
('Stuttgart',)
('Sydney',)
('São Paulo',)
('Tokyo',)
('Torino',)
('Toulouse',)
('Tsawassen',)
('Vancouver',)
('Versailles',)
('Walla',)
('Walla Walla',)
('Zaandam',)
('Århus',)
SQL UNION ALL Example: 중복이 있다.
조회된 행의 수: 120
('Aachen',)
('Albuquerque',)
('Anchorage',)
('Ann Arbor',)
('Annecy',)
('Barcelona',)
('Barquisimeto',)
('Bend',)
('Bergamo',)
('Berlin',)
('Berlin',)
('Bern',)
('Boise',)
('Boston',)
('Brandenburg',)
('Bruxelles',)
('Bräcke',)
('Buenos Aires',)
('Buenos Aires',)
('Buenos Aires',)
('Butte',)
('Campinas',)
('Caracas',)
('Charleroi',)
('Cork',)
('Cowes',)
('Cunewalde',)
('Cuxhaven',)
('Elgin',)
('Eugene',)
('Frankfurt',)
('Frankfurt a.M.',)
('Genève',)
('Graz',)
('Göteborg',)
('Helsinki',)
('I. de Margarita',)
('Kirkland',)
('Köln',)
('København',)
('Lander',)
('Lappeenranta',)
('Leipzig',)
('Lille',)
('Lisboa',)
('Lisboa',)
('London',)
('London',)
('London',)
('London',)
('London',)
('London',)
('Londona',)
('Luleå',)
('Lyngby',)
('Lyon',)
('Madrid',)
('Madrid',)
('Madrid',)
('Manchester',)
('Mannheim',)
('Marseille',)
('Melbourne',)
('Montceau',)
('Montréal',)
('Montréal',)
('México D.F.',)
('México D.F.',)
('México D.F.',)
('México D.F.',)
('México D.F.',)
('München',)
('Münster',)
('Nantes',)
('Nantes',)
('New Orleans',)
('Osaka',)
('Oulu',)
('Oviedo',)
('Paris',)
('Paris',)
('Paris',)
('Portland',)
('Portland',)
('Ravenna',)
('Reggio Emilia',)
('Reims',)
('Resende',)
('Rio de Janeiro',)
('Rio de Janeiro',)
('Rio de Janeiro',)
('Salerno',)
('Salzburg',)
('San Cristóbal',)
('San Francisco',)
('Sandvika',)
('Seattle',)
('Sevilla',)
('Singapore',)
('Stavern',)
('Ste-Hyacinthe',)
('Stockholm',)
('Strasbourg',)
('Stuttgart',)
('Sydney',)
('São Paulo',)
('São Paulo',)
('São Paulo',)
('São Paulo',)
('São Paulo',)
('Tokyo',)
('Torino',)
('Toulouse',)
('Tsawassen',)
('Vancouver',)
('Versailles',)
('Walla',)
('Walla Walla',)
('Zaandam',)
('Århus',)
SQL UNION With WHERE: 중복이 있다.
조회된 행의 수: 13
('Aachen', 'Germany')
('Berlin', 'Germany')
('Brandenburg', 'Germany')
('Cunewalde', 'Germany')
('Cuxhaven', 'Germany')
('Frankfurt', 'Germany')
('Frankfurt a.M.', 'Germany')
('Köln', 'Germany')
('Leipzig', 'Germany')
('Mannheim', 'Germany')
('München', 'Germany')
('Münster', 'Germany')
('Stuttgart', 'Germany')
SQL UNION ALL With WHERE: 중복이 있다.
조회된 행의 수: 14
('Aachen', 'Germany')
('Berlin', 'Germany')
('Berlin', 'Germany')
('Brandenburg', 'Germany')
('Cunewalde', 'Germany')
('Cuxhaven', 'Germany')
('Frankfurt', 'Germany')
('Frankfurt a.M.', 'Germany')
('Köln', 'Germany')
('Leipzig', 'Germany')
('Mannheim', 'Germany')
('München', 'Germany')
('Münster', 'Germany')
('Stuttgart', 'Germany')
Another UNION Example: Alias를 사용하여 컬럼명을 바꾸고, 어느 소속인지 알 수 있게 한다.
조회된 행의 수: 120
('Customer', 'Alejandra Camino', 'Madrid', 'Spain')
('Customer', 'Alexander Feuer', 'Leipzig', 'Germany')
('Customer', 'Ana Trujillo', 'México D.F.', 'Mexico')
('Customer', 'Anabela Domingues', 'São Paulo', 'Brazil')
('Customer', 'André Fonseca', 'Campinas', 'Brazil')
('Customer', 'Ann Devon', 'London', 'UK')
('Customer', 'Annette Roulet', 'Toulouse', 'France')
('Customer', 'Antonio Moreno', 'México D.F.', 'Mexico')
('Customer', 'Aria Cruz', 'São Paulo', 'Brazil')
('Customer', 'Art Braunschweiger', 'Lander', 'USA')
('Customer', 'Bernardo Batista', 'Rio de Janeiro', 'Brazil')
('Customer', 'Carine Schmitt', 'Nantes', 'France')
('Customer', 'Carlos González', 'Barquisimeto', 'Venezuela')
('Customer', 'Carlos Hernández', 'San Cristóbal', 'Venezuela')
('Customer', 'Catherine Dewey', 'Bruxelles', 'Belgium')
('Customer', 'Christina Berglund', 'Luleå', 'Sweden')
('Customer', 'Daniel Tonini', 'Versailles', 'France')
('Customer', 'Diego Roel', 'Madrid', 'Spain')
('Customer', 'Dominique Perrier', 'Paris', 'France')
('Customer', 'Eduardo Saavedra', 'Barcelona', 'Spain')
('Customer', 'Elizabeth Brown', 'London', 'UK')
('Customer', 'Elizabeth Lincoln', 'Tsawassen', 'Canada')
('Customer', 'Felipe Izquierdo', 'I. de Margarita', 'Venezuela')
('Customer', 'Fran Wilson', 'Portland', 'USA')
('Customer', 'Francisco Chang', 'México D.F.', 'Mexico')
('Customer', 'Frédérique Citeaux', 'Strasbourg', 'France')
('Customer', 'Georg Pipps', 'Salzburg', 'Austria')
('Customer', 'Giovanni Rovelli', 'Bergamo', 'Italy')
('Customer', 'Guillermo Fernández', 'México D.F.', 'Mexico')
('Customer', 'Hanna Moos', 'Mannheim', 'Germany')
('Customer', 'Hari Kumar', 'London', 'UK')
('Customer', 'Helen Bennett', 'Cowes', 'UK')
('Customer', 'Helvetius Nagy', 'Kirkland', 'USA')
('Customer', 'Henriette Pfalzheim', 'Köln', 'Germany')
('Customer', 'Horst Kloss', 'Cunewalde', 'Germany')
('Customer', 'Howard Snyder', 'Eugene', 'USA')
('Customer', 'Isabel de Castro', 'Lisboa', 'Portugal')
('Customer', 'Jaime Yorres', 'San Francisco', 'USA')
('Customer', 'Janete Limeira', 'Rio de Janeiro', 'Brazil')
('Customer', 'Janine Labrune', 'Nantes', 'France')
('Customer', 'Jean Fresnière', 'Montréal', 'Canada')
('Customer', 'John Steel', 'Walla Walla', 'USA')
('Customer', 'Jonas Bergulfsen', 'Stavern', 'Norway')
('Customer', 'Jose Pavarotti', 'Boise', 'USA')
('Customer', 'José Pedro Freyre', 'Sevilla', 'Spain')
('Customer', 'Jytte Petersen', 'København', 'Denmark')
('Customer', 'Karin Josephs', 'Münster', 'Germany')
('Customer', 'Karl Jablonski', 'Seattle', 'USA')
('Customer', 'Laurence Lebihans', 'Marseille', 'France')
('Customer', 'Lino Rodriguez', 'Lisboa', 'Portugal')
('Customer', 'Liu Wong', 'Butte', 'USA')
('Customer', 'Liz Nixon', 'Portland', 'USA')
('Customer', 'Lúcia Carvalho', 'São Paulo', 'Brazil')
('Customer', 'Manuel Pereira', 'Caracas', 'Venezuela')
('Customer', 'Maria Anders', 'Berlin', 'Germany')
('Customer', 'Maria Larsson', 'Bräcke', 'Sweden')
('Customer', 'Marie Bertrand', 'Paris', 'France')
('Customer', 'Mario Pontes', 'Rio de Janeiro', 'Brazil')
('Customer', 'Martine Rancé', 'Lille', 'France')
('Customer', 'Martín Sommer', 'Madrid', 'Spain')
('Customer', 'Mary Saveley', 'Lyon', 'France')
('Customer', 'Matti Karttunen', 'Helsinki', 'Finland')
('Customer', 'Maurizio Moroni', 'Reggio Emilia', 'Italy')
('Customer', 'Michael Holz', 'Genève', 'Switzerland')
('Customer', 'Miguel Angel Paolino', 'México D.F.', 'Mexico')
('Customer', 'Palle Ibsen', 'Århus', 'Denmark')
('Customer', 'Paolo Accorti', 'Torino', 'Italy')
('Customer', 'Pascale Cartrain', 'Charleroi', 'Belgium')
('Customer', 'Patricia McKenna', 'Cork', 'Ireland')
('Customer', 'Patricio Simpson', 'Buenos Aires', 'Argentina')
('Customer', 'Paul Henriot', 'Reims', 'France')
('Customer', 'Paula Parente', 'Resende', 'Brazil')
('Customer', 'Paula Wilson', 'Albuquerque', 'USA')
('Customer', 'Pedro Afonso', 'São Paulo', 'Brazil')
('Customer', 'Peter Franken', 'München', 'Germany')
('Customer', 'Philip Cramer', 'Brandenburg', 'Germany')
('Customer', 'Pirkko Koskitalo', 'Oulu', 'Finland')
('Customer', 'Renate Messner', 'Frankfurt a.M.', 'Germany')
('Customer', 'Rene Phillips', 'Anchorage', 'USA')
('Customer', 'Rita Müller', 'Stuttgart', 'Germany')
('Customer', 'Roland Mendel', 'Graz', 'Austria')
('Customer', 'Sergio Gutiérrez', 'Buenos Aires', 'Argentina')
('Customer', 'Simon Crowther', 'London', 'UK')
('Customer', 'Sven Ottlieb', 'Aachen', 'Germany')
('Customer', 'Thomas Hardy', 'London', 'UK')
('Customer', 'Victoria Ashworth', 'London', 'UK')
('Customer', 'Yang Wang', 'Bern', 'Switzerland')
('Customer', 'Yoshi Latimer', 'Elgin', 'USA')
('Customer', 'Yoshi Tannamuri', 'Vancouver', 'Canada')
('Customer', 'Yvonne Moncada', 'Buenos Aires', 'Argentina')
('Customer', 'Zbyszek', 'Walla', 'Poland')
('Supplier', 'Anne Heikkonen', 'Lappeenranta', 'Finland')
('Supplier', 'Antonio del Valle Saavedra', 'Oviedo', 'Spain')
('Supplier', 'Beate Vileid', 'Sandvika', 'Norway')
('Supplier', 'Carlos Diaz', 'São Paulo', 'Brazil')
('Supplier', 'Chandra Leka', 'Singapore', 'Singapore')
('Supplier', 'Chantal Goulet', 'Ste-Hyacinthe', 'Canada')
('Supplier', 'Charlotte Cooper', 'Londona', 'UK')
('Supplier', 'Cheryl Saylor', 'Bend', 'USA')
('Supplier', 'Dirk Luchte', 'Zaandam', 'Netherlands')
('Supplier', 'Eliane Noz', 'Annecy', 'France')
('Supplier', 'Elio Rossi', 'Ravenna', 'Italy')
('Supplier', 'Giovanni Giudici', 'Salerno', 'Italy')
('Supplier', 'Guylène Nodier', 'Paris', 'France')
('Supplier', 'Ian Devling', 'Melbourne', 'Australia')
('Supplier', 'Jean-Guy Lauzon', 'Montréal', 'Canada')
('Supplier', 'Lars Peterson', 'Göteborg', 'Sweden')
('Supplier', 'Marie Delamare', 'Montceau', 'France')
('Supplier', 'Martin Bein', 'Frankfurt', 'Germany')
('Supplier', 'Mayumi Ohno', 'Osaka', 'Japan')
('Supplier', 'Michael Björn', 'Stockholm', 'Sweden')
('Supplier', 'Niels Petersen', 'Lyngby', 'Denmark')
('Supplier', 'Peter Wilson', 'Manchester', 'UK')
('Supplier', 'Petra Winkler', 'Berlin', 'Germany')
('Supplier', 'Regina Murphy', 'Ann Arbor', 'USA')
('Supplier', 'Robb Merchant', 'Boston', 'USA')
('Supplier', 'Shelley Burke', 'New Orleans', 'USA')
('Supplier', 'Sven Petersen', 'Cuxhaven', 'Germany')
('Supplier', 'Wendy Mackenzie', 'Sydney', 'Australia')
('Supplier', 'Yoshi Nagase', 'Tokyo', 'Japan')

### SQL GROUP BY Statement

- 집계 함수와 함께 사용됨.

```sql
SELECT column_name(s)
FROM table_name
WHERE condition
ORDER BY column_name(s);
```

In [47]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL GROUP BY Examples
    print("SQL GROUP BY Examples")

    cursor.execute(
        '''
        SELECT COUNT(CustomerID), Country
        FROM Customers
        GROUP BY Country;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # 나라 별 많은 수 순서로 정렬
    print("나라 별 많은 수 순서로 정렬")

    cursor.execute(
        '''
        SELECT COUNT(CustomerID), Country
        FROM Customers
        GROUP BY Country
        ORDER BY COUNT(CustomerID) DESC;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # GROUP BY With JOIN Example
    print("GROUP BY With JOIN Example")

    cursor.execute(
        '''
        SELECT s.ShipperName, COUNT(o.OrderID) AS NumberOfOrders FROM Orders o
        LEFT JOIN Shippers s ON o.ShipperID = s.ShipperID
        GROUP BY ShipperName;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL GROUP BY Examples
조회된 행의 수: 21
(3, 'Argentina')
(2, 'Austria')
(2, 'Belgium')
(9, 'Brazil')
(3, 'Canada')
(2, 'Denmark')
(2, 'Finland')
(11, 'France')
(11, 'Germany')
(1, 'Ireland')
(3, 'Italy')
(5, 'Mexico')
(1, 'Norway')
(1, 'Poland')
(2, 'Portugal')
(5, 'Spain')
(2, 'Sweden')
(2, 'Switzerland')
(7, 'UK')
(13, 'USA')
(4, 'Venezuela')
나라 별 많은 수 순서로 정렬
조회된 행의 수: 21
(13, 'USA')
(11, 'Germany')
(11, 'France')
(9, 'Brazil')
(7, 'UK')
(5, 'Spain')
(5, 'Mexico')
(4, 'Venezuela')
(3, 'Italy')
(3, 'Canada')
(3, 'Argentina')
(2, 'Switzerland')
(2, 'Sweden')
(2, 'Portugal')
(2, 'Finland')
(2, 'Denmark')
(2, 'Belgium')
(2, 'Austria')
(1, 'Poland')
(1, 'Norway')
(1, 'Ireland')
GROUP BY With JOIN Example
조회된 행의 수: 3
('Federal Shipping', 68)
('Speedy Express', 54)
('United Package', 74)

### SQL HAVING Clause
- Having은 GROUP BY 절과 함께 사용됨.
- WHERE는 레코드를 필터링하는 데 사용되고, HAVING은 그룹을 필터링하는 데 사용됨.

```sql
SELECT column_name(s)
FROM table_name
WHERE condition
GROUP BY column_name(s)
HAVING condition
ORDER BY column_name(s);
```

In [48]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL HAVING Examples
    print("SQL HAVING Examples")

    cursor.execute(
        '''
        SELECT COUNT(CustomerID), Country
        FROM Customers
        GROUP BY Country
        HAVING COUNT(CustomerID) > 5;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
 
    cursor.execute(
        '''
        SELECT COUNT(CustomerID), Country
        FROM Customers
        GROUP BY Country
        HAVING COUNT(CustomerID) > 5
        ORDER BY COUNT(CustomerID) DESC;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
    
    # More HAVING Examples
    print("More HAVING Examples")

    cursor.execute(
        '''
        SELECT Employees.LastName, COUNT(Orders.OrderID) AS NumberOfOrders
        FROM (Orders
        INNER JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID)
        GROUP BY LastName
        HAVING COUNT(Orders.OrderID) > 10;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

    # WHERE 절 추가
    print("WHERE 절 추가")

    cursor.execute(
        '''
        SELECT Employees.LastName, COUNT(Orders.OrderID) AS NumberOfOrders
        FROM Orders
        INNER JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID
        WHERE LastName = 'Davolio' OR LastName = 'Fuller'
        GROUP BY LastName
        HAVING COUNT(Orders.OrderID) > 25;
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL HAVING Examples
조회된 행의 수: 5
(9, 'Brazil')
(11, 'France')
(11, 'Germany')
(7, 'UK')
(13, 'USA')
조회된 행의 수: 5
(13, 'USA')
(11, 'Germany')
(11, 'France')
(9, 'Brazil')
(7, 'UK')
More HAVING Examples
조회된 행의 수: 8
('Buchanan', 11)
('Callahan', 27)
('Davolio', 29)
('Fuller', 20)
('King', 14)
('Leverling', 31)
('Peacock', 40)
('Suyama', 18)
WHERE 절 추가
조회된 행의 수: 1
('Davolio', 29)

### SQL EXIST Operator
- 서브쿼리의 결과가 존재하는지 확인하는 데 사용됨.

```sql
SELECT column_name(s)
FROM table_name
WHERE EXISTS
(SELECT column_name FROM table_name WHERE condition);
```

In [49]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL EXISTS Examples
    print("SQL EXISTS Examples")

    cursor.execute(
        '''
        SELECT SupplierName
        FROM Suppliers
        WHERE EXISTS (SELECT ProductName FROM Products 
        WHERE Products.SupplierID = Suppliers.supplierID AND Price < 20);
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)
 
    cursor.execute(
        '''
        SELECT SupplierName
        FROM Suppliers
        WHERE EXISTS (SELECT ProductName FROM Products 
        WHERE Products.SupplierID = Suppliers.supplierID AND Price = 22);
        '''
    )
    rows = cursor.fetchall()
    print(f"조회된 행의 수: {len(rows)}")
    for row in rows:
        print(row)

SQL EXISTS Examples
조회된 행의 수: 24
('Exotic Liquid',)
('New Orleans Cajun Delights',)
('Tokyo Traders',)
("Mayumi's",)
('Pavlova, Ltd.',)
('Specialty Biscuits, Ltd.',)
('PB Knäckebröd AB',)
('Refrescos Americanas LTDA',)
('Heli Süßwaren GmbH & Co. KG',)
('Plutzer Lebensmittelgroßmärkte AG',)
('Formaggi Fortini s.r.l.',)
('Norske Meierier',)
('Bigfoot Breweries',)
('Svensk Sjöföda AB',)
('Aux joyeux ecclésiastiques',)
('New England Seafood Cannery',)
('Leka Trading',)
('Lyngbysild',)
('Zaanse Snoepfabriek',)
('Karkki Oy',)
("G'day, Mate",)
('Ma Maison',)
('Pasta Buttini s.r.l.',)
('Escargots Nouveaux',)
조회된 행의 수: 1
('New Orleans Cajun Delights',)

### SQL ANY and ALL Operators
- 서브쿼리의 결과가 ANY 또는 ALL 조건과 일치하는지 확인하는 데 사용됨.
- ANY는 서브쿼리의 결과 중 하나라도 조건과 일치하면 TRUE를 반환함.
- ALL은 서브쿼리의 결과가 모두 조건과 일치하면 TRUE를 반환함.

```sql
SELECT column_name(s)
FROM table_name
WHERE column_name operator ANY
  (SELECT column_name
  FROM table_name
  WHERE condition);
```

- ALL은 모든 조건이 일치해야 함.
- SELECT, WHERE, HAVING 절에서 사용됨.

In [52]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL ANY Examples
    print("SQL ANY Examples")

    
    '''
    SELECT ProductName
    FROM Products
    WHERE ProductID = ANY(SELECT ProductID
    FROM OrderDetails
    WHERE Quantity = 10);
    '''
    
    
    '''
    SELECT ProductName
    FROM Products
    WHERE ProductID = ANY
    (SELECT ProductID
    FROM OrderDetails
    WHERE Quantity > 99);
    '''
   
    # SQL ALL Examples
    print("SQL ALL Examples")

    
    '''
    SELECT ALL ProductName
    FROM Products
    WHERE TRUE;
    '''
    
    
    '''
    SELECT ProductName
    FROM Products
    WHERE ProductID = ALL
    (SELECT ProductID
    FROM OrderDetails
    WHERE Quantity = 10);
    '''

SQL ANY Examples
SQL ALL Examples

### SQL SELECT INTO Statement

- SELECT 문의 결과를 새 테이블로 복사하는 데 사용됨.

```sql
SELECT *
INTO newtable [IN externaldb]
FROM oldtable
WHERE condition;
```

- 몇 개의 컬럼만 복사할 수도 있음.
```sql
SELECT column1, column2, column3, ...
INTO newtable [IN externaldb]
FROM oldtable
WHERE condition;
```
- AS를 사용하여 컬럼명을 변경할 수도 있음.

In [21]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL SELECT INTO Examples
    print("SQL SELECT INTO Examples")

    
    '''
    SELECT * INTO CustomersBackup2017
    FROM Customers;
    '''

    print("IN 사용 시에 Backup.db에 저장도 가능하다.") 
 
    '''
    SELECT * INTO CustomersBackup2017 IN 'Backup.mdb'
    FROM Customers;
    '''
    
    '''
    SELECT * INTO CustomersGermany
    FROM Customers
    WHERE Country = 'Germany';
    '''
    
    '''
    SELECT Customers.CustomerName, Orders.OrderID
    INTO CustomersOrderBackup2017
    FROM Customers
    LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID;
    '''

    print("테이블의 스키마만 복사하고 싶은 경우.")
    '''
    SELECT * INTO newtable
    FROM oldtable
    WHERE 1 = 0;
    '''

SQL SELECT INTO Examples
IN 사용 시에 Backup.db에 저장도 가능하다.
테이블의 스키마만 복사하고 싶은 경우.

### SQL INSERT INTO SELECT Statement

- SELECT 문의 결과를 다른 테이블에 삽입하는 데 사용됨.

```sql
INSERT INTO table2
SELECT * FROM table1
WHERE condition;
```

In [4]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL INSERT INTO SELECT Examples
    print("SQL INSERT INTO SELECT Examples: 없으면 NULL로 들어간다.")

    cursor.execute(
        '''
        INSERT INTO Customers (CustomerName, City, Country)
        SELECT SupplierName, City, Country FROM Suppliers;
        '''
    )
    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()
 
    cursor.execute(
        '''
        INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country)
        SELECT SupplierName, ContactName, Address, City, PostalCode, Country FROM Suppliers;
        '''
    )
    
    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()
    
    cursor.execute(
        '''
        INSERT INTO Customers (CustomerName, City, Country)
        SELECT SupplierName, City, Country FROM Suppliers
        WHERE Country='Germany';
        '''
    )

    affected_rows = cursor.rowcount
    print(f"영향받은 행의 수: {affected_rows}")

    conn.rollback()

SQL INSERT INTO SELECT Examples: 없으면 NULL로 들어간다.
영향받은 행의 수: 29
영향받은 행의 수: 29
영향받은 행의 수: 3

### SQL CASE Statement
- IF-THEN-ELSE 문과 유사함.
- SELECT, WHERE, HAVING 절에서 사용됨.

```sql
CASE
  WHEN condition1 THEN result1
  WHEN condition2 THEN result2
  WHEN conditionN THEN resultN
  ELSE result
END;
```

In [5]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # SQL CASE Examples
    print("SQL CASE Examples")

    cursor.execute(
        '''
        SELECT OrderID, Quantity,
        CASE
            WHEN Quantity > 30 THEN 'The quantity is greater than 30'
            WHEN Quantity = 30 THEN 'The quantity is 30'
            ELSE 'The quantity is under 30'
        END AS QuantityText
        FROM OrderDetails;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    print("Case를 사용한 NULL 처리")

    cursor.execute(
        '''
        SELECT CustomerName, City, Country
        FROM Customers
        ORDER BY
        (CASE
            WHEN City IS NULL THEN Country
            ELSE City
        END);
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

SQL CASE Examples
(10248, 12, 'The quantity is under 30')
(10248, 10, 'The quantity is under 30')
(10248, 5, 'The quantity is under 30')
(10249, 9, 'The quantity is under 30')
(10249, 40, 'The quantity is greater than 30')
(10250, 10, 'The quantity is under 30')
(10250, 35, 'The quantity is greater than 30')
(10250, 15, 'The quantity is under 30')
(10251, 6, 'The quantity is under 30')
(10251, 15, 'The quantity is under 30')
(10251, 20, 'The quantity is under 30')
(10252, 40, 'The quantity is greater than 30')
(10252, 25, 'The quantity is under 30')
(10252, 40, 'The quantity is greater than 30')
(10253, 20, 'The quantity is under 30')
(10253, 42, 'The quantity is greater than 30')
(10253, 40, 'The quantity is greater than 30')
(10254, 15, 'The quantity is under 30')
(10254, 21, 'The quantity is under 30')
(10254, 21, 'The quantity is under 30')
(10255, 20, 'The quantity is under 30')
(10255, 35, 'The quantity is greater than 30')
(10255, 25, 'The quantity is under 30')
(10255, 30, 'The quantity is 30')
(10256, 15, 'The quantity is under 30')
(10256, 12, 'The quantity is under 30')
(10257, 25, 'The quantity is under 30')
(10257, 6, 'The quantity is under 30')
(10257, 15, 'The quantity is under 30')
(10258, 50, 'The quantity is greater than 30')
(10258, 65, 'The quantity is greater than 30')
(10258, 6, 'The quantity is under 30')
(10259, 10, 'The quantity is under 30')
(10259, 1, 'The quantity is under 30')
(10260, 16, 'The quantity is under 30')
(10260, 50, 'The quantity is greater than 30')
(10260, 15, 'The quantity is under 30')
(10260, 21, 'The quantity is under 30')
(10261, 20, 'The quantity is under 30')
(10261, 20, 'The quantity is under 30')
(10262, 12, 'The quantity is under 30')
(10262, 15, 'The quantity is under 30')
(10262, 2, 'The quantity is under 30')
(10263, 60, 'The quantity is greater than 30')
(10263, 28, 'The quantity is under 30')
(10263, 60, 'The quantity is greater than 30')
(10263, 36, 'The quantity is greater than 30')
(10264, 35, 'The quantity is greater than 30')
(10264, 25, 'The quantity is under 30')
(10265, 30, 'The quantity is 30')
(10265, 20, 'The quantity is under 30')
(10266, 12, 'The quantity is under 30')
(10267, 50, 'The quantity is greater than 30')
(10267, 70, 'The quantity is greater than 30')
(10267, 15, 'The quantity is under 30')
(10268, 10, 'The quantity is under 30')
(10268, 4, 'The quantity is under 30')
(10269, 60, 'The quantity is greater than 30')
(10269, 20, 'The quantity is under 30')
(10270, 30, 'The quantity is 30')
(10270, 25, 'The quantity is under 30')
(10271, 24, 'The quantity is under 30')
(10272, 6, 'The quantity is under 30')
(10272, 40, 'The quantity is greater than 30')
(10272, 24, 'The quantity is under 30')
(10273, 24, 'The quantity is under 30')
(10273, 15, 'The quantity is under 30')
(10273, 20, 'The quantity is under 30')
(10273, 60, 'The quantity is greater than 30')
(10273, 33, 'The quantity is greater than 30')
(10274, 20, 'The quantity is under 30')
(10274, 7, 'The quantity is under 30')
(10275, 12, 'The quantity is under 30')
(10275, 6, 'The quantity is under 30')
(10276, 15, 'The quantity is under 30')
(10276, 10, 'The quantity is under 30')
(10277, 20, 'The quantity is under 30')
(10277, 12, 'The quantity is under 30')
(10278, 16, 'The quantity is under 30')
(10278, 15, 'The quantity is under 30')
(10278, 8, 'The quantity is under 30')
(10278, 25, 'The quantity is under 30')
(10279, 15, 'The quantity is under 30')
(10280, 12, 'The quantity is under 30')
(10280, 20, 'The quantity is under 30')
(10280, 30, 'The quantity is 30')
(10281, 1, 'The quantity is under 30')
(10281, 6, 'The quantity is under 30')
(10281, 4, 'The quantity is under 30')
(10282, 6, 'The quantity is under 30')
(10282, 2, 'The quantity is under 30')
(10283, 20, 'The quantity is under 30')
(10283, 18, 'The quantity is under 30')
(10283, 35, 'The quantity is greater than 30')
(10283, 3, 'The quantity is under 30')
(10284, 15, 'The quantity is under 30')
(10284, 21, 'The quantity is under 30')
(10284, 20, 'The quantity is under 30')
(10284, 5, 'The quantity is under 30')
(10285, 45, 'The quantity is greater than 30')
(10285, 40, 'The quantity is greater than 30')
(10285, 36, 'The quantity is greater than 30')
(10286, 100, 'The quantity is greater than 30')
(10286, 40, 'The quantity is greater than 30')
(10287, 40, 'The quantity is greater than 30')
(10287, 20, 'The quantity is under 30')
(10287, 15, 'The quantity is under 30')
(10288, 10, 'The quantity is under 30')
(10288, 3, 'The quantity is under 30')
(10289, 30, 'The quantity is 30')
(10289, 9, 'The quantity is under 30')
(10290, 20, 'The quantity is under 30')
(10290, 15, 'The quantity is under 30')
(10290, 15, 'The quantity is under 30')
(10290, 10, 'The quantity is under 30')
(10291, 20, 'The quantity is under 30')
(10291, 24, 'The quantity is under 30')
(10291, 2, 'The quantity is under 30')
(10292, 20, 'The quantity is under 30')
(10293, 12, 'The quantity is under 30')
(10293, 10, 'The quantity is under 30')
(10293, 5, 'The quantity is under 30')
(10293, 6, 'The quantity is under 30')
(10294, 18, 'The quantity is under 30')
(10294, 15, 'The quantity is under 30')
(10294, 15, 'The quantity is under 30')
(10294, 21, 'The quantity is under 30')
(10294, 6, 'The quantity is under 30')
(10295, 4, 'The quantity is under 30')
(10296, 12, 'The quantity is under 30')
(10296, 30, 'The quantity is 30')
(10296, 15, 'The quantity is under 30')
(10297, 60, 'The quantity is greater than 30')
(10297, 20, 'The quantity is under 30')
(10298, 40, 'The quantity is greater than 30')
(10298, 40, 'The quantity is greater than 30')
(10298, 30, 'The quantity is 30')
(10298, 15, 'The quantity is under 30')
(10299, 15, 'The quantity is under 30')
(10299, 20, 'The quantity is under 30')
(10300, 30, 'The quantity is 30')
(10300, 20, 'The quantity is under 30')
(10301, 10, 'The quantity is under 30')
(10301, 20, 'The quantity is under 30')
(10302, 40, 'The quantity is greater than 30')
(10302, 28, 'The quantity is under 30')
(10302, 12, 'The quantity is under 30')
(10303, 40, 'The quantity is greater than 30')
(10303, 30, 'The quantity is 30')
(10303, 15, 'The quantity is under 30')
(10304, 30, 'The quantity is 30')
(10304, 10, 'The quantity is under 30')
(10304, 2, 'The quantity is under 30')
(10305, 25, 'The quantity is under 30')
(10305, 25, 'The quantity is under 30')
(10305, 30, 'The quantity is 30')
(10306, 10, 'The quantity is under 30')
(10306, 10, 'The quantity is under 30')
(10306, 5, 'The quantity is under 30')
(10307, 10, 'The quantity is under 30')
(10307, 3, 'The quantity is under 30')
(10308, 1, 'The quantity is under 30')
(10308, 5, 'The quantity is under 30')
(10309, 20, 'The quantity is under 30')
(10309, 30, 'The quantity is 30')
(10309, 2, 'The quantity is under 30')
(10309, 20, 'The quantity is under 30')
(10309, 3, 'The quantity is under 30')
(10310, 10, 'The quantity is under 30')
(10310, 5, 'The quantity is under 30')
(10311, 6, 'The quantity is under 30')
(10311, 7, 'The quantity is under 30')
(10312, 4, 'The quantity is under 30')
(10312, 24, 'The quantity is under 30')
(10312, 20, 'The quantity is under 30')
(10312, 10, 'The quantity is under 30')
(10313, 12, 'The quantity is under 30')
(10314, 40, 'The quantity is greater than 30')
(10314, 30, 'The quantity is 30')
(10314, 25, 'The quantity is under 30')
(10315, 14, 'The quantity is under 30')
(10315, 30, 'The quantity is 30')
(10316, 10, 'The quantity is under 30')
(10316, 70, 'The quantity is greater than 30')
(10317, 20, 'The quantity is under 30')
(10318, 20, 'The quantity is under 30')
(10318, 6, 'The quantity is under 30')
(10319, 8, 'The quantity is under 30')
(10319, 14, 'The quantity is under 30')
(10319, 30, 'The quantity is 30')
(10320, 30, 'The quantity is 30')
(10321, 10, 'The quantity is under 30')
(10322, 20, 'The quantity is under 30')
(10323, 5, 'The quantity is under 30')
(10323, 4, 'The quantity is under 30')
(10323, 4, 'The quantity is under 30')
(10324, 21, 'The quantity is under 30')
(10324, 70, 'The quantity is greater than 30')
(10324, 30, 'The quantity is 30')
(10324, 40, 'The quantity is greater than 30')
(10324, 80, 'The quantity is greater than 30')
(10325, 6, 'The quantity is under 30')
(10325, 12, 'The quantity is under 30')
(10325, 9, 'The quantity is under 30')
(10325, 4, 'The quantity is under 30')
(10325, 40, 'The quantity is greater than 30')
(10326, 24, 'The quantity is under 30')
(10326, 16, 'The quantity is under 30')
(10326, 50, 'The quantity is greater than 30')
(10327, 25, 'The quantity is under 30')
(10327, 50, 'The quantity is greater than 30')
(10327, 35, 'The quantity is greater than 30')
(10327, 30, 'The quantity is 30')
(10328, 9, 'The quantity is under 30')
(10328, 40, 'The quantity is greater than 30')
(10328, 10, 'The quantity is under 30')
(10329, 10, 'The quantity is under 30')
(10329, 8, 'The quantity is under 30')
(10329, 20, 'The quantity is under 30')
(10329, 12, 'The quantity is under 30')
(10330, 50, 'The quantity is greater than 30')
(10330, 25, 'The quantity is under 30')
(10331, 15, 'The quantity is under 30')
(10332, 40, 'The quantity is greater than 30')
(10332, 10, 'The quantity is under 30')
(10332, 16, 'The quantity is under 30')
(10333, 10, 'The quantity is under 30')
(10333, 10, 'The quantity is under 30')
(10333, 40, 'The quantity is greater than 30')
(10334, 8, 'The quantity is under 30')
(10334, 10, 'The quantity is under 30')
(10335, 7, 'The quantity is under 30')
(10335, 25, 'The quantity is under 30')
(10335, 6, 'The quantity is under 30')
(10335, 48, 'The quantity is greater than 30')
(10336, 18, 'The quantity is under 30')
(10337, 40, 'The quantity is greater than 30')
(10337, 24, 'The quantity is under 30')
(10337, 20, 'The quantity is under 30')
(10337, 28, 'The quantity is under 30')
(10337, 25, 'The quantity is under 30')
(10338, 20, 'The quantity is under 30')
(10338, 15, 'The quantity is under 30')
(10339, 10, 'The quantity is under 30')
(10339, 70, 'The quantity is greater than 30')
(10339, 28, 'The quantity is under 30')
(10340, 20, 'The quantity is under 30')
(10340, 12, 'The quantity is under 30')
(10340, 40, 'The quantity is greater than 30')
(10341, 8, 'The quantity is under 30')
(10341, 9, 'The quantity is under 30')
(10342, 24, 'The quantity is under 30')
(10342, 56, 'The quantity is greater than 30')
(10342, 40, 'The quantity is greater than 30')
(10342, 40, 'The quantity is greater than 30')
(10343, 50, 'The quantity is greater than 30')
(10343, 4, 'The quantity is under 30')
(10343, 15, 'The quantity is under 30')
(10344, 35, 'The quantity is greater than 30')
(10344, 70, 'The quantity is greater than 30')
(10345, 70, 'The quantity is greater than 30')
(10345, 80, 'The quantity is greater than 30')
(10345, 9, 'The quantity is under 30')
(10346, 36, 'The quantity is greater than 30')
(10346, 20, 'The quantity is under 30')
(10347, 10, 'The quantity is under 30')
(10347, 50, 'The quantity is greater than 30')
(10347, 4, 'The quantity is under 30')
(10347, 6, 'The quantity is under 30')
(10348, 15, 'The quantity is under 30')
(10348, 25, 'The quantity is under 30')
(10349, 24, 'The quantity is under 30')
(10350, 15, 'The quantity is under 30')
(10350, 18, 'The quantity is under 30')
(10351, 20, 'The quantity is under 30')
(10351, 13, 'The quantity is under 30')
(10351, 77, 'The quantity is greater than 30')
(10351, 10, 'The quantity is under 30')
(10352, 10, 'The quantity is under 30')
(10352, 20, 'The quantity is under 30')
(10353, 12, 'The quantity is under 30')
(10353, 50, 'The quantity is greater than 30')
(10354, 12, 'The quantity is under 30')
(10354, 4, 'The quantity is under 30')
(10355, 25, 'The quantity is under 30')
(10355, 25, 'The quantity is under 30')
(10356, 30, 'The quantity is 30')
(10356, 12, 'The quantity is under 30')
(10356, 20, 'The quantity is under 30')
(10357, 30, 'The quantity is 30')
(10357, 16, 'The quantity is under 30')
(10357, 8, 'The quantity is under 30')
(10358, 10, 'The quantity is under 30')
(10358, 10, 'The quantity is under 30')
(10358, 20, 'The quantity is under 30')
(10359, 56, 'The quantity is greater than 30')
(10359, 70, 'The quantity is greater than 30')
(10359, 80, 'The quantity is greater than 30')
(10360, 30, 'The quantity is 30')
(10360, 35, 'The quantity is greater than 30')
(10360, 10, 'The quantity is under 30')
(10360, 35, 'The quantity is greater than 30')
(10360, 28, 'The quantity is under 30')
(10361, 54, 'The quantity is greater than 30')
(10361, 55, 'The quantity is greater than 30')
(10362, 50, 'The quantity is greater than 30')
(10362, 20, 'The quantity is under 30')
(10362, 24, 'The quantity is under 30')
(10363, 20, 'The quantity is under 30')
(10363, 12, 'The quantity is under 30')
(10363, 12, 'The quantity is under 30')
(10364, 30, 'The quantity is 30')
(10364, 5, 'The quantity is under 30')
(10365, 24, 'The quantity is under 30')
(10366, 5, 'The quantity is under 30')
(10366, 5, 'The quantity is under 30')
(10367, 36, 'The quantity is greater than 30')
(10367, 18, 'The quantity is under 30')
(10367, 15, 'The quantity is under 30')
(10367, 7, 'The quantity is under 30')
(10368, 5, 'The quantity is under 30')
(10368, 13, 'The quantity is under 30')
(10368, 25, 'The quantity is under 30')
(10368, 35, 'The quantity is greater than 30')
(10369, 20, 'The quantity is under 30')
(10369, 18, 'The quantity is under 30')
(10370, 15, 'The quantity is under 30')
(10370, 30, 'The quantity is 30')
(10370, 20, 'The quantity is under 30')
(10371, 6, 'The quantity is under 30')
(10372, 12, 'The quantity is under 30')
(10372, 40, 'The quantity is greater than 30')
(10372, 70, 'The quantity is greater than 30')
(10372, 42, 'The quantity is greater than 30')
(10373, 80, 'The quantity is greater than 30')
(10373, 50, 'The quantity is greater than 30')
(10374, 30, 'The quantity is 30')
(10374, 15, 'The quantity is under 30')
(10375, 15, 'The quantity is under 30')
(10375, 10, 'The quantity is under 30')
(10376, 42, 'The quantity is greater than 30')
(10377, 20, 'The quantity is under 30')
(10377, 20, 'The quantity is under 30')
(10378, 6, 'The quantity is under 30')
(10379, 8, 'The quantity is under 30')
(10379, 16, 'The quantity is under 30')
(10379, 20, 'The quantity is under 30')
(10380, 18, 'The quantity is under 30')
(10380, 20, 'The quantity is under 30')
(10380, 6, 'The quantity is under 30')
(10380, 30, 'The quantity is 30')
(10381, 14, 'The quantity is under 30')
(10382, 32, 'The quantity is greater than 30')
(10382, 9, 'The quantity is under 30')
(10382, 14, 'The quantity is under 30')
(10382, 60, 'The quantity is greater than 30')
(10382, 50, 'The quantity is greater than 30')
(10383, 20, 'The quantity is under 30')
(10383, 15, 'The quantity is under 30')
(10383, 20, 'The quantity is under 30')
(10384, 28, 'The quantity is under 30')
(10384, 15, 'The quantity is under 30')
(10385, 10, 'The quantity is under 30')
(10385, 20, 'The quantity is under 30')
(10385, 8, 'The quantity is under 30')
(10386, 15, 'The quantity is under 30')
(10386, 10, 'The quantity is under 30')
(10387, 15, 'The quantity is under 30')
(10387, 6, 'The quantity is under 30')
(10387, 12, 'The quantity is under 30')
(10387, 15, 'The quantity is under 30')
(10388, 15, 'The quantity is under 30')
(10388, 20, 'The quantity is under 30')
(10388, 40, 'The quantity is greater than 30')
(10389, 16, 'The quantity is under 30')
(10389, 15, 'The quantity is under 30')
(10389, 20, 'The quantity is under 30')
(10389, 30, 'The quantity is 30')
(10390, 60, 'The quantity is greater than 30')
(10390, 40, 'The quantity is greater than 30')
(10390, 45, 'The quantity is greater than 30')
(10390, 24, 'The quantity is under 30')
(10391, 18, 'The quantity is under 30')
(10392, 50, 'The quantity is greater than 30')
(10393, 25, 'The quantity is under 30')
(10393, 42, 'The quantity is greater than 30')
(10393, 7, 'The quantity is under 30')
(10393, 70, 'The quantity is greater than 30')
(10393, 32, 'The quantity is greater than 30')
(10394, 10, 'The quantity is under 30')
(10394, 10, 'The quantity is under 30')
(10395, 28, 'The quantity is under 30')
(10395, 70, 'The quantity is greater than 30')
(10395, 8, 'The quantity is under 30')
(10396, 40, 'The quantity is greater than 30')
(10396, 60, 'The quantity is greater than 30')
(10396, 21, 'The quantity is under 30')
(10397, 10, 'The quantity is under 30')
(10397, 18, 'The quantity is under 30')
(10398, 30, 'The quantity is 30')
(10398, 120, 'The quantity is greater than 30')
(10399, 60, 'The quantity is greater than 30')
(10399, 30, 'The quantity is 30')
(10399, 35, 'The quantity is greater than 30')
(10399, 14, 'The quantity is under 30')
(10400, 21, 'The quantity is under 30')
(10400, 35, 'The quantity is greater than 30')
(10400, 30, 'The quantity is 30')
(10401, 18, 'The quantity is under 30')
(10401, 70, 'The quantity is greater than 30')
(10401, 20, 'The quantity is under 30')
(10401, 60, 'The quantity is greater than 30')
(10402, 60, 'The quantity is greater than 30')
(10402, 65, 'The quantity is greater than 30')
(10403, 21, 'The quantity is under 30')
(10403, 70, 'The quantity is greater than 30')
(10404, 30, 'The quantity is 30')
(10404, 40, 'The quantity is greater than 30')
(10404, 30, 'The quantity is 30')
(10405, 50, 'The quantity is greater than 30')
(10406, 10, 'The quantity is under 30')
(10406, 30, 'The quantity is 30')
(10406, 42, 'The quantity is greater than 30')
(10406, 5, 'The quantity is under 30')
(10406, 2, 'The quantity is under 30')
(10407, 30, 'The quantity is 30')
(10407, 15, 'The quantity is under 30')
(10407, 15, 'The quantity is under 30')
(10408, 10, 'The quantity is under 30')
(10408, 6, 'The quantity is under 30')
(10408, 35, 'The quantity is greater than 30')
(10409, 12, 'The quantity is under 30')
(10409, 12, 'The quantity is under 30')
(10410, 49, 'The quantity is greater than 30')
(10410, 16, 'The quantity is under 30')
(10411, 25, 'The quantity is under 30')
(10411, 40, 'The quantity is greater than 30')
(10411, 9, 'The quantity is under 30')
(10412, 20, 'The quantity is under 30')
(10413, 24, 'The quantity is under 30')
(10413, 40, 'The quantity is greater than 30')
(10413, 14, 'The quantity is under 30')
(10414, 18, 'The quantity is under 30')
(10414, 50, 'The quantity is greater than 30')
(10415, 2, 'The quantity is under 30')
(10415, 20, 'The quantity is under 30')
(10416, 20, 'The quantity is under 30')
(10416, 10, 'The quantity is under 30')
(10416, 20, 'The quantity is under 30')
(10417, 50, 'The quantity is greater than 30')
(10417, 2, 'The quantity is under 30')
(10417, 36, 'The quantity is greater than 30')
(10417, 35, 'The quantity is greater than 30')
(10418, 60, 'The quantity is greater than 30')
(10418, 55, 'The quantity is greater than 30')
(10418, 16, 'The quantity is under 30')
(10418, 15, 'The quantity is under 30')
(10419, 60, 'The quantity is greater than 30')
(10419, 20, 'The quantity is under 30')
(10420, 20, 'The quantity is under 30')
(10420, 2, 'The quantity is under 30')
(10420, 8, 'The quantity is under 30')
(10420, 20, 'The quantity is under 30')
(10421, 4, 'The quantity is under 30')
(10421, 30, 'The quantity is 30')
(10421, 15, 'The quantity is under 30')
(10421, 10, 'The quantity is under 30')
(10422, 2, 'The quantity is under 30')
(10423, 14, 'The quantity is under 30')
(10423, 20, 'The quantity is under 30')
(10424, 60, 'The quantity is greater than 30')
(10424, 49, 'The quantity is greater than 30')
(10424, 30, 'The quantity is 30')
(10425, 10, 'The quantity is under 30')
(10425, 20, 'The quantity is under 30')
(10426, 5, 'The quantity is under 30')
(10426, 7, 'The quantity is under 30')
(10427, 35, 'The quantity is greater than 30')
(10428, 20, 'The quantity is under 30')
(10429, 40, 'The quantity is greater than 30')
(10429, 35, 'The quantity is greater than 30')
(10430, 45, 'The quantity is greater than 30')
(10430, 50, 'The quantity is greater than 30')
(10430, 30, 'The quantity is 30')
(10430, 70, 'The quantity is greater than 30')

### SQL NULL Functions
- NULL 값을 처리하는 데 사용됨.
- ISNULL(), COALESCE(), IFNULL(), NVL()
- MySQL은 IFNULL(), Oracle은 NVL(), SQL Server는 ISNULL()을 사용함.
- COALESCE()는 모든 DBMS에서 사용 가능함.

```sql
SELECT ProductName, UnitPrice * (UnitsInStock + COALESCE(UnitsOnOrder, 0))
FROM Products;
```

In [16]:
with sqlite3.connect("demo.db") as conn:
    cursor = conn.cursor()

    # 기존 테이블이 있다면 삭제
    cursor.execute('DROP TABLE IF EXISTS Products')

    # 테이블 생성
    create_table_sql = '''
    CREATE TABLE Products (
        P_Id INTEGER PRIMARY KEY,
        ProductName TEXT NOT NULL,
        UnitPrice DECIMAL(10,2),
        UnitsInStock INTEGER,
        UnitsOnOrder INTEGER
    )
    '''
    cursor.execute(create_table_sql)

    # 데이터 삽입
    products_data = [
        (1, 'Jarlsberg', 10.45, 16, 15),
        (2, 'Mascarpone', 32.56, 23, None),
        (3, 'Gorgonzola', 15.67, 9, 20)
    ]

    cursor.executemany('INSERT INTO Products VALUES (?,?,?,?,?)', products_data)

    # 변경사항 저장
    conn.commit()

    # SQL NULL 미처리 문제
    print("SQL NULL 미처리 문제: NULL이 포함되어 있으면 결과가 NULL이 된다.")

    cursor.execute(
        '''
        SELECT ProductName, UnitPrice * (UnitsInStock + UnitsOnOrder)
        FROM Products;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    # Solutions
    print("Solutions: COALESCE")

    cursor.execute(
        '''
        SELECT ProductName, UnitPrice * (UnitsInStock + COALESCE(UnitsOnOrder, 0))
        FROM Products;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

SQL NULL 미처리 문제: NULL이 포함되어 있으면 결과가 NULL이 된다.
('Jarlsberg', 323.95)
('Mascarpone', None)
('Gorgonzola', 454.43)
Solutions: COALESCE
('Jarlsberg', 323.95)
('Mascarpone', 748.8800000000001)
('Gorgonzola', 454.43)

### SQL Stored Procedures for SQL Server
- sqlite3는 지원하지 않음. 대신 user defined function을 사용함.
- 저장 프로시저는 데이터베이스에 저장된 SQL 코드 블록임.
- 재사용 가능하고, 성능이 좋음.
- 매개변수를 사용하여 저장 프로시저를 호출할 수 있음.
- 저장 프로시저는 CREATE PROCEDURE 문을 사용하여 생성함.

```sql
CREATE PROCEDURE procedure_name
AS
sql_statement
GO;
```

- 저장 프로시저는 EXECUTE 문을 사용하여 호출함.

```sql
EXEC procedure_name;
```

In [18]:
with sqlite3.connect("demo.db") as conn:
    cursor = conn.cursor()

    # Stored Procedure Example
    print("Stored Procedure Example")

    '''
    CREATE PROCEDURE SelectAllCustomers
    AS
    SELECT * FROM Customers
    GO;
    '''
    
    '''
    EXEC SelectAllCustomers;
    '''
    
    

    # Stored Procedure With One Parameter
    print("Stored Procedure With One Parameter")

    '''
    CREATE PROCEDURE SelectAllCustomers @City nvarchar(30)
    AS
    SELECT * FROM Customers WHERE City = @City
    GO;
    '''
    

    '''
    EXEC SelectAllCustomers @City = 'London';
    '''
   
    # Stored Procedure With Multiple Parameters
    print("Stored Procedure With Multiple Parameters")

    '''
    CREATE PROCEDURE SelectAllCustomers @City nvarchar(30), @PostalCode nvarchar(10)
    AS
    SELECT * FROM Customers WHERE City = @City AND PostalCode = @PostalCode
    GO;
    '''
    
    '''
    EXEC SelectAllCustomers @City = 'London', @PostalCode = 'WA1 1DP';
    '''

Stored Procedure Example
Stored Procedure With One Parameter
Stored Procedure With Multiple Parameters

### 주석 달기

- 한 줄 주석은 --로 시작함.
- 여러 줄 주석은 /*로 시작하여 */로 끝남.

In [20]:
with sqlite3.connect("northwind.db") as conn:
    cursor = conn.cursor()
    # Single Line Comments
    print("Single Line Comments")

    cursor.execute(
        '''
        -- Select all:
        SELECT * FROM Customers;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    cursor.execute(
        '''
        SELECT * FROM Customers -- WHERE City='Berlin';
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # Multi-line Comments
    print("Multi-line Comments")

    cursor.execute(
        '''
        SELECT * FROM Customers WHERE (CustomerName LIKE 'L%'
        OR CustomerName LIKE 'R%' /*OR CustomerName LIKE 'S%'
        OR CustomerName LIKE 'T%'*/ OR CustomerName LIKE 'W%')
        AND Country='USA'
        ORDER BY CustomerName;
        '''
    )
    rows = cursor.fetchall()
    for row in rows:
        print(row)

Single Line Comments
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app''", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B''s Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', '', 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d''abondance", 'Daniel Tonini', "67, avenue de l''Europe", 'Versailles', '78000', 'France')
(41, "La maison d''Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M.', '60528', 'Germany')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '4179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '5033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '1307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail''s Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l''Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland')
Multi-line Comments
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(45, "Let''s Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')

### SQL Operators
- 수치 연산자: +, -, *, /, %
- 비트 연산자: &, |, ^, ~, <<, >>
- 비교 연산자: =, <>, >, <, >=, <=
- 복합 연산자: +=, -=, *=, /=, %=, &=, |=, ^=, <<=, >>=
- 논리 연산자: ALL, AND, ANY, BETWEEN, EXISTS, IN, LIKE, NOT, OR, SOME


복합 비트 연산자 사용법

```sql
-- 권한 관리 시스템
SET @user_permissions = 0;  -- 초기 권한 없음
SET @user_permissions |= 4;  -- 읽기 권한 추가
SET @user_permissions |= 2;  -- 쓰기 권한 추가
SET @user_permissions &= ~4;  -- 읽기 권한 제거
```